### ISSUE TITLE
BGC subset for oxygen producing all NA values

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#100]
```R
library(argoFloats)
bai <- getIndex(filename='merge')
s <- subset(bai, circle=list(longitude=-83, latitude=9, radius=800))
plot(s, which='map') # To get a visual
pax <- c(-92.56199, -87.32731, -83.66646, -79.35555, -88.28529, -92.76727, -92.76727, -92.73306)
pay <- c(15.204447, 12.422940,  9.071727,  5.653489,  5.720514,  5.653489, 10.546261, 15.439032)
a <- subset(s, polygon=list(longitude=pax, latitude=pay))
subo <- subset(a, parameter='DOXY')
profiles <- getProfiles(subo)
argos <- readProfiles(profiles)
pressure <- unlist(argos[["pressure"]])
oxygen <- unlist(argos[["oxygen"]])
summary(oxygen)
```
produces

```R
Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
     NA      NA      NA     NaN      NA      NA   11170 
```

Indicating of the 22 floats that had "DOXY" they were all filled in NA. Any thoughts on this? Is it maybe just 'bad' floats?
```R

**Comment by dankelley** [comment]
I suggest doing e.g.
```R
summary(argos[[1]])
```
to see if that has any oxygen values listed.  If not, then I'd maybe do
```R
unlist(lapply(argos, function(a) any(!is.na(a[["oxygen"]])))
```
an so forth.  The idea is basically to check first if there actually is no DOXY there.

You can also do
```R
str(argos[[1]])
```
to see all of what's in that first profile (or any of the profiles).

**Comment by dankelley** [comment]
NOTE: in our repo, the directory 
```
issues/1xx/100
```
contains a .R file that demonstrates this bug.  You ought to try running that with Rscript.  It uses that trick of making a PNG if run noninteractively. I hope you get the bathymetry without error.  (It is *so* beautiful.)

I don't know what causes the oxygen problem, though.  Did we figure that out in our vf2f yesterday?

**Comment by dankelley** [comment]
This is caused by flag removal, because
```R
argos <- readProfiles(profiles)
argosRaw <- readProfiles(profiles, handleFlags=FALSE)
oxygen <- unlist(argos[["oxygen"]])
oxygenRaw <- unlist(argosRaw[["oxygen"]])
sum(is.na(oxygenRaw)) / length(oxygenRaw)
sum(is.na(oxygen)) / length(oxygen)
```
gives
```R
> sum(is.na(oxygenRaw)) / length(oxygenRaw)
[1] 0
> sum(is.na(oxygen)) / length(oxygen)
[1] 1
>        
```

**Comment by dankelley** [comment]
For the first profile, we have
```R
> table(argos[[1]][["flags"]]$oxygen)

  4
507
```
i.e. all the flags for oxygen equal `4`.  (NOTE: this uses the newly-added syntax that `argos[[1]]` is a shortcut for `argos[["profile",1]]`.)

By contrast, salinity and temperature are flagged with `1`.
```R
> table(argos[[1]][["flags"]]$temperature)

  1
507
> table(argos[[1]][["flags"]]$salinity)

  1
507

```

**Comment by dankelley** [comment]
According to Appendix 4, Reference Table 2 (page 50) of Wong et al. (2018), a flag of 4 means "bad data". I've put the table and the citation below.

# Snapshot of table of flag meanings (from Wong et al 2018)

<img width="596" alt="Screen Shot 2020-05-23 at 6 24 56 AM" src="https://user-images.githubusercontent.com/99469/82727015-295e8100-9cbe-11ea-8743-e716e0103e80.png">

# Citation

Wong, Annie, Robert Keeley, Thierry Carval, and the Argo Data Management Tam. “Argo Quality Control Manual For CTD and Trajectory Data,” 2018. https://www.oceanbestpractices.net/bitstream/handle/11329/450/32470.pdf?sequence=1&isAllowed=y.

**Comment by dankelley** [comment]
I don't know why the data in our `indexMerged` have passed data QC tests, but these have failed.  

Therefore, the solution for this issue is to use `readProfiles(...,handleFlags=FALSE)`.  With that, we will get all the oxygen values, even ones that have failed QC tests.

I will open a new issue on whether we ought to change the default behaviour of `readProfiles()` to have `handleFlags=FALSE`.  I suppose we could make it scan the flags and print a message about how many data are bad.  But, whether I change the behaviour or not, using `handleFlags=FALSE` will solve this issue.

**Comment by j-harbin** [comment]
Great detective work! I will close this issue and address the `readProfiles(...,handeFlags=FALSE)` in issue #104
