### ISSUE TITLE
revamp plot() bathymetry arg

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#101]
As per vf2f today, I plan to make `bathymetry` be the *single* argument that controls everything about the plotting of a water-depth underlay.  I won't go into the details here, because the effort of describing here it is better spent describing it in the docs.

**Comment by dankelley** [comment]
Commit 380363494314d55ee4d8105c122be0132a89a2fa of the "develop" branch has a new method.  @j-harbin -- this is not quite the same as I had proposed in our vf2f meeting today, since I removed the option of letting `bathymetry` be the output from `marmap::getNOAA.bathy().  It just seemed too complex to have 4 cases, and so now there are 3 cases.  The old 3rd case is just a subset of the new one.

Maybe you can pull and check?

PS. I had to put e.g.
```R
plot(index, bathymetry=FALSE)
```
throughout the examples, to prevent an error that comes up only when I "check" and never when I run code directly.  But that's a separate issue.  All I want to know now is whether this new form of the `bathymetry` argument:
* [ ] has docs that make sense
* [ ] works interactively

**Comment by j-harbin** [comment]
When I do the following code (Example 4 in the help docs for `?`plot,argoFloats-method``)

```R
library(argoFloats)
library(marmaps)
data("index")
plot(index, bathymetry=TRUE)
```

I receive the following error:

```R
Querying NOAA database ...
This may take seconds to minutes, depending on grid size
Error in if (ncol(x) == 3 & !exists("bathy", inherits = FALSE)) { : 
  argument is of length zero
 Error in -min(bathy) : invalid argument to unary operator 
```

Additionally, in terms of the documentation, it all makes great sense to me. The one little hiccup I did notice is when doing ``?`plot,argoFloats-method`` in the Details it says "A list with items controlling both the bathymetry data and its representation in the plot, as in Example 6.", I think it is supposed to say Example 5? I just wanted to double check before changing it.

**Comment by dankelley** [comment]
You're not supposed to work 13 hours per day!

Yes, the doc should say 5, not 6.  I'll change it tomorrow morning.

If you have time tomorrow or next week, we could maybe try debugging this in a vf2f.  (I can teach you hints on finding bugs, which is a pretty good skill.)

I sure hope you didn't read this in the evening.  Take a break!

**Comment by dankelley** [comment]
@j-harbin see https://github.com/ericpante/marmap/issues/10 which seems to indicate that this is a general marmap problem; https://github.com/ericpante/marmap/issues/10#issuecomment-631928645 suggests that the solution may be to update `rgdal` and `raster`. 

I recommend you do
```R
update.packages()
```
prior to any further tests, which should update those packages and others, too.

It may make sense to update all packages about once a week.  It works from CRAN, so the updated versions are well-tested.  Being updated can fix errors, and it also lets you see get features. And you'll update eventually anyway, so you can save time by discovering changes early.

**Comment by j-harbin** [comment]
I had updated my R and needed to install my packages again. For that reason, I did not have `rgdal` and `raster` installed. I can confirm, the plot now works. Maybe we should add it in the documentation that those packages are required?

**Comment by dankelley** [comment]
I'll need to think about this over the weekend.  What I'll do is to remove those packages locally and see what error message I get.  I do not want to talk about this in the documentation.  The better method is for the code to check for existence of those packages, and to issue clear errors if not; you can see how I do that in oce at https://github.com/dankelley/oce/blob/fc6d17e57d544a681b7baa04df2a9f0e6bfc74bd/R/argo.R#L539

**Comment by dankelley** [comment]
I think the way to avoid the
```
Error in if (ncol(x) == 3 & !exists("bathy", inherits = FALSE)) { : 
  argument is of length zero
```
error is for `argoFloats` to require a recent-enough `marmap` version.  Therefore, I altered `DESCRIPTION` to demand a recent marmap, as below
```
Imports: curl, marmap (>= 1.0.4), methods, ncdf4, oce, sf
```
and I think that should be enough to solve much of the problem.

My presumption is that a lot of users will be on R.x.y quite soon, and that they will do
```R
update.packages()
```
of
```R
install.packages()
```
after doing that, as they find that their existing code cannot find packages.  That may prevent the problem of relying on outdated packages.

If users get this error, and ask us, we can say "please see https://github.com/ericpante/marmap/issues/10#issuecomment-631928645", and if they google on that error message, they will quite likely come upon that site, anyhow.

Based on all of this, I am closing the issue.
