### ISSUE TITLE
should readProfiles() have handleFlags=FALSE by default?

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#104]
The present default for the `handleFlags` argument of `readProfiles()` is `TRUE`.  That means that data flagged as bad are set to `NA`.  As shown in #100, this can lead to a surprising number of NA results.  I have looked further into that test, and see that the all-`NA` data are for a particular float, numbered 5901462.  (In that test, there are 22 profiles with that float.)

It would be helpful if @j-harbin could look into the `NA` incidence in more detail, perhaps starting by looking at the float in that example that is in the Pacific.

I am not necessarily in favour of changing the default value of `handleFlags` to `FALSE`, just because we want to get an idea of oxygen for a particular float (which just have a flat-out bad sensor). After all, the decision to use a default of removing "bad" data was taken with some thought and deliberation.  However, we might consider changing `readProfiles()` give a brief message about data quality.

Any thoughts on this, @j-harbin and @richardsc?  Maybe you can both think about it for a while, and put comments here next week.  We could discuss this in a vf2f, to bring @j-harbin up to speed (@richardsc and I have already spent a long time on the general issue of flags, in the `oce` context).

**Comment by dankelley** [comment]
I have made `readProfiles()` in the "develop" branch produce a warning if any profiles have more than half of any data field being flagged as 4 (meaning bad).  Below, you can see the warnings that are issued for the test code in `issues/1xx/104/104a.R`.  (By the way, it's not just `oxygen` that can be problematic.  I had to alter the test file `tests/testthat/test_read.R` because 1 of the 4 profiles being read had more than 50% of it's temperatures being flagged with 4 (meaning "bad").

```R
Warning message:
In readProfiles(profiles) :
  Of 22 profiles read, 22 have >50% of oxygen values with QC flag of 4, signalling bad data.
    These data are set to NA, because the handleFlags argument is TRUE
    The indices of the bad profiles are as follows.
    1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22
```
```R
> argos1 <- readProfiles(profiles, handleFlags=TRUE)
Warning message:
In readProfiles(profiles, handleFlags = TRUE) :
  Of 22 profiles read, 22 have >50% of oxygen values with QC flag of 4, signalling bad data.
    These data are set to NA, because the handleFlags argument is TRUE
    The indices of the bad profiles are as follows.
    1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22
```
```R
> argos2 <- readProfiles(profiles, handleFlags=FALSE)
Warning message:
In readProfiles(profiles, handleFlags = FALSE) :
  Of 22 profiles read, 22 have >50% of oxygen values with QC flag of 4, signalling bad data.
    These data are retained, because the handleFlags argument is FALSE
    The indices of the bad profiles are as follows.
    1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22
```

**Comment by j-harbin** [comment]
After reading your first message in this thread my idea was to keep `handleFlags=TRUE` as the default, as I see great value in filtering "bad" data, and then providing a warning message to let the user know what was going on. I see you were one step ahead of me and have already completed this! I vote a +1 for this update.

**Comment by dankelley** [comment]
Glad to get the vote, because, as @richardsc might complain :-), I often ask for a vote and then do something before anyone responds; undoing a change is quicker than doing a change, and so if the suggestion is likely to be agreed-upon, this lets me schedule time more easily.

Since we have 2 plus votes out of 3 codevelopers, I'll close this issue.  It can always be reopened.
