### ISSUE TITLE
Should axes of maps not have "longitude" and "latitude"

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#105]
As discussed in the vftf with @dankelley , it would be a good idea to have N,S,E, and W indicating direction instead of having "latitude" and "longitude" on map axes

**Comment by dankelley** [comment]
Thanks -- I forgot about that!  Issues are good.

**Comment by j-harbin** [comment]
Complete in @dankelley 's commit #f5fc87e of the develop branch. I am therefore closing this issue.
