### ISSUE TITLE
plot(..., which="map") bathymetry can sometimes have white borders

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#108]
I am not too sure on the conditions that cause this.  It would certainly occur if a plot gets resized, because the way it works is that we do a `plot.window()` to find `par("usr")` and then use the latter to decide on a bathymetry patch to download, and I think resizing only replays graphics calls, not the other code in that embeds those calls.

**Comment by dankelley** [comment]
Here's an example of it happening:

<img width="831" alt="Screen Shot 2020-05-27 at 1 14 32 PM" src="https://user-images.githubusercontent.com/99469/83045512-0dd7db00-a01c-11ea-84bc-67904307db41.png">

**Comment by dankelley** [comment]
One problem is that the `plot.window()` call -- which is made to infer the geographical domain for the bathymetry lookup -- is not taking into account the possibility of a palette being drawn one one side of the plot.

**Comment by dankelley** [comment]
@j-harbin -- could you rebuild "develop" and do some tests on this? I think I have it fixed, but I have not done extensive testing.  My hope is that we can compare notes during our vf2f meeting tomorrow, and close (or update) the issue then.  Thanks!

**Comment by j-harbin** [comment]
I can confirm once cleaning and rebuilding, I no longer receive the white borders.

**Comment by dankelley** [comment]
Thanks team!
