### ISSUE TITLE
Create plot(a, which="diagnostic")

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#109]
As @dankelley suggested, it would be a good idea to have `plot(a, which="diagnostic")`. I am currently working on coding for this, and will keep this issue updated as it evolves.

**Comment by j-harbin** [comment]
This is added under commit #62e6688 of the develop branch with the help of @dankelley in a vtftf. I still need to do the documentation and create plot

**Comment by dankelley** [comment]
Right, and we need a test also, in `tests/testthat/test_subset.R`

**Comment by j-harbin** [comment]
Completed in commit #1d9f2f0ce40da3e987ee51b3c141ad46e579d3df of the develop branch
