### ISSUE TITLE
find a synthetic-type profile dataset with flags for O2 and either S or T

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#117]
@j-harbin, as discussed in our vf2f today, I'd appreciate it if you could identify an bgc-argo profile that has flags for oxygen, along with either S or T.

My hope is to include that file in the data that come with the package.  That way, we can use that file in a `getProfiles()` call, without having to download data ... and that means that we can add more documentation and tests, without the problem of CRAN not wanting packages to download data onto its servers.

With any luck, this will be a float in "our" region.

Thanks!

**Comment by j-harbin** [comment]
In the following code you'll see this particular profile has flags for all oxygen, S, and T.

```R
library(argoFloats)
ais <- getIndex(filename = 'synthetic')
sub <- subset(ais, mode='delayed')
lonRect <- c(-76.5, -76)
latRect <- c(26.5, 27.5)
s <- subset(sub, rectangle=list(longitude=lonRect, latitude=latRect))
profiles <- getProfiles(s)
argos <- readProfiles(profiles)
oxygenFlags <- argos[[1]]@metadata$flags$oxygen
temperatureFlags <- argos[[1]]@metadata$flags$temperature
salinityFlags <- argos[[1]]@metadata$flags$salinity
```

**Comment by dankelley** [comment]
I know I'm being a total pain, but is there a chance you could find one that has some "bad data" flags?  An easy way to see is to do e.g.
```R
summary(argos[[1]])
```
which lists some info on the flags near the end.

**Comment by dankelley** [comment]
PS. here's a code that might help.  I didn't see any bad-data flags there, though ... maybe another search zone?
```R
library(argoFloats)
ais <- getIndex(filename="synthetic", destdir=".")
sub <- subset(ais, mode="delayed")
lonRect <- c(-77, -75)
latRect <- c(25, 28)
s <- subset(sub, rectangle=list(longitude=lonRect, latitude=latRect))
profiles <- getProfiles(s)
argos <- readProfiles(profiles)

n <- profiles[["length"]]
files <- profiles[["file"]]
for (i in seq_len(n)) {
    argo <- argos[[i]]
    cat(rep("-", length.out=30), "\n", sep="")
    cat(files[i], "\n")
    cat(rep("-", length.out=30), "\n", sep="")
    oxygenFlags <- as.vector(argo[["oxygenFlag"]])
    print(table(oxygenFlags))
    salinityFlags <- as.vector(argo[["salinityFlag"]])
    print(table(salinityFlags))
    temperatureFlags <- as.vector(argo[["temperatureFlag"]])
    print(table(temperatureFlags))
}
```

**Comment by j-harbin** [comment]
I am going to move our email conversations to this issue to have a record. My question to @dankelley was in the photo below does this mean, for this particular file, for oxygenFlags, there are 108 # 1 Flags, with 7 # 3 flags, and for salinityFlags there are 994 # 1 Flags and 114 #8 flags etc? The question then was "can flags go up to 8?". My response to this is If you look at the Argo Manual, section 3.2, table 2 (screenshotted here), flags can go up to a value of 9 (screen shotted below).

![Screen Shot 2020-06-03 at 8 52 51 AM](https://user-images.githubusercontent.com/58750538/83635808-38291b80-a57b-11ea-85b1-c4a41ca7220f.png)

![Screen Shot 2020-06-03 at 9 07 34 AM](https://user-images.githubusercontent.com/58750538/83635817-3cedcf80-a57b-11ea-951d-a6b0e1263852.png)

reference
Carval, Thierry, Bob Keeley, Yasushi Takatsuki, Takashi Yoshida, Stephen Loch, Claudia Schmid, Roger Goldsmith et al. "Argo User's Manual, Version 3.2. December 29th 2015.[SUPERSEDED]." (2015).

**Comment by dankelley** [comment]
Thanks for the ref.  I think we'll want to rewrite that table and put it into the argoFloats docs, somewhere.  (We could have a vignette just on flags, actually.  We do that in the oce package.)

**Comment by j-harbin** [comment]
I think that would be useful. I suppose this poses the question is "Interpolated Data" (with a handle flag of 8) considered "bad" data. Would you instead prefer me find a file with a flags # of 4 (ie. bad data)?

**Comment by j-harbin** [comment]
Hi Team,

If you do the following code:

```R
library(argoFloats)
ais <- getIndex(filename = 'synthetic', age=0)
sub <- subset(ais, mode='delayed')
lonRect <- c(54, 70)
latRect <- c(21,23)
s <- subset(sub, rectangle=list(longitude=lonRect, latitude=latRect))
sp <- subset(s, ID=5903586)
profiles <- getProfiles(sp)
argos <- readProfiles(profiles)
n <- profiles[["length"]]
files <- profiles[["file"]]
for (i in seq_len(n)) {
    argo <- argos[[i]]
    cat(rep("-", length.out=30), "\n", sep="")
    cat(files[i], "\n")
    cat(rep("-", length.out=30), "\n", sep="")
    oxygenFlags <- as.vector(argo[["oxygenFlag"]])
    print(table(oxygenFlags))
    salinityFlags <- as.vector(argo[["salinityFlag"]])
    print(table(salinityFlags))
    temperatureFlags <- as.vector(argo[["temperatureFlag"]])
    print(table(temperatureFlags))
}
```

You'll see some options of files with "bad" flags within the Arabian Sea (ie. an Oxygen Minimum Zone)

**Comment by dankelley** [comment]
Thanks.  I did a `summary()` of one to remind myself of the flag scheme, yielding
```R
mapping=list(not_assessed=0,passed_all_tests=1,probably_good=2,probably_bad=3,bad=4,changed=5,averaged=7,interpolated=8,missing=9)
```
so all the oxygens are flagged 3 or 'probably_bad'.

We are definitely getting somewhere with this!

Ideally, we'd find a case with some good and some not-good oxygen data, plus some good and some not-good S or T data, all together in one profile.

I am especially interested in oxygen, so I tried doing `readProfile()` with `handleFlags=FALSE` and then I did
```R
oce::plotProfile(oce::as.ctd(argo), xtype="oxygen")
```
which yields as below.  It would be very interesting to figure out why the QC procedure called this flag=3 or "probably bad" ... in this, I agree with something @j-harbin said in a vf2f yesterday, that it would be great if argo files said which tests failed, yielding the flags that end up in the file.

![image](https://user-images.githubusercontent.com/99469/83760752-c371e200-a64b-11ea-9ed0-9f3eecf69b07.png)

**Comment by dankelley** [comment]
Also, to build on this, 
```R
oce::plot(oce::as.ctd(argo))
```
(which works on the last-read argo object) yields as below.

![image](https://user-images.githubusercontent.com/99469/83761104-3c713980-a64c-11ea-915e-3d1c7b8b8ae7.png)

**Comment by j-harbin** [comment]
Hi Team,

If you go to https://github.com/ArgoCanada/argoFloats/blob/develop/sandbox/jlh/13_SyntheticFlags/syntheticFlags.R , you'll find code that looks at `synthetic` data, subsetted by `realtime` near the Arabian Sea (Oxygen minimum zone). File ~/data/argo/SR2902204_131.nc (screenshot below), in particular, has 'bad' oxygen data, as well as 'probably bad' temperature and salinity data. What do you think @dankelley , is this a winner?

![Screen Shot 2020-06-08 at 2 09 30 PM](https://user-images.githubusercontent.com/58750538/84059892-b299d700-a991-11ea-8f62-75afdc494780.png)

**Comment by dankelley** [comment]
In the immortal words of Don Junior, "I love it!"

**Comment by dankelley** [comment]
I have added this file to the repo.  If you consult
```R
?SR2902204_131.nc
```
you'll see a demonstration of its use.

With this addition, we can start adding code checks on `readProfiles()`; we can discuss this in the next vf2fm.

**Comment by dankelley** [comment]
Done.
