### ISSUE TITLE
should be able to subset() by profile number

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#118]
I tried
```R
library(argoFloats)
i <- getIndex("synthetic")
subset(subset(i, ID="2902199"), profile=144)
```
and it gave
```
Kept 197 profiles (0.106%)
Error: In subset,argoFloats-method() : the only permitted '...' argument is a list named 'circle','rectangle','parameter','polygon', 'time','institution', 'deep', 'ID', 'ocean', or 'mode'
```

The fact that I expected `profile=` to work suggests (in the dog-food context) that we ought to consider adding this `subset()` method.

Do you agree, @j-harbin?  Want to take a shot at implementing it, if so?

**Comment by j-harbin** [comment]
subset by profile added in pull request for issue118, and `testthat()` added in commit ebf5b8ca0453d67bff7cbe43df796d523ea14715 .

**Comment by j-harbin** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done. Thanks!

PS. This is a standardized reply.

**Comment by dankelley** [comment]
Thanks for the reminder!  Yes, your solution is excellent.  Closing now.
