### ISSUE TITLE
proposal: read_profiles() should have handleFlags default of FALSE

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#122]
As noted in #117 and other issues, it seems that oxgyen data are flagged as 4 (bad) or 3 (probably bad) in quite a lot of cases.  That means that `read_profiles(..., handleFlags=TRUE)` will set the values to NA.  

When I set that up as the default argument, I thought it made sense, but now I am starting to think that we ought to use `FALSE` as the argument, letting the user make a decision to remove flagged data later, after examining the flags directly, or after using `plot(..., which="diagnostic")`.

We do not have a large set of users, so I think we have an opportunity to change the default.

What do you think, @j-harbin and @richardsc?

**Comment by j-harbin** [comment]
I agree with this. I think if we do change the default to FALSE, we should maybe give a message to the user reminding them to look at the diagnostics.

**Comment by j-harbin** [comment]
As discussed with @dankelley in a vftf, `handleFlags=FALSE` will be the new default.

**Comment by dankelley** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done. *Thanks!*

PS.  This is a standardized reply.

**Comment by dankelley** [comment]
Oh, jeeze, 4 days ago I asked the reporter to check whether it worked, not realizing that **I** am the reporter.  Closing now, with a red face.
