### ISSUE TITLE
readProfiles() should warn on all non-good flags

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#123]
Note that the code in https://github.com/ArgoCanada/argoFloats/issues/117#issuecomment-638821211 did not produce any info on questionable data, because it only checks for flag value of 4, which means "bad".  I think it should check for all non-good values.  Otherwise, as in that code, `readProfile()` will fill the oxygens with NA just because they are flagged with 3, which means "probably_bad".  (See also #122, though...)

**Comment by j-harbin** [comment]
I agree with this. I think if we do change the default to FALSE, we should maybe give a message to the user reminding them to look at the diagnostics.

**Comment by j-harbin** [comment]
As discussed in the vftf, `readProfiles()` will make a note of flags that are not 1 and 2.

**Comment by j-harbin** [comment]
Hi Team,

When I do 
```R
library(argoFloats)
data('index')
s <- subset(index, 1:3)
profiles <- getProfiles(s)
argos <- readProfiles(profiles)
```
I receive the message:
```R
readProfiles() is setting handleFlags=FALSE, so all data (not just those flagged as 'good') are retained
Warning messages:
1: In readProfiles(profiles) :
  Of 3 profiles read, 2 have >10% of salinity values with QC flag of 4, signalling bad data.
    These data are retained, because the handleFlags argument is FALSE
    The indices of the bad profiles are as follows.
    1 3
2: In readProfiles(profiles) :
  Of 3 profiles read, 2 have >10% of temperature values with QC flag of 4, signalling bad data.
    These data are retained, because the handleFlags argument is FALSE
    The indices of the bad profiles are as follows.
    1 3
```

I therefore believe this issue is solved.

**Comment by dankelley** [comment]
Yes, closing
