### ISSUE TITLE
plot(ai, which='diagnostics') should take into account Flags that are not 1 and 2

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#124]

**Comment by dankelley** [comment]
Um, in our vf2fm today, I was suggesting that @j-harbin take care of this, as the author of `plot(...,which="diagnostic")` and therefore the expert in it, so I switched the assignee from me.

**Comment by j-harbin** [comment]
This has been addressed in commit d8ea6066cb4c1e7155163251a3a3cf542bc07bea of the develop branch, and I am therefore closing this issue.
