### ISSUE TITLE
Make our own message when the index comes from ftp://ftp.ifremer.fr/ifremer/argo

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#125]
When downloading synthetic data, for example, synthetic files are not yet found on the ftp://usgodae.org/pub/outgoing/argo server. We therefore receive a message letting the user know it comes from the ftp://ftp.ifremer.fr/ifremer/argo. We should make a message specific from our package.

**Comment by dankelley** [comment]
Can you copy/paste an example here so I'll know what you mean, exactly.  (I think this is what we discussed in our vf2fm today -- I ought to silence the `curl` output and insert our own message. But I want to be sure I understand.)

**Comment by dankelley** [comment]
I did this last week, but forgot to ask @j-harbin to check if the wording is ok.  So, @j-harbin, if the wording is ok, please close this; otherwise, please suggest edits.

**Comment by j-harbin** [comment]
What commit is this pushed to? I clean and rebuilt and when I do:

```R
library(argoFloats
ai <- getIndex(file='synthetic', age=0)
```
I still receive the error:

```R
Error in curl::curl_download(url = url[iurl], destfile = destfileTemp,  : 
  Given file does not exist
Cannot download the index file from server "ftp://usgodae.org/pub/outgoing/argo", so moving to the next possible server
```

**Comment by dankelley** [comment]
Hm, maybe I didn't do it.  I'll check...

**Comment by dankelley** [comment]
Sorry, I closed it in my commit note.  Now, with "develop" commit b681e85fdcc96b8d7d4f97c951ab05065a2cd0b1, with should get as follows
```R
> library(argoFloats)
> ai <- getIndex(file='synthetic', age=0)
Can't download index from ftp://usgodae.org/pub/outgoing/argo, so moving to next server
Downloaded index from ftp://ftp.ifremer.fr/ifremer/argo
```

**Comment by j-harbin** [comment]
I can confirm I now get this message, and will therefore close this issue.
