### ISSUE TITLE
readProfiles() should have new args: adjusted and FUN

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#126]
As in vftf with D and J

* ~`adjusted` a logical value~ (This was rejected in #146)
* [x] `FUN` a function that defaults to `oce::read.argo()`

**Comment by dankelley** [comment]
My first step is always to write the docs.  I've put snippets below (not pushed to GH yet).  Does the wording make sense, @j-harbin, and does it capture what we discussed at our vf2fm last week?

*Snippet 1 (in Details section)*

<img width="676" alt="Screen Shot 2020-06-08 at 9 29 24 AM" src="https://user-images.githubusercontent.com/99469/84030634-bebe6e00-a96a-11ea-8722-d2f5ae05f813.png">

*Snippet 2 (in Arguments section)*

<img width="677" alt="Screen Shot 2020-06-08 at 9 29 11 AM" src="https://user-images.githubusercontent.com/99469/84030636-bebe6e00-a96a-11ea-9ef4-3b2e442327e9.png">

**Comment by dankelley** [comment]
Hm, this is trickier than I thought, because sometimes the "Adjusted" columns are worthless.

For example, with
```R
library(argoFloats)
data(index)
s <- subset(index, 1:3)
p <- getProfiles(s)
a <- readProfiles(p, adjust=TRUE) # code for this not yet in GH
summary(a[[1]])
```
I get, amongst other things,
```R
* Data Overview

                                          Min.    Mean    Max. Dim. NAs        OriginalName
    latitude [°N]                       27.705  27.705  27.705    1   0            LATITUDE
    longitude [°E]                     -76.231 -76.231 -76.231    1   0           LONGITUDE
    pressureUnadjusted [dbar]                5  323.13    1250 67x1   0                PRES
    pressure [dbar]                         NA      NA      NA 67x1  67       PRES_ADJUSTED
    pressureError [dbar]                    NA      NA      NA 67x1  67 PRES_ADJUSTED_ERROR
    temperatureUnadjusted [°C, ITS-90]   5.177  21.239  28.888 67x1   0                TEMP
    temperature [°C, ITS-90]                NA      NA      NA 67x1  67       TEMP_ADJUSTED
    temperatureError [°C, ITS-90]           NA      NA      NA 67x1  67 TEMP_ADJUSTED_ERROR
    salinityUnadjusted [PSS-78]           35.1  36.434  36.803 67x1   0                PSAL
    salinity [PSS-78]                       NA      NA      NA 67x1  67       PSAL_ADJUSTED
    salinityError [PSS-78]                  NA      NA      NA 67x1  67 PSAL_ADJUSTED_ERROR
```

Thus, in this case, `adjusted=TRUE` will hide our good values.

NOTE: I am actually coding this with a new function that is (presently) called `argoUseAdjusted()`, which works on just one argo profile at a time, and I call that for each profile that gets read in.  I *suppose* I could check to see if the "Adjusted" values are all `NA`, and not do it then, but this would be confusing to the user.

I am not too sure what the best approach is.  Maybe @j-harbin and I could discuss that in our vf2fm tomorrow at 1000h.

**Comment by dankelley** [comment]
Another method might be to drop this idea of an `adjusted` arg to `readProfiles()` and instead institute a new nuance to `[[``, in which
```R
a[["oxygen"]]         # OXY
a[["oxygen", "best"]] # OXY_ADJUSTED, if all are finite, or OXY otherwise
```

**Comment by dankelley** [comment]
@j-harbin perhaps, before our meeting today, you might have time to pull the "126_readProfiles_new_args" branch, build it, and then go to /Users/kelley/git/argoFloats/sandbox/dek and type `make` to run a test that we can talk about in the meeting.

**Comment by dankelley** [comment]
Oh, I added `FUN` quite a while ago and forgot to tick the box.  I'm closing this now.
