### ISSUE TITLE
Make markdown for flags

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#129]
As discussed in the vftf with @dankelley , it would be a good idea to make a markdown explaining how our `argoFloats` package handles flags for Argo data.

**Comment by j-harbin** [comment]
For anybody following this issue, I encourage you to follow https://github.com/ArgoCanada/argoFloats/blob/develop/sandbox/jlh/15_FlagMarkdown/flag.Rmd for the most up to date version of a QC markdown in progress.

**Comment by dankelley** [comment]
Any chance of using the newer Carvel ref (vsn 3.3)?  :-)

**Comment by j-harbin** [comment]
Leaving this note for myself:
I changed all of the examples to have the same float ID number for consistency and now am creating this To-Do list for the QC Markdown:

* [ ] Have user complete the same tasks with a different float ID and potentially a different parameter of interest for exercises
* [ ] Add V3.3 reference
* [ ] Explain Adjusted data section

**Comment by j-harbin** [comment]
Hi Team,

I've completed the items on my to-do list and encourage you to all look at commit 7dcd01396c780f23d9f02e40ce7b1a9caee13104 or https://github.com/ArgoCanada/argoFloats/blob/develop/sandbox/jlh/15_FlagMarkdown/flag.Rmd to look at the QC markdown.

I'd appreciate any feedback you may have.

**Comment by j-harbin** [comment]
As described in issue 162, we decided to include png files instead of a prebuilt vignette. 

Step One: The first step in doing this was to change the "Configure Build Tools" from the first photo to the second photo.

Photo 1
![Screen Shot 2020-07-02 at 5 14 08 PM](https://user-images.githubusercontent.com/58750538/86405954-a64f2400-bc88-11ea-8b77-a7899b8361ea.png)

Photo 2

![Screen Shot 2020-07-02 at 5 14 36 PM](https://user-images.githubusercontent.com/58750538/86405970-aea75f00-bc88-11ea-8775-32d1a789a77f.png)

Step Two : the next step was to fix the YAML in the vignettes from

![Screen Shot 2020-07-02 at 5 26 53 PM](https://user-images.githubusercontent.com/58750538/86406382-63da1700-bc89-11ea-8b50-f5cae294599e.png)

to

![Screen Shot 2020-07-02 at 5 28 22 PM](https://user-images.githubusercontent.com/58750538/86406419-72c0c980-bc89-11ea-903f-5e4c4ea11952.png)

Step 3: In DESCRIPTION remove R.rsp from suggests and VignetteBuilder and put knitr.

Step 4: Deleted the pdf's in the vignette folder to save on space

This is completed in commit 7eaec86be63ca39861147fb32c56960557adb5a1.

I am now working on making pngs of the plots to avoid downloading data.

**Comment by j-harbin** [comment]
Hi Team,

I have added the .png files to the vignette folder to avoid downloading data when we try to submit to CRAN. This is completed in commit 1e7330b4c569e4cfa90bae5b5e093f14219e3969 of the develop branch. One thing I will note (which admittedly, it took me WAY to long to realize), I removed the ^.*.png$ from the .Rbuildignore folder. Without doing that, when I would click "Check" I received the warning: `pandoc document conversion failed with error 99`. There is now no warning.

I encourage you to review both the argoFloats.Rmd and qc.Rmd vignettes in the vignettes folder. Any feedback you may have is greatly appreciated. If both vignettes get a thumbs up I will close this issue :)

**Comment by dankelley** [comment]
We need those particular png files to be part of the git repo.  They are not.  To find what's in the repo, to
```
git ls-files
```

I think our .gitignore is set up to not track .png files.  We want it that way, or else every test .png we make might end up in the repo!  But we need more steps.

You have a file named `qc.R`, which has some stuff we want and other stuff we don't want.  I don't know how it got made, but we don't want it.  Please take the non-commented stuff from that and call it, say, `qc_flowchart.R`.  Then add an appropriate `png()` call at the top and a `dev.off()` at the bottom.  Then run
```
Rscript qc_flowchart.R
```
to create `qc_flowchar.png`.  Then you must put it into the repo with
```
git add -f qc_flow.png
```
(the `-f` over-rides the `.gitignore` setting).

**Comment by j-harbin** [comment]
Hi Dan,

I have just completed that step for all of the code of png files that I need for the vignettes. You can find this at commit 1e735a8e582daa367687b279ce2e478589f41e1d

Unfortunately, when I put  ^.*.png$ back into the .Rbuildignore folder I receive the same error as before.

**Comment by dankelley** [comment]
Right, `.Rbuildignore` should not be discarding that png.  In "develop" commit d3b7219301c42a6d9593835e0c937fb86d2c3e29, I have removed that line.  I also made the two vignettes be slightly more similar (comma in author list, and another tiny tweak).

I feel that this issue can be closed.

**Comment by j-harbin** [comment]
With Dans tweaks and suggestions, I am now closing this issue.
