### ISSUE TITLE
Should be incorporate more than one subset at a time? 

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#130]
Right now, doing the following code:
```R
library(argoFloats)
data('index')
sss <- subset(index, ID='1901584', profile='124')
```
We receive the following error:
```R
Error: in subset,argoFloats-method() : cannot give more than one method in the '...' argument
```

Do we want to incorporate more than one subset at a time, or do we think it's okay for a user to do:

```R
library(argoFloats)
data("index")
s <- subset(index, ID='1901584')
ss <- subset(s, profile='124')
```

**Comment by dankelley** [comment]
Based on `oce` experience, I think we want to do just one at a time.  We can add more, later, but I think it gets confusing.  For example, we might want to allow for
```
subset(index, ID='1901584', a="foo", b="bar")
```
where `a` and `b` are things that mean something in the `ID` context.  (We do not have this, yet.)  But then, if `profile` also has extra args, we will need to parse through all the args and decide what goes with what.  I know this would be confusing to code into the package, and I also think it might be confusing to the user.  I prefer to let the user focus step by step, so they might do
```F
s1 <- subset(index, ID='1901584')
```
and note the number retained, and then do
```R
s2 <- subset(s1, profile=(ETC))
```
and note how many are now retained.

**Comment by j-harbin** [comment]
Ok, good point @dankelley, doing one type of subset at a time is a good way for the user to keep track of their work. I will close this issue.
