### ISSUE TITLE
Test hypothesis do all 'realtime' have all NA values for <PARAM>ADJUSTED

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#132]

**Comment by j-harbin** [comment]
Dan, can you please do the following code and see if you receive the same output (indicating our hypothesis is not correct)?

```R
library(argoFloats)
data(index)
set.seed(1) # First sample
n <- 50
s <- subset(index, sample(seq_along(index[['longitude']]), n))
p <- getProfiles(s)
a <- readProfiles(p, adjusted=TRUE)
cat("Demonstration: adjusted data are not always good!\n")
testOfHypothesis <- NULL
for (argo in a[["profile"]]) {
    isRealtime <- grepl("/[SM]{0,1}R", argo[["filename"]])
    allNA <- all(!is.finite(argo[["temperature"]]))
    hypothesis <- if (isRealtime) allNA else TRUE
    testOfHypothesis <- c(testOfHypothesis, hypothesis)
    if (!hypothesis) {
        cat(argo[["filename"]], "\n", sep="")
        cat("    mean temperature:           ", mean(argo[["temperature"]], na.rm=TRUE), "\n")
        cat("    mean temperatureUnadjusted: ", mean(argo[["temperatureUnadjusted"]], na.rm=TRUE), "\n")
        warning("bad hypothesis on file ", argo[["filename"]], "\n")
    }
}
table(testOfHypothesis)
```
producing:

```R
testOfHypothesis
FALSE  TRUE 
   25    25 
```

The first five of the twenty five `FALSE` tests show:

```R
/Users/jaimiekeeping/data/argo/R4902066_018.nc
    mean temperature:            20.28396 
    mean temperatureUnadjusted:  20.28396 
/Users/jaimiekeeping/data/argo/R4901533_095.nc
    mean temperature:            21.84841 
    mean temperatureUnadjusted:  21.84841 
/Users/jaimiekeeping/data/argo/R4901274_253.nc
    mean temperature:            20.30547 
    mean temperatureUnadjusted:  20.30547 
/Users/jaimiekeeping/data/argo/R4901274_180.nc
    mean temperature:            21.53411 
    mean temperatureUnadjusted:  21.53411 
/Users/jaimiekeeping/data/argo/R4901532_027.nc
    mean temperature:            19.49334 
    mean temperatureUnadjusted:  19.49334 
```

If you look at the Argo Quality Control Manual for Dissolved Oxygen Concentration [1], you'll see that there is REAL-TIME QUALITY CONTROL (pg. 10) (explained a bit in issue #110 ), and maybe this has something to do with it?

Interestingly, for `indexMerged`, `indexBgc`, and `indexSynthetic` all hypothesis tests were `TRUE`. 

[1] Thierry, Virginie, and Henry Bittig. "Argo quality control manual for dissolved oxygen concentration." (2018).

**Comment by dankelley** [comment]
Yes, I get the same.  I now have `sandbox/dk/09_adjust/09_adjust_02.R` to test, and it spits out the summary of the first failed-hypothesis and first passed-hypothesis cases.  I see a pattern there ... possibly easier to describe in a vftfm, if you're free this afternoon or tomorrow morning.

**Comment by j-harbin** [comment]
As an update for the vftf with @dankelley today, we think the answer to our question is within `PARAMETER_DATA_MODE`. As you'll see by the following code:

```R
library(argoFloats)
a <- readProfiles(system.file("extdata", "SD5903586_001.nc", package="argoFloats"))
a1 <- a[[1]]
sort(names(a1@metadata)) # To find PARAMETER_DATA_MODE
a1[['PARAMETER_DATA_MODE']]
```
Produces:

```R
[1] "DDDDARR"
```

and
```R
a1[['PARAMETER']]
```
produces:

```R
[1,] "PRES"   
[2,] "TEMP"   
[3,] "PSAL"   
[4,] "DOXY"   
[5,] "CHLA"   
[6,] "BBP700" 
[7,] "NITRATE"
```
Indicating PRES, TEMP, PSAL, and DOXY are in delayed mode, CHLA is in adjusted mode, and BBP700, and NITRATE are in delayed mode. In other words, an entire profile does not necessarily need to be the same mode, but rather it is parameter specific.

I've screen shotted page 62, section 2.6.5 PARAMETER_DATA_MODE of the Argo Manual [1]. 
![Screen Shot 2020-06-22 at 1 02 50 PM](https://user-images.githubusercontent.com/58750538/85309298-c9a7f100-b488-11ea-88f0-9f4c839b7e4a.png)

Which explains there is both `dataMode` and `PARAMETER_DATA_MODE`. Dan, this explains why we couldn't find `dataMode` today in our vftf. It also explains  the large amount of 'NA' values when we were analyzing <PARAM>_ADJUSTED because as shown in the screen shot, if a parameter has adjusted data, the <PARAM>_ADJUSTED is filled in accordingly, however, if a parameter does not have adjusted data, they are filled in with NA values. 

My thought is to have an argument in argoFloat's `useAdjusted()` function, which uses changes to <PARAM>_ADJUSTED if it exists within the `PARAMETER_DATA_MODE`, and if not we would use whichever mode existed for that particular parameter.

The problem arises when `PARAMETER_DATA_MODE` doesn't exist. What do we do? For example:

```R
library(argoFloats)
data("index")
s <- subset(index, 1)
profiles <- getProfiles(s)
argos <- readProfiles(profiles)
argos1 <- argos[[1]]
sort(names(argos1@metadata))
```
Shows `PARAMETER_DATA_MODE` does not exist, but `dataMode` does. 

What are our thoughts on this?

[1] Carval, Thierry, Bob Keeley, Yasushi Takatsuki, Takashi Yoshida, Stephen Loch Loch, Claudia Schmid, and Roger Goldsmith. Argo User’s Manual V3.3. Ifremer, 2019. https://doi.org/10.13155/29825.

**Comment by dankelley** [comment]
I did
```R
library(argoFloats)
a <- readProfiles(system.file("extdata", "SD5903586_001.nc", package="argoFloats"))[[1]]
```
and then
```R
a[["PARAMETER_DATA_MODE"]]
```
gives
```
[1] "DDDDARR"
```
while
```R
as.vector(a[["PARAMETER"]])
```
gives
```
[1] "PRES"    "TEMP"    "PSAL"    "DOXY"    "CHLA"    "BBP700"  "NITRATE"
```

Looking at
```R
summary(a)
```
I see that (referring to Original Names)
* PRES 
* TEMP
* PSAL
* DOXY
all have adjusted fields (only diff. from original in DOXY case) but that
* BBP700
* NITRATE
do *not* have adjusted fields.  From this, and the docs, I suggest

**HYPOTHESIS.** If PARAMETER_DATA_MODE for a particular variable is either "D" or "A", an Adjusted field will be present, but if it is "R" no such field will be present.

Before we move on to what to do if `PARAMETER_DATA_MODE` is not present, I think we ought to check my "hypothesis" on some more files.  Any chance you could give that a go, @j-harbin?  You can see in the directory `create_data` how I found the file in question ... that will be a reminder for where we are seeing test data that might help us.

**Comment by dankelley** [comment]
@j-harbin in my sandbox, 09_adjust_05.R samples 500 of the approx 1000 profiles in the `indexSynthetic` dataset.  I am *not* sure I am doing all my logic right, and I ask you to set n=5 or so (line 4) and then explore that logic (line 27 and following) to see if I am doing things right.  

Anyway, I get as shown in the screenshot below.  This is perplexing to me.

First, not one case has `[["PARAMETER_DATA_MODE"]]`.  This cannot be a problem in reading the files because we *do* get it for the built-in dataset `SD5903586_001.nc`.  So, maybe that is only defined for some very new floats, and we don't have any in our approximately 1000 `indexSynthetic` floats.  **Q:** Any thoughts on this, @j-harbin?

Now we come to what to do if we do not have `PARAMETER_DATA_MODE`.  We could try going for either letters in the name or `dataMode` in the variables.  These are given in the columns named isRealTime and dataMode.  My visual scan shows that thse match up, which is good because it suggests that our `subset(...,mode=)` will work on type=index files.

But now for the thing that confuses me.  Look at line 563 (case 180).  It and the next cse have some p, S and T values that are *not* `NA` values. But I do not see how we could know that without reading the netcdf.  **Q:** @j-harbin, maybe you could look at case 179 and case 180, to figure out what's up.  (NOTE: this pattern is not isolated, I think ... )

<img width="826" alt="Screen Shot 2020-06-22 at 4 16 03 PM" src="https://user-images.githubusercontent.com/99469/85326620-fc131780-b4a3-11ea-8f56-9b7555b93dbc.png">

**Comment by j-harbin** [comment]
To first touch on your first hypothesis:
" If PARAMETER_DATA_MODE for a particular variable is either "D" or "A", an Adjusted field will be present, but if it is "R" no such field will be present.", if you look at the Argo Manual v3.3 pg. 20 [1], it states:
" Each parameter can be adjusted (in delayed-mode, but also in real-time if appropriate). In that case, <PARAM>_ADJUSTED contains the adjusted values, <PARAM>_ADJUSTED_QC contains the QC flags set by the adjustment process, and <PARAM>_ADJUSTED_ERROR contains the adjustment uncertainties.
When a profile has DATA_MODE = ’R’, no adjusted data are available. Hence the adjusted section (<PARAM>_ADJUSTED, <PARAM>_ADJUSTED_QC and <PARAM>_ADJUSTED_ERROR) should be filled with FillValue."

I am therefore agreeing with your hypothesis.

**Comment by j-harbin** [comment]
Dan, 
I feel in our `?useAdjusted()` we've addressed this hypothesis. What do you think?

**Comment by j-harbin** [comment]
As discussed in the vftf with @dankelley , this issue has been addressed. I am therefore closing this issue.

**Comment by j-harbin** [comment]
After meeting with D and C, we decided to reopen this with the following changes:
1. use `getIndex()` and not `data(index)`
2. Check for `dataMode` and `parameterDataMode` (?)

**Comment by j-harbin** [comment]
I'm going to close this, as we've discussed over Zoom. Also, refer  to the Argo User's Manual, page 22, it explains realtime data can have values that are **not** NA for `<PARAM>_ADJUSTED`
