### ISSUE TITLE
readProfiles() and diagnostics should handle flags 1, 2 ,5, and 8

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#133]
As shown in the screenshot below, the Argo User Manual [1] states (on page 79) that 'good' data are considered to be 1, 2, 5 or 8. Flags 9 (missing) are not used, and all other flags are considered 'bad' data.

![Screen Shot 2020-06-10 at 8 01 00 AM](https://user-images.githubusercontent.com/58750538/84260804-053dd500-aaf1-11ea-824e-aa29462cf8cb.png)

[1] Carval, Thierry, Bob Keeley, Yasushi Takatsuki, Takashi Yoshida, Stephen Loch, Claudia Schmid, Roger Goldsmith et al. "Argo User's Manual, Version 3.2. December 29th 2015.[SUPERSEDED]." (2015).

**Comment by j-harbin** [comment]
As discussed in the vftf to @dankelley today, he will make `argoFloats` specifically catch these flags.

**Comment by dankelley** [comment]
I think this working now, in "develop" commit b0847fc17b0c51596c6d64556034897a89f0aaaf.

A test code is
```R
library(argoFloats)
data(index)
s <- subset(index,1:5)
p <- getProfiles(s)
a <- readProfiles(p)
summary(a[[1]])
```
where you will note near the end of the summary that the oce `flagScheme` has been overridden.  You can see the installed scheme with
```R
str(a[[1]][["flagScheme"]])
```
which should give
```R
List of 3
 $ name   : chr "argo"
 $ mapping:List of 10
  ..$ not_assessed    : num 0
  ..$ passed_all_tests: num 1
  ..$ probably_good   : num 2
  ..$ probably_bad    : num 3
  ..$ bad             : num 4
  ..$ changed         : num 5
  ..$ not_used_6      : num 6
  ..$ not_used_7      : num 7
  ..$ estimated       : num 8
  ..$ missing         : num 9
 $ default: num [1:4] 0 3 4 9
```
and I think this issue can be closed, if you get that.  If you don't get that, please add a comment showing what you get, and leave the issue open.

Thanks.

**Comment by j-harbin** [comment]
I can confirm I also receive this. I will now close this issue.

**Comment by j-harbin** [comment]
Hi Team,

I realized I closed this issue prematurely. I have made diagnostics handle flags 1,2,5 and 8 in commit 2d79f942f84c4de94832ff72e437be8cc477ead7 in the develop branch.
