### ISSUE TITLE
Make qc function to display which qc tests passed, and which failed

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#137]

**Comment by j-harbin** [comment]
Hi Team,

With help/ guidance from Dan, we've created a function `showQCTests()` in commit 11860b7a37cb530d6ba687cf0d9c7c5420af3194 of branch issue137. 

I've been manually practicing changing from hexadecimal to binary numbers, and I can confirm that my answers completed manually match what the `showQCTests()` function is showing.

I am therefore closing this issue.

**Comment by dankelley** [comment]
@j-harbin I reopened this.  Can you please add this to the package?  I don't think it's an immediate concern, but I always find it easier to do this kind of thing when the code is in my head.

To do that, I'd recommend these steps:
1. create a file `R/misc.R` and insert the function (but not the tests)
2. complete the roxygen2 stuff at the top of the function, following the protocol we use for other function (e.g. `getProfileFromUrl()`, perhaps).  It will take a while to understand the syntax for this, but there are good resources online.  It is *very* important to write clearly and succinctly in the docs, for that is all the user will ever have available for learning.
3. In your roxygen2 docs, you should have some `examples`, and that's where you can put some of the code we made already (using one of the two package-supplied netcdf file)
4. create some tests in the test suite (they can be the same as in the Examples part of the docs, but of course you'll want to test the the output with `expect_output()`.

All of this seems quite fiddly, but the result is great for users.

Learning how to document functions usually takes a few days, so please don't think I'm looking for something right away.  Hadley Wickham's book (draft online at https://r-pkgs.org/man.html) is a great resource for learning.

Once this is all done, I will likely port it over into the oce package, as part of `summary,argo-method`.  That way, oce users will also get this new feature.  (PS. I am surprised that the source file for `data(argo)` in oce does not have these HISTORY_ items, but maybe they are a new innovation.)

**Comment by j-harbin** [comment]
This is completed in commit b55e681157e82433e032e191c17cfc0c766da7ef of the develop branch. I am therefore closing this issue.
