### ISSUE TITLE
Error: In plot,argo-method()

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#138]
Hi Team,
When I do the following code:

```R
library(argoFloats)
data('indexSynthetic')
profiles <- getProfiles(indexSynthetic)
a <- readProfiles(profiles)
plot(a[[1]], which='diagnostic', parameter='oxygen')
```
I receive the following error:

```
Error: In plot,argo-method() :
  unrecognized value(s) of which: diagnostic
```

Thoughts?

**Comment by dankelley** [comment]
Can you paste the output if you do
```R
plot(ETC, debug=5)
```
?

**Comment by j-harbin** [comment]
```R
plot(a[[1]], which='diagnostics', parameter='oxygen', debug=5)
```
produces
```R
plot.argo(x, which=c(diagnostics),mgp=c(2.0,0.7,0),mar=c(3.5,3.5,1.5,1.5),cex=1, ...) {
Error: In plot,argo-method() :
  unrecognized value(s) of which: diagnostics
```

**Comment by dankelley** [comment]
I suggest going into the "plot" function and putting a bunch of `message("** 1")` type commands to trace the flow.  When you find out where the error is, go up a bit and insert a `browser()` and then sniff around.

We could z if that helps.

**Comment by j-harbin** [comment]
Sounds good. I just initiated a z

**Comment by j-harbin** [comment]
This was solved in the vftf with Dan. I had a typing error, and it was therefore trying to plot using `oce`. 

The following code works, and I am therefore closing this issue.

```R
library(argoFloats)
data('indexSynthetic')
s <- subset(indexSynthetic, ID='4900845')
profiles <- getProfiles(s)
a <- readProfiles(profiles)
plot(a, which='diagnostic', parameter='oxygen')
```
