### ISSUE TITLE
Video 02 code not working

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#142]
Hi Team,

When I check the video 02 code, in the develop branch, I receive the following error message:

```R
library(argoFloats)
# Get world index
ai <- getIndex()
# Get index withing 50km of Bermuda
ais <- subset(ai, circle=list(longitude=-64.7505, latitude=32.3078, radius=50))
# Get profile data files for this near-Bermuda index
pr <- getProfiles(ais)
# Read those data files
a <- readProfiles(pr)
# Plot a map to the left, and a TS diagram to the right
par(mfrow=c(1, 2))
plot(a, which="map")
```
```R
 Error in xy.coords(x, y) : 
  'list' object cannot be coerced to type 'double' 
```

```R
plot(a, which='TS')
```
creates the following error:
```R
 Error in oce::as.ctd(salinity = salinity, temperature = temperature, pressure = pressure,  : 
  lengths of salinity and longitude must match but they are 69 and 32671, respectively 
```

**Comment by dankelley** [comment]
I know what that is and can fix in 30s but am in a meeting, so later

**Comment by dankelley** [comment]
This is solved in "develop" commit 765276dcceef36a0aac823105434e0bebc6fc1e1.  Check out the issue-test code (in issues/1xx/142) and note that
* I am using the built-in dataset for speed
* I used `handleFlags=TRUE` because otherwise the TS diagram is terrible.  These data are not the best!  To see what i mean, try the code with `handleFlags=FALSE.

**Comment by dankelley** [comment]
If you go do
```
cd argoFloats/issues/1xx/142
make
```
does it work and make a .png file, or does it error?  Because it works fine for me in "develop" commit 35659c2a13ba33cec84386e0701eecd2a01cd8c1, as built in RStudio a couple of minutes ago (build passed, check passed).

**Comment by j-harbin** [comment]
It works! I am therefore closing this issue.

**Comment by dankelley** [comment]
Just to follow up -- does it work now in RStudio also?  (For a while at least, I'm not trusting RStudio at all...)

**Comment by j-harbin** [comment]
Yes, it does work in both RStudio and the terminal.

**Comment by dankelley** [comment]
Ta.
