### ISSUE TITLE
locator() does not work when bathymetry=TRUE

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#143]
When doing the code for video 04 subset by polygon:
```R
library(argoFloats)
ai <- getIndex()
s <- subset(ai, circle=list(longitude=-83, latitude=9, radius=500))
plot(s, which='map') # To get a visual
pa <- locator(type='l')
# Now select your points on the map in the Atlantic
a <- subset(s, polygon=list(longitude=pa$x, latitude=pa$y))
points(a[['longitude']], a[['latitude']], col=2)
pp <- locator(type='l')
# Now select your points on the map in the Pacific
p <- subset(s, polygon=list(longitude=pp$x, latitude=pp$y))
points(p[['longitude']], p[['latitude']], col=3)
```
The `locator()` does not work when `bathymetry=TRUE`. More specifically, it doesn't let me "escape" the locator. If I change it to `bathymetry=FALSE`, it works no problem. I'm wondering if you guys have the same problem, or if it simply my computer.

**Comment by dankelley** [comment]
It lets me escape.  Wanna do a quick Z so I can see what's going on?

**Comment by j-harbin** [comment]
In the vftf with @dankelley we discovered this is an Rstudio issue. To ensure this works for the user, I have changed the code to have `bathymetry=FALSE` in commit 35659c2a13ba33cec84386e0701eecd2a01cd8c1. Dan is going to add a comment in the Youtube link. I am therefore closing this issue.
