### ISSUE TITLE
check plots for colour-blindness issues

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#163]
The site
https://www.color-blindness.com/coblis-color-blindness-simulator/
lets you drag/drop an image into a window, and then you can click buttons to check for different types of colour-blindness.

It would be a good idea to try this out on the plots made by argoFloats.  The question is not whether things look "right", but rather whether things we want to look distinct still look reasonably distinct.  A particular question is whether our float-position colour shows up against bathymetry.

I'm @j-harbin can have a look.  This is a low-priority item -- I just made the issue to save the above website, which I happened upon just now.  A checklist (that I invite @j-harbin to append *within this comment, so we see the percent-done in the pan-issue view*) is given below.
* [x] `plot(..., which="map", bathymetry=FALSE)`
* [x] `plot(..., which="map", bathymetry=TRUE)`
* [x] `plot(..., which="TS")`

**Comment by j-harbin** [comment]
Dan,
This was an excellent website you came across. My overall comment is that bathymetry is not an issue. The Argo float positions easily stand out with the different types of color vision deficiency.

The one area which I did see that could be problematic would have been the distinction between Argo floats and land. When selecting the variations of color vision deficiencies, the land seemed to change the same "hue" as the Argo floats. This would have been problematic, however, the boarders on the Argo float positions solved this issue. I've attached an example of what I mean below.

![Screen Shot 2020-07-02 at 7 31 31 AM](https://user-images.githubusercontent.com/58750538/86348472-16808a00-bc36-11ea-94c8-46a8288a3651.png)

All of this to say I am pleased to report people with color vision deficiencies should not have any problems with the argoFloats package. If you are pleased with this answer, please feel free to close this issue.

**Comment by dankelley** [comment]
Before I close it, can you do me a favour?  It would be great if you could put a brief note about this procedure in the development wiki, so we don't have to go into issues to find out what website to use, etc.

**Comment by j-harbin** [comment]
Great idea! The wiki can be found at https://github.com/ArgoCanada/argoFloats/wiki/How-to-check-plots-for-colour-deficiency

**Comment by dankelley** [comment]
Thanks.  I altered the wiki to list the tests (making it a bit easier to read now, and we may have more plots pretty soon!)  I'm closing this now.  You're fast!
