### ISSUE TITLE
Fix code on Youtube video 02

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#165]
In the code for YouTube video 02, TS plot near Bermuda, we still use `readProfiles(ais, handleFlags=TRUE)`, I have changed the code to not have the `handleFlags` argument, however, I suggest adding the following text to the description of the YouTube video:

At the time of the creation of this video, readProfiles() had a handleFlags argument. We now use applyQC() and the update to the code can be found at https://github.com/ArgoCanada/argoFloats/blob/develop/videos/02/video02.R.

**Comment by dankelley** [comment]
Done, thanks.  Also, I put this one into the playlist.  Unfortunately, I uploaded video3 under a different username and I cannot figure out how to download it to re-upload it with the username under which the others were uploaded.
