### ISSUE TITLE
Q on a citation in QC vignette

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#167]
@j-harbin, maybe you could look at the attached.  The top panel is the vignette, and the bottom is a website.  Are these the same thing?  
* If so, there's a 2020 version, so our citation in the vignette is out of date and should be altered. 
* If not (and in any case, actually) then the citation in our vignette ought to have a DOI or a URL, so people can get it.  As it is, readers will be forced to do google searches to try to find this document.

Also, the first citation confuses me.  Does the "2(5) p.32" refer to something within the document?  If so, that information ought to be in in the citation, not in the reference list. The ideas is to write e.g "the sky is blue (Smith and Jones, appendix 3)" in one spot of the text and "water is wet (Smith and Jones, Appendix 4)" at another, with just on item in the ref list, which tells us where to get the S-J document, not where to look within it.

<img width="927" alt="Screen Shot 2020-07-03 at 3 47 00 PM" src="https://user-images.githubusercontent.com/99469/86492587-fab7d980-bd44-11ea-9228-15c59a0d4ff4.png">

**Comment by j-harbin** [comment]
Dan, 

Thank you for catching this. The updated (2009 to 2020) version actually impacted the information that was in the vignette as well. This has been fixed in commit 3489ed44cb76fc400ccf0394ee51d96543c01b5c . If you feel this is adequate feel free to close this issue.

**Comment by dankelley** [comment]
Um, it got formatted a bit wrong (note indentation in the snapshot).
<img width="714" alt="Screen Shot 2020-07-03 at 7 52 22 PM" src="https://user-images.githubusercontent.com/99469/86500348-c228f780-bd66-11ea-81ff-bd980fa71131.png">

**Comment by j-harbin** [comment]
Fixed in commit dc8206b9f83897b4db38eb45ee2789495298db12 of the develop branch.

**Comment by j-harbin** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done. Thanks!

PS. This is a standardized reply.

**Comment by dankelley** [comment]
Um, I am getting the following now (again) on "develop" commit 0f65050286ad2261b683bc365dd2802ff4f77575.  I thought that problem was fixed, so I may be mixed up.

```
==> devtools::document(roclets = c('rd', 'collate', 'namespace', 'vignette'))

Updating argoFloats documentation
Loading argoFloats
Writing NAMESPACE
Writing NAMESPACE
Updating vignettes
Rebuilding qc.Rmd
Error in tools::buildVignette(vign, dirname(vign), tangle = FALSE, clean = FALSE) : 
  Vignette 'qc' is non-ASCII but has no declared encoding
Calls: suppressPackageStartupMessages ... roclet_output.roclet_vignette -> vign_update_all -> map_lgl -> .f -> <Anonymous>
Execution halted

Exited with status 1.
```

**Comment by dankelley** [comment]
Below is how to find the problem.  Maybe you can add this to the wiki, @j-harbin ?
```
$ Rscript -e 'tools::showNonASCIIfile("vignettes/qc.Rmd[0/193]
260: 1.Wong, Annie, Robert Keeley, Thierry Carval, and Argo Data Management Team. <e2><80><9c>Argo Quality Control Manual for CTD and Trajectory Data,<e2><80><9d> January 1, 2020. https://archimer.ifremer.fr/doc/00228/33951/.
```

**Comment by j-harbin** [comment]
Done!

**Comment by j-harbin** [comment]
As discussed in the vftf with @dankelley , this issue is now solved and I am therefore closing this issue. An explanation of how to solve this can be found in the wiki at https://github.com/ArgoCanada/argoFloats/wiki/How-to-fix-non-ASCII-error-when-building-vignettes .
