### ISSUE TITLE
Get more than one vignette to show up on user website

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#168]

**Comment by dankelley** [comment]
@j-harbin I see the QC one shows up, in the Articles tab, so I think you ought to close this issue.

<img width="918" alt="Screen Shot 2020-07-14 at 10 55 26 AM" src="https://user-images.githubusercontent.com/99469/87434324-b3d9a780-c5c0-11ea-9b8a-60321b15c47b.png">
