### ISSUE TITLE
Create code for useAdjusted()

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#169]
As discussed in the vftf with @dankelley , the `useAdjusted()` function solely has the documentation completed. We are now going to add the coding to get the function to work.

**Comment by dankelley** [comment]
Let's start by deciding (and recording here) a netcdf file will work for coding and then for documenting and testing.  Maybe it's one we already have in the `data` directory ... if not, maybe we should find a good one and put it there.

**Comment by j-harbin** [comment]
I recommend using SD5903586_050.nc. That is the netcdf that we sent to Tanya, and as she kindly pointed out there was a 16% difference in adjusted vs unadjusted data for oxygen.

**Comment by j-harbin** [comment]
This has been completed with the creation of `preferAdjusted()` in `oce`. R code for `useAdjusted()``in `argoFloats` can be found at https://github.com/ArgoCanada/argoFloats/blob/develop/R/misc.R. It should be noted that the user will now need to use a version (>= 1.3.0) of oce.

I am therefore closing this issue.

**Comment by dankelley** [comment]
Hi @j-harbin, I'm reopening this, because the docs are not quite right.  They still refer to the old way.  I can take a shot at writing about the new way, if you want, but I think you were planning on doing that, and might have closed this issue by mistake.

**Comment by j-harbin** [comment]
This was discussed in a vftf with @dankelley and has been completed in commit b43935d46487fe8a45888f17bb8a8678be28dfc3 of the develop branch.
