### ISSUE TITLE
PROPOSAL: subset() by polygon should not warn if polygon needs completion

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#170]
Presently we get the warning, as below.  This will occur routinely, for polygons developed by mouse clicks using `locator()`, and that means that the message will come up a *lot*, possibly making users think they did something wrong.  But any sensible user will also draw the polygon, to check on it, so I think this message is not helpful.

@j-harbin, if you agree, can you comment-out the test and the warning?  Otherwise, you can give a "no" vote, and then another co-developer can be called upon to break the tie.

DK vote: +1 for silencing the message.

```R
In subset,argoFloats-method(): Closing the polygon, since the first and last points did not match.
```

**Comment by j-harbin** [comment]
I agree with this change and I have completed it in commit c0942ed82ffb955c86a1b12af924e187994026bf of the develop branch. The warning was commented-out, documentation fixed, and testthat adjusted. If you feel this is adequate, please feel free to close this issue.

**Comment by dankelley** [comment]
This looks great, thanks!
