### ISSUE TITLE
png files not showing up in vignettes on user's website

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#172]
If you go to our user website https://argocanada.github.io/argoFloats/index.html , you'll notice that the png files are not showing up in the vignettes. I suspect this has to do with pkgdown not detecting the png files that are being imported into the vignettes. I plan to look into this, but in the meantime, @richardsc have you run into this before?

**Comment by j-harbin** [comment]
Hi Team,

I've been using this great issue found at https://github.com/r-lib/pkgdown/issues/172 . It seems the problem is that the file paths in the html generated by `pkgdown::build_site()` are absolute. The suggestion to avoid this problem was to put the contents for the vignette in the docs/article folder. Am I correct in thinking, however, that the only way to check this is if it is pushed to master? I was under the impression that using ```pkgdown::build_site()``` built the website from the master branch. This work is currently in a branch named issue172.

**Comment by dankelley** [comment]
I always do `Rscript -e "pkgdown::build_site()"` from the "master" branch.  I can try that.  We could ms/teams if you want to try with more eyes on the prize.

**Comment by j-harbin** [comment]
Sure! It shouldn't take long. I am available when you are, so feel free to initiate.

**Comment by j-harbin** [comment]
This issue has been solved in a vftf with @dankelley. When adding the png to the docs/articles directory, it was necessary to type ```git add -f nameofpng.png``` in a terminal to force the adding of png. I am now closing this issue.
