### ISSUE TITLE
 Error in -min(bathy) : invalid argument to unary operator 

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#173]
When doing the following code, I receive the following error:

```R
library(argoFloats)
ai <- getIndex()
from <- as.POSIXct("2020-07-01 00:00:00", tz="UTC")
to <- as.POSIXct("2020-07-02 00:00:00", tz="UTC")
subset <- subset(ai, time=list(from=from, to=to))
plot(subset)
```
```R
Error in marmap::getNOAA.bathy(round(usr[1] - Dlon, 3), round(usr[2] +  : 
  Latitudes should have values between -90 and +90
 Error in -min(bathy) : invalid argument to unary operator 
```

When I set the bathymetry to FALSE, I don't have any problems. Thoughts? (No rush on this).

**Comment by dankelley** [comment]
I suggest you look into it ... in R, when you get the error, use
```R
traceback()
```
to see where the error happened.  Then, if RStudio allows it, insert a
```R
browser()
```
before that line, and look at the variables. Most likely you'll see that lat is under -90 or over +90.  Just use e.g.
```
latTrimmed <- max(min(c(lat, 90)), 90)
```
or something to trim it.  (Play around a bit.)

I think RStudio may crash on a `browser()`, though (it does for me, most of the time)) so just put a line that prints the lat, and rebuild, to check.  Then twiddle the code like above.

**Comment by dankelley** [comment]
We could Z if you want to discuss this and maybe another bug I'm going to report in a moment.

**Comment by j-harbin** [comment]
Yes, I have a few things to ask you about as well. I am available whenever so feel free to initiate.

**Comment by j-harbin** [comment]
This was solved with the help of dan in commit 98db0f4bb3cf7e091d5451b41c1a3e20c05efbfd of the develop branch. I am therefore closing this issue.

**Comment by j-harbin** [comment]
Reopening this issue because when I do the following code:
```R
library(argoFloats)
data(index)
plot(index)
```
I receive:

```R
Error in marmap::getNOAA.bathy(max(-180, round(usr[1] - Dlon, 3)), min(+180,  : 
  The resolution must be equal to or greater than 1
 Error in -min(bathy) : invalid argument to unary operator 
```

**Comment by dankelley** [comment]
Hm, it works for me, as below.

<img width="1206" alt="Screen Shot 2020-09-01 at 3 40 54 PM" src="https://user-images.githubusercontent.com/99469/91892737-909ab280-ec69-11ea-8ac0-d5d472cf8537.png">

**Comment by j-harbin** [comment]
As found at https://stackoverflow.com/questions/18350353/error-in-external-graphics-r it was recommend to do

```R
dev.off()
```

All is good now!
