### ISSUE TITLE
Uneven characters in hexadecimal Tests Performed vs Tests Failed

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#179]
Hi @cgrdn ,

When using the example that we use in https://github.com/ArgoCanada/argoFloats/issues/176 , @dankelley and I came across something that we weren't quite sure about. With commit 7c01ce703d844afd9180b74e411793b826c0b5ff of the develop branch, when we do:

```R
library(argoFloats)
library(oce)
index1 <- subset(getIndex(), profile="188")
index2 <- subset(index1, ID='3900407')
profiles <- getProfiles(index2)
argos <- readProfiles(profiles)
argos[[1]][['historyQCTest']]
```
We receive 

```R
  [,1]    [,2]   [,3] [,4] [,5] [,6] [,7]
[1,] "FFBFE" "4000" ""   ""   ""   ""   ""  
```

My question is, how can we have 5 characters for "Tests Performed" (ie. 5*4 bits=20), but only 4 characters for "Tests Failed) ie (4*4 bits = 16). 

This is evident when doing

```R
showQCTests(argos[[1]])
```

We receive

```R
Tests performed: 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1
Tests failed:    0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0
```
Where in "Test failed" a `0` indicates it did not fail this test, but it only goes as high as Test 15, we would think it would go as high as 19 like in Tests performed.

**Comment by dankelley** [comment]
I was thinking about this during my run, and realized that the notation is likely that if there is a leading 0, that it is not reported.  This is because leading hex digits give *trailing* binary digits in this reverse-of-math notation.  You can see that in:
```R
> argoFloats::hexToBits("4000")
 [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0
> argoFloats::hexToBits("04000")
 [1] 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
```

@cgrdn -- is my hypothesis correct?  If so, then it means that @j-harbin and I have a clear path to our next step, which is to report tests done and tests failed by both number *and* summary phrase.

**Comment by cgrdn** [comment]
Yes I think your right - the way I was thinking about it was that in terms of representing the tests in base 10, Argo doesn't seem to report above what is necessary for the tests failed. So by nature of the system, all the lower tests are "included", but tests > 14 in this case aren't included. 

I would assume any tests not within the combined QCP and QCF rows were just not performed. So with QCP = FFBFE and QCF = 4000, test 10 and tests > 19 weren't performed at all?

**Comment by dankelley** [comment]
I was guessing that P=FFBFE and F=4000 meant that those higher tests *were* performed, but they passed.  In other words, I was guessing that the code that wrote the netcdf files simplified 04000 to 4000, much as we might simple 012 to 12 in decimal ... that is, the code would stop listing digits "to the left" if they were zero.

So, my guess is that we should trust the P value in telling us what tests are performed, but that we should extend the F value (adding insignificant zeros to the left of the left-most non-zero hex digit) as necessary.

But, frankly, this is just guess-work.  @j-harbin and I decided that if you were not sure (and given that we are not sure!) that @j-harbin would reach out to someone more official next week.  (There are some names in some docs or websites, I think.)

To be honest, I'm a bit surprised by the sloppiness of the official Argo documentation.  But, c'est la vie.

**Comment by cgrdn** [comment]
Agreed I'm just taking guesses at this point as well. The one example they give in the manual (1BE? at least in the version I was originally using) leaves a lot to be desired I agree.

**Comment by dankelley** [comment]
Although I look forward to hearing we hear from MEDS colleagues, I am becoming more convinced that we ought to interpret short QCTEST strings by adding an extra `0` hex digit at the left.

This is because I've been looking at Matlab code store at github.com/gabrielapilo/ArgoRealTimeSource.git, which seems to be part of an official CSIRO system used for Australian floats.

At [line 1027 of argoprofile_desc_ncWindows.md](https://github.com/gabrielapilo/ArgoRealTimeSource/blob/483b6dd241761790fcae6aba98bc95c70521cac4/argoprofile_desc_ncWindows.m#L1027) we see the following matlab code

```matlab
jj = find(fp.testsperformed);
        qp = dec2hex(sum(power(2,jj)));
        netcdf.putVar(ncid,NHISQCTID,[0,ii-1,4],[length(qp),1,1],qp);
        jj = find(fp.testsfailed);
        qf = dec2hex(sum(power(2,jj)));
        netcdf.putVar(ncid,NHISQCTID,[0,ii-1,5],[length(qf),1,1],qf);
```
so the problem reduces to finding out how matlab `dec2hex` works.  The following tests illustrate how these work.
```matlab
>> hex2dec('4000')

ans =

       16384

>> hex2dec('04000')

ans =

       16384

>> dec2hex(16384)

ans =

    '4000'
```

**Comment by dankelley** [comment]
I have coded explicit prepending of zeros (so the method is very clear) in commit 78618de4fed3b798880997abfa1c5e219dc2d0a6 of "develop".

Now, using
```R
library(argoFloats)
library(oce)
index1 <- subset(getIndex(), profile="188")
index2 <- subset(index1, ID='3900407')
profiles <- getProfiles(index2)
argos <- readProfiles(profiles)
showQCTests(argos[[1]])
```
yields
```
Tests performed: 2 3 4 5 6 7 8 9 10 12 13 14 15 16 17 18 19 20
    Failed test 14 (Density Inversion test)
```
and
```R
showQCTests(argos[[1]],"full")
```
yields
```
Test |  Status | Description
-----|---------|--------------------------------------------------------------
   1 | Skipped | Platform Identification test
   2 |  Passed | Impossible Date test
   3 |  Passed | Impossible Location test
   4 |  Passed | Position on Land test
   5 |  Passed | Impossible Speed test
   6 |  Passed | Global Range test
   7 |  Passed | Regional Global Parameter test
   8 |  Passed | Pressure Increasing test
   9 |  Passed | Spike test
  10 |  Passed | Top and Bottom Spike test (obsolete)
  11 | Skipped | Gradient test
  12 |  Passed | Digit Rollover test
  13 |  Passed | Stuck Value test
  14 |  FAILED | Density Inversion test
  15 |  Passed | Grey List test
  16 |  Passed | Gross Salinity or Temperature Sensor Drift test
  17 |  Passed | Visual QC test
  18 |  Passed | Frozen profile test
  19 |  Passed | Deepest pressure test
  20 |  Passed | Questionable Argos position test
  21 | Skipped | Near-surface unpumped CTD salinity test
  22 | Skipped | Near-surface mixed air/water test
  23 | Skipped | Interim rtqc flag scheme for data deeper than 2000 dbar
  24 | Skipped | Interim rtqc flag scheme for data from experimental sensors
  25 | Skipped | MEDD test
-----|---------|--------------------------------------------------------------
```

**Comment by j-harbin** [comment]
I just want to reiterate that I *love* this option of `showQCTests(..,full)`. I think it's very insightful for the user. One thing I will note, is if you look at page 14 of the Argo Quality Control Manual for CTD and Trajectory Data [1], the Density Inversion Test is as follows:

![Screen Shot 2020-07-27 at 8 05 12 AM](https://user-images.githubusercontent.com/58750538/88535276-057e2b00-cfe0-11ea-9638-693240f3f538.png)

This is problematic because if you do the following code:
```R
library(argoFloats)
library(oce)
index1 <- subset(getIndex(), profile="188")
index2 <- subset(index1, ID='3900407')
profiles <- getProfiles(index2)
argos <- readProfiles(profiles)
argos[[1]][['flags']]$temperature
```
We get the following output, that demonstrates that *no* temperature values were flagged as 4, indicating to me that the test was not failed.

```R
   [,1]
 [1,]    1
 [2,]    1
 [3,]    1
 [4,]    1
 [5,]    1
 [6,]    1
 [7,]    1
 [8,]    1
 [9,]    1
[10,]    1
[11,]    1
[12,]    1
[13,]    1
[14,]    1
[15,]    1
[16,]    1
[17,]    1
[18,]    1
[19,]    1
[20,]    1
[21,]    1
[22,]    1
[23,]    1
[24,]    1
[25,]    1
[26,]    1
[27,]    1
[28,]    1
[29,]    1
[30,]    1
[31,]    1
[32,]    1
[33,]    1
[34,]    1
[35,]    1
[36,]    1
[37,]    1
[38,]    1
[39,]    1
[40,]    1
[41,]    1
[42,]    1
[43,]    1
[44,]    1
[45,]    1
[46,]    1
[47,]    1
[48,]    1
[49,]    1
[50,]    1
[51,]    1
[52,]    1
[53,]    1
[54,]    1
[55,]    1
[56,]    1
[57,]    1
[58,]    1
[59,]    1
[60,]    1
[61,]    1
[62,]    1
[63,]    1
[64,]    1
[65,]    1
[66,]    1
[67,]    1
[68,]    1
[69,]    1
[70,]    1
[71,]    1
[72,]    1
```
Thoughts?

[1] Wong, Annie, Robert Keeley, Thierry Carval, and Argo Data Management Team. “Argo Quality Control Manual for CTD and Trajectory Data,” January 1, 2020. https://archimer.ifremer.fr/doc/00228/33951/.

**Comment by dankelley** [comment]
Closing, as per vf2f JH/DK today.
