### ISSUE TITLE
What do letters mean at the end of file names

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#181]
When doing the following code:
```R
library(argoFloats)
ai <- getIndex()
deep <- subset(ai, deep=TRUE)
deep[['file']][[2]]
```
We receive:
```R
"aoml/4902321/profiles/R4902321_001D.nc"
```

I will be looking into what the `D` means after the profile number.

**Comment by j-harbin** [comment]
Using this link http://www.argodatamgt.org/content/download/20705/143045/file/ConclusionOnStoringBioObservation.pdf , I determined that the <D> at the end of the file name indicates depending profile. I am therefore closing this issue.

**Comment by dankelley** [comment]
Great find!  This link ought to go in the references for `getIndex()`, I think.  Maybe in the main vignette also.
