### ISSUE TITLE
showQCTests() should provide test titles

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#182]
`?showQCTests` lists the tests by number and description, but as discussed in a vf2f meeting with @j-harbin earlier today, most users are unlikely to remember the numbers.  We decided that `showQCTests` ought to display the descriptions.  After playing around with that, I decided that it produced results that were too verbose (requiring a user to scroll the screen to see them all), so I dropped that idea.  However, if we only listed the failed test descriptions, things should be shorter.  So, doing that might make sense.

**Comment by dankelley** [comment]
This is done in "develop" commit 3aa03829c5ad91169d82a88e74f758f4a3f87f8c (and a commit or two before that).  So, the example in `?showQCTests`
```R
library(argoFloats)
a <- readProfiles(system.file("extdata", "D4900785_048.nc", package="argoFloats"))
showQCTests(a[[1]])
```
now yields
```
Tests performed: 2 3 4 5 6 7 8 9 10 12 13 14 15 16 17 18 19 20 22 23 24 25
    Passed all tests
```
and the example from a recent issue
```R
library(argoFloats)
library(oce)
index1 <- subset(getIndex(), profile="188")
index2 <- subset(index1, ID='3900407')
profiles <- getProfiles(index2)
argos <- readProfiles(profiles)
showQCTests(argos[[1]])
```
now yields
```
Tests performed: 2 3 4 5 6 7 8 9 10 12 13 14 15 16 17 18 19 20 22 23 24 25
    Failed test 14 (Density Inversion test)
```

**Comment by dankelley** [comment]
I like this behaviour of showing details just of the failed tests, rather than burning up maybe 20 lines (half a terminal window height) on names of the tests that were performed.

But I want the opinion of @j-harbin ... if you agree that what I have coded looks good, please close this issue.  If not, please suggest a change. Thanks!

**Comment by dankelley** [comment]
Hm.  Actually, I'm wondering whether I have the numbers wrong.  It says that test 10 was performed in these two test cases.  But I thought it was obsolete so why would it be listed?  And neither of these has test 1.  So that might make me think I'm listing 1+test_number instead of test_number.

@j-harbin maybe you can check on this sometime on Monday, using our `hexToBits()` and going through reasoning like we were using this morning?

**Comment by dankelley** [comment]
I've added a new "style" argument to `showQCTests()` so now
```R
library(argoFloats)
a <- readProfiles(system.file("extdata", "D4900785_048.nc", package="argoFloats"))
showQCTests(a[[1]], "full")
```
yields
```
Test | Status | Description
-----|--------|--------------------------------------------------------------
   1 |     OK | Platform Identification test
   2 |     OK | Impossible Date test
   3 |     OK | Impossible Location test
   4 |     OK | Position on Land test
   5 |     OK | Impossible Speed test
   6 |     OK | Global Range test
   7 |     OK | Regional Global Parameter test
   8 |     OK | Pressure Increasing test
   9 |     OK | Spike test
  10 |     OK | Top and Bottom Spike test (obsolete)
  11 |     OK | Gradient test
  12 |     OK | Digit Rollover test
  13 |     OK | Stuck Value test
  14 |     OK | Density Inversion test
  15 |     OK | Grey List test
  16 |     OK | Gross Salinity or Temperature Sensor Drift test
  17 |     OK | Visual QC test
  18 |     OK | Frozen profile test
  19 |     OK | Deepest pressure test
  20 |     OK | Questionable Argos position test
  21 |     OK | Near-surface unpumped CTD salinity test
  22 |     OK | Near-surface mixed air/water test
  23 |     OK | Interim rtqc flag scheme for data deeper than 2000 dbar
  24 |     OK | Interim rtqc flag scheme for data from experimental sensors
  25 |     OK | MEDD test
-----|--------|--------------------------------------------------------------
```
and
```R
library(argoFloats)
library(oce)
index1 <- subset(getIndex(), profile="188")
index2 <- subset(index1, ID='3900407')
profiles <- getProfiles(index2)
argos <- readProfiles(profiles)
showQCTests(argos[[1]], "full")
```
yields
```
Test | Status | Description
-----|--------|--------------------------------------------------------------
   1 |     OK | Platform Identification test
   2 |     OK | Impossible Date test
   3 |     OK | Impossible Location test
   4 |     OK | Position on Land test
   5 |     OK | Impossible Speed test
   6 |     OK | Global Range test
   7 |     OK | Regional Global Parameter test
   8 |     OK | Pressure Increasing test
   9 |     OK | Spike test
  10 |     OK | Top and Bottom Spike test (obsolete)
  11 |     OK | Gradient test
  12 |     OK | Digit Rollover test
  13 |     OK | Stuck Value test
  14 |   FAIL | Density Inversion test
  15 |     OK | Grey List test
  16 |     OK | Gross Salinity or Temperature Sensor Drift test
  17 |     OK | Visual QC test
  18 |     OK | Frozen profile test
  19 |     OK | Deepest pressure test
  20 |     OK | Questionable Argos position test
  21 |     OK | Near-surface unpumped CTD salinity test
  22 |     OK | Near-surface mixed air/water test
  23 |     OK | Interim rtqc flag scheme for data deeper than 2000 dbar
  24 |     OK | Interim rtqc flag scheme for data from experimental sensors
  25 |     OK | MEDD test
-----|--------|--------------------------------------------------------------
```

So, this can save a `?showQCTests` step.  Note that the output is a markdown table, so if a person wanted, they could cut/paste this into a summary document.

**Comment by dankelley** [comment]
Oh, hang on... this new "full" needs to list "skipped" in the second column, if the test was not performed...

**Comment by dankelley** [comment]
I've altered to indicate skipped tests.  Now,
```R
library(argoFloats)
a <- readProfiles(system.file("extdata", "D4900785_048.nc", package="argoFloats"))
showQCTests(a[[1]], "full")
```
yields
```
est |  Status | Description
-----|---------|--------------------------------------------------------------
   1 | Skipped | Platform Identification test
   2 |  Passed | Impossible Date test
   3 |  Passed | Impossible Location test
   4 |  Passed | Position on Land test
   5 |  Passed | Impossible Speed test
   6 |  Passed | Global Range test
   7 |  Passed | Regional Global Parameter test
   8 |  Passed | Pressure Increasing test
   9 |  Passed | Spike test
  10 |  Passed | Top and Bottom Spike test (obsolete)
  11 | Skipped | Gradient test
  12 |  Passed | Digit Rollover test
  13 |  Passed | Stuck Value test
  14 |  Passed | Density Inversion test
  15 |  Passed | Grey List test
  16 |  Passed | Gross Salinity or Temperature Sensor Drift test
  17 |  Passed | Visual QC test
  18 |  Passed | Frozen profile test
  19 |  Passed | Deepest pressure test
  20 |  Passed | Questionable Argos position test
  21 | Skipped | Near-surface unpumped CTD salinity test
  22 | Skipped | Near-surface mixed air/water test
  23 | Skipped | Interim rtqc flag scheme for data deeper than 2000 dbar
  24 | Skipped | Interim rtqc flag scheme for data from experimental sensors
  25 | Skipped | MEDD test
-----|---------|--------------------------------------------------------------
```
and
```R
library(argoFloats)
library(oce)
index1 <- subset(getIndex(), profile="188")
index2 <- subset(index1, ID='3900407')
profiles <- getProfiles(index2)
argos <- readProfiles(profiles)
showQCTests(argos[[1]], "full")
```
yields
```
est |  Status | Description
-----|---------|--------------------------------------------------------------
   1 | Skipped | Platform Identification test
   2 |  Passed | Impossible Date test
   3 |  Passed | Impossible Location test
   4 |  Passed | Position on Land test
   5 |  Passed | Impossible Speed test
   6 |  Passed | Global Range test
   7 |  Passed | Regional Global Parameter test
   8 |  Passed | Pressure Increasing test
   9 |  Passed | Spike test
  10 |  Passed | Top and Bottom Spike test (obsolete)
  11 | Skipped | Gradient test
  12 |  Passed | Digit Rollover test
  13 |  Passed | Stuck Value test
  14 |  FAILED | Density Inversion test
  15 |  Passed | Grey List test
  16 |  Passed | Gross Salinity or Temperature Sensor Drift test
  17 |  Passed | Visual QC test
  18 |  Passed | Frozen profile test
  19 |  Passed | Deepest pressure test
  20 |  Passed | Questionable Argos position test
  21 | Skipped | Near-surface unpumped CTD salinity test
  22 | Skipped | Near-surface mixed air/water test
  23 | Skipped | Interim rtqc flag scheme for data deeper than 2000 dbar
  24 | Skipped | Interim rtqc flag scheme for data from experimental sensors
  25 | Skipped | MEDD test
-----|---------|--------------------------------------------------------------
```

But it remains to know what to think of cases where the number of hex digits in the "performed" item does not match that in the "failed" item ... see #179.

**Comment by j-harbin** [comment]
Dan,

I *love* this idea of having the user have the option to provide a `full` argument. I stand strongly for always letting the user know what is going on (ie. provide detail such as which tests were performed), however, I don't like the idea of too many lines as an output. This seems like a great way around that where it at least gives the user the option to see the full detail if they like. I am going to continue to look into this problem of QCP$ vs QCF$ hex digits today.

**Comment by dankelley** [comment]
Note that the "full" output is a bit wrong. It calls the early tests "skipped" when the bit is zero, but it's also saying "skipped" for those tests at the end, where we are only guessing, because there is no hex digit there to tell us the actual result.

I looked into some resources on the weekend, but my *very* quick skimming did not uncover anything giving an example of decoding.  Even so, the following links might be worth examining:

* [SOCCOM-BCGArgo processing website](https://github.com/SOCCOM-BGCArgo/ARGO_PROCESSING)
* [argoFloats development website](https://github.com/ArgoCanada/argoFloats)
* [UCSD argo software website](https://argo.ucsd.edu/data/argo-software-tools)
* [argo-floats gitter chat](https://gitter.im/Argo-floats?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
* [euro argo dev forum](https://github.com/euroargodev/publicQCforum/issues)

**Comment by richardsc** [comment]
If those resources don’t turn up anything useful, another option is to ask Anh at MEDS to see if she knows the decoding magic. She is on Github but probably email would be better.

**Comment by dankelley** [comment]
This MEDS connection might be useful, because my detective work on the weekend seems to suggest that a lot of the bad data (NA for lon, lat or date) have `meds` for the DAC.

**Comment by j-harbin** [comment]
This is great, I will reach out to Anh.

**Comment by j-harbin** [comment]
I believe this issue has been addressed. I am still checking `showQCTests()` on numerous profiles after the changes you made (ie. adding the leading 0's), however, I do not think that stops us from closing this issue. If you think this has been addressed @dankelley , feel free to close this issue.

**Comment by dankelley** [comment]
Yup!
