### ISSUE TITLE
PROPOSAL: Change subset(..., profile='x') to subset(..., cycle='x')

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#183]
This idea came about from looking at the following code:
```R
library(argoFloats)
deep <- subset(getIndex(), deep=TRUE)
subset <- subset(deep, ID='4902321')
subset2 <- subset(subset, profile='001D')
gp <- getProfiles(subset2)
rp <- readProfiles(gp)
sort(names(rp[[1]][['metadata']]))
rp[[1]][['cycleNumber']]
```
You'll see `cycleNumber` exists, and it therefore may be a good idea to change `profile` to `cycle` for consistency. Thoughts?

**Comment by dankelley** [comment]
Let's sort this out in our 1000h vm.

**Comment by j-harbin** [comment]
This was completed in commit fa5ed01e8c0914e7f0d3ccc588abaf6c3aa63974 of the branch issue183 and was merged into the develop branch. I am therefore closing this issue.

**Comment by dankelley** [comment]
I am reopening this as a notice to @j-harbin that I will recode how `[[` works, so please don't edit `R/AllClass.R` until I close this again.

**Comment by dankelley** [comment]
Actually, @j-harbin, I got distracted and did not recode `[[` yesterday.  If you like, we could try another ms/teams to check out screen-sharing, and do that recoding together.  Four eyes (6, if you count my glasses) can help in such global search/replace work.

**Comment by j-harbin** [comment]
That sounds great. I am available whenever you are, feel free to initiate.

**Comment by j-harbin** [comment]
This has been completed during a vftf with @dankelley in commit 97947021dfc0c4a6f319fd02041d5442cc9018eb of the develop branch. I am therefore closing this issue.

**Comment by dankelley** [comment]
FYI, "develop" commit 9629822009a9a7baeecdd823ca91f951ca6525c0 now auto-converts "profile" to "cycle", giving an informative message that this will cease "after" 2020-sep-01.  That way, we can leave it in place later, if we want to.  @j-harbin if you dislike this behaviour, let me know and I an undo it.

**Comment by dankelley** [comment]
This session illustrates the msg:
```R
> library(argoFloats)
> data("index")
> p<-index[["profile"]]
Warning message:
In index[["profile"]] :
  converted x[["profile"]] to x[["cycle"]] for backwards compatibility;
  NOTE: this conversion will cease after 2020-Sep-01.
> str(p)
 chr [1:953] "124" "125" "126" "128" "129" "132" "147" "148" ...
> ps <- subset(index, profile="001")
Kept 6 profiles (0.63%)
Warning message:
In subset,argoFloats-method : converted subset(x,profile=...) to subset(x,cycle=...) for backwards compatibility
  NOTE: this conversion will cease after 2020-Sep-01. 
> ps
argoFloats object of type "index" with 6 items
```
