### ISSUE TITLE
For descending profile it is necessary to put D when specifying profile #

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#184]
When doing the following code : 

```R
library(argoFloats)
deep <- subset(getIndex(), deep=TRUE)
subset <- subset(deep, ID='4902321')
subset2 <- subset(subset, profile='001')
```
We receive

```R
Kept 0 profiles (0%)
Warning message:
In subset,argoFloats-method(..., parameter) : found no profiles with given profile
```

However, doing
```R
subset2 <- subset(subset, profile='001D')
```
We receive

```R
Kept 1 profiles (1.1%)
```

If it is agreed we should not have to specific `D` when giving the profile argument, I will assign this to myself and change it.

**Comment by dankelley** [comment]
I suppose we could make `profile='001'` detect both `001` and `001D`.  It's just a matter of adding `D{0,1}` to the regexp.

**Comment by j-harbin** [comment]
This has been completed by @dankelley in a vftf in commit 97947021dfc0c4a6f319fd02041d5442cc9018eb of the develop branch. I am therefore closing this issue.
