### ISSUE TITLE
Provide exact time for speech videos of YouTube videos

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#187]
I will be providing Dan with the exact time in Youtube Videos to insert speech videos to fix the change of `profile` argument to `cycle`.

**Comment by j-harbin** [comment]
Hi @dankelley, 

I have fixed the sample code for the YouTube videos. More specifically, I have fixed video 06 and 07 to use the word `cycle` instead of `profile`. The following is a table that demonstrates the video URL, time a speech bubble is needed, and what should go in the speech bubble. As I reminder, I encourage you to look at https://blog.promolta.com/add-annotations-youtube-enhance-engagement/ for a video on how to make the speech bubble.

Video URL | min:sec | Speech Bubble
https://www.youtube.com/watch?v=7BB3UuwjUqo&feature=youtu.be | 3:18 | cycle <- index[['cycle']]
https://www.youtube.com/watch?v=7BB3UuwjUqo&feature=youtu.be | 6:46 | index0[['cycle']]
https://www.youtube.com/watch?v=7BB3UuwjUqo&feature=youtu.be | 7:04 | o <- order(index[['cycle']]
https://www.youtube.com/watch?v=7BB3UuwjUqo&feature=youtu.be | 9:19 | cycle <- index0[['cycle']][o]
https://www.youtube.com/watch?v=7BB3UuwjUqo&feature=youtu.be | 13:39 | text(lon[sub], lat[sub], cycle[sub], cex=2/3, pos=1)
https://youtu.be/Lc32MTMCbbI | 6:02 | cycle <- index0[['cycle']]
https://youtu.be/Lc32MTMCbbI | 11:02 | text(lon[sub], lat[sub], cycle[sub], cex=2/3, pos=1)

**Comment by dankelley** [comment]
Hm. I tried following the directions at  https://blog.promolta.com/add-annotations-youtube-enhance-engagement/ but the interface seems to have changed.  I clicked lots of things and did not see a way to add annotations.

**Comment by j-harbin** [comment]
Another idea could be to make a note in the description of the video, with the min:sec and Speech bubble part of the table included?

**Comment by dankelley** [comment]
Yes, I think the description idea is our best plan.  I'll have a go.  The good thing is that I can write a general sentence, like perhaps

> CHANGE: argoFloats now refers to "cycle" rather than "profile", e.g. subset(a,profile=1:3) would become subset(a,cycle=1:3) an a[["profile"]] would become a[["cycle"]].

**Comment by j-harbin** [comment]
Exactly, and maybe draw attention to the updated sample code at https://github.com/ArgoCanada/argoFloats/blob/develop/videos/06/video06_trajectory_by_time.R for video 06 and https://github.com/ArgoCanada/argoFloats/blob/develop/videos/07/video07_map_with_bathymetry.R for video 07

**Comment by dankelley** [comment]
I've updated the video descriptions.  I think I will also add in code so that if the user tries
```R
a[["profile"]]
```
or
```R
subset(a, profile=1:10)
```
they will get an error telling them that they have to change their code.  This way, nobody will get into trouble.  I will put a time-out on that error, stating that we will stop checking at 2020 Sep 1 or something.

**Comment by j-harbin** [comment]
That's a great idea. I have checked out the descriptions of both of the videos and I give a +1. I believe this issue is solved, so I am therefore closing this issue.
