### ISSUE TITLE
Create .png for useAdjusted() docs

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#189]
As discussed in a vftf with @dankelley, to help users understand the complex ideas behind the `useAdjusted()` function within `argoFloats`, I thought a flow chart may be useful. Dan, this is kind of what I had in mind, but as always, I am open to feedback.

![useAdjusted()](https://user-images.githubusercontent.com/58750538/88396887-8a2b3800-cd99-11ea-9aee-7ff07866a607.jpg)

**Comment by dankelley** [comment]
Looks nice.  Similar wording should be used in the three bottom boxes -- all should refer to `[[`.

I think the diagrammer package (http://rich-iannone.github.io/DiagrammeR/index.html) might be useful...at any rate, the video is worth watching, even though the music is a bit distracting.

The advantage of having it in code is that then we can edit things easily.

**Comment by dankelley** [comment]
Also, the diagram should let people know about the `which` arg.

**Comment by j-harbin** [comment]
Hi Team,

I encourage you to look at https://github.com/ArgoCanada/argoFloats/blob/develop/sandbox/jlh/23_useAdjustedDiagram/diagram.R to see a rough draft of the useAdjusted() diagram. That was a great suggestion on the DiagrammeR package, Dan, it was very easy to follow.

![Screen Shot 2020-07-24 at 1 04 11 PM](https://user-images.githubusercontent.com/58750538/88411644-adacad80-cdae-11ea-8e96-9a2f3c762ec7.png)


A few things to note:

1) I know @dankelley wanted something about the `which` arg, so I was thinking maybe put it in the Figure caption (ie. Figure 1: The steps taken during the useAdjusted(which=ALL) process)

2) Ideally, I would want the "Is there an adjusted data field" > "No" > "[[ returns <param> values" to be lined up with the other bottom blocks, so I am currently in the process of determining how to extend the arrows.

**Comment by dankelley** [comment]
First, **wow**, this looks fantastic!

The diagram might be further improved if it said what `fallback` does.  That's just another if branch.  I agree, the `which` part is pretty long to put in a box, but the docs in `useAdjusted` has some reasonably clear sentences that could likely be trimmed for a caption that's only a line long.

PS. I added a `Makefile` to the dir, and added in a `png()` line, but this graphing system seems not to use conventional graph output.  @j-harbin how did you make that png with this R file?

@richardsc the plan @j-harbin and I have is to put this diagram into the docs returned by `?oce::preferAdjusted` but we could also use it in argoFloats the `?useAdjusted` doc if the file is not big.

**Comment by j-harbin** [comment]
Hi @dankelley , the photo I added to this issue was simply a screenshot, however, I do see that you added the lines to create a png within my sandbox - thanks for that! I've updated the diagram based on your feedback, and it is shown below. One thing I do still want to do is line up the "Yes" and "No" 's.

![Screen Shot 2020-07-27 at 7 47 08 AM](https://user-images.githubusercontent.com/58750538/88534054-aa4b3900-cfdd-11ea-9bf9-2a437dc436d5.png)

**Comment by j-harbin** [comment]
Sorry, I should have added, the code for this can be found at https://github.com/ArgoCanada/argoFloats/blob/develop/sandbox/jlh/23_useAdjustedDiagram/diagramNew.R

**Comment by dankelley** [comment]
The lines I added don't actually work.  The only thing that worked for me was to manually save the png in rstudio (which made a crazily huge PNG) and then scale that png down to a more reasonable size in macos "preview".

Anyway, as for the "yes" an "no", the normal way is to label a line (see time 2:31 in the video at https://rich-iannone.github.io/DiagrammeR/)

**Comment by j-harbin** [comment]
Dan, thanks for the feedback about the "label" idea. It has made the diagram a lot more condense. DiagrammeR is a great package, and I'm having quite a lot of fun exploring it. Below is the new `useAdjusted()` diagram. I was thinking for a figure caption (and to incorporate the `which` argument) we could say something like:

Figure 1 : Flow chat for useAdjusted() function within argoFloats package when which argument is equal to ALL or <param>. The default settings are displayed in red. 

![Screen Shot 2020-07-27 at 10 41 47 AM](https://user-images.githubusercontent.com/58750538/88548680-ce1a7900-cff5-11ea-9609-22b1c2e86ba8.png)

Note: if we are putting this diagram within preferredAdjusted in oce, the figure caption would clearly adjusted accordingly.

Code for this diagram can be found at
https://github.com/ArgoCanada/argoFloats/blob/develop/sandbox/jlh/23_useAdjustedDiagram/03_diagram.R

Thoughts?

**Comment by dankelley** [comment]
I don't think red means default, as drawn.  It's not the default that all parameter are NA.  The default is that `fallback` is `TRUE`.  I propose dropping the colour.

**Comment by j-harbin** [comment]
I took your advice and removed the colour. In addition, I added the .png to the package (only at 49 KB!) and I've updated the docs to include this diagram in `useAdjusted()` in commit eef7ee44323e9156223dca4d379e19b1251a4f8b  of the develop branch. If I get the "OK" and you are happy with how the docs look, I can close this issue. In addition, I can also add this to the `preferredAdjusted()` in `oce` if that is something you'd be interested in.

**Comment by dankelley** [comment]
Please dd the new png to git with `git add -f man/figures/FILE.png`

**Comment by j-harbin** [comment]
when I do
```R
git add -f man/figures/useAdjusted.png
```
I receive 
```R
fatal: pathspec 'man/figures/useAdjustedDiagram.png' did not match any files
```

however, when I do `ls` within the figures folder, there is a useAdjustedDiagram.png

**Comment by dankelley** [comment]
Yes. What is happening is that The file access locally but it is not part of the repo. You have to do get ad space Dash F in order to add it to the repo. Repository. Sorry for typos, during this by dictation on Phone because computer keyboard has really failed now
