### ISSUE TITLE
Is useAdjusted() working properly?

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#191]
As example in Case 4 of issue 190 (https://github.com/ArgoCanada/argoFloats/issues/190), doing the following code:
```R
delayed <- subset(getIndex(), mode='delayed')
index1 <- subset(delayed, circle=list(longitude=-60.8518, latitude=46.2487, radius=350))
profiles <- getProfiles(index1)
argos <- readProfiles(profiles)
summary(argos[['salinity']][[63]])
```
We receive:
```R
Min.   : 2.133  
 1st Qu.:34.562  
 Median :34.868  
 Mean   :34.030  
 3rd Qu.:34.919  
 Max.   :34.954  
```
By doing
```R
unlist(argos[['salinity']][[63]])
```
We see that position 38 has a salinity value of 2.133, which when doing
```R
unlist(argos[['flags']][[63]][['salinity']])
```
We see that the 38th position is flagged as 4 (ie. bad data).

I therefore did:

```R
adj <- useAdjusted(argos)
summary(unlist(adj[[63]][['salinity']]))
```
And I receive
```R
       V1        
 Min.   : 2.133  
 1st Qu.:34.562  
 Median :34.868  
 Mean   :34.030  
 3rd Qu.:34.919  
 Max.   :34.954 
```
Which is the same as when I do 

```R
summary(unlist(argos[[63]][['salinity']]))
```
Indicating it did not get rid of the bad data.

**Comment by dankelley** [comment]
I don’t think adjusted necessarily means following the flags. Try using the hand of legs function.

**Comment by j-harbin** [comment]
Ah yes! One of these I will remember that these two things are different.

As a follow up when I do:
```R
QC <- applyQC(argos)
summary(unlist(QC[[63]][['salinity']]))
```
I receive 
```R
     V1       
 Min.   :32.01  
 1st Qu.:34.66  
 Median :34.88  
 Mean   :34.49  
 3rd Qu.:34.92  
 Max.   :34.95  
 NA's   :1  
```
Which did indeed get rid of the bad data. I am therefore closing this issue.
