### ISSUE TITLE
[[ "ID" vs "id" return values differ

### ISSUE THREAD

**Issue by richardsc** [ArgoCanada/argoFloats#192]
This is kind of a minor point, but I keep getting confused between whether to use "ID" or "id". Note that `subset,argoFloats-method` uses `"ID"`, but the way it is stored in the actual `argo` object is with `id`.

I also notice that `[['ID']]` vs `[['id']]` behaves differently for an `argoFloats` object of type `argos`, e.g.

```r
library(argoFloats)
library(magrittr)

data(index)
d <- index %>%
    subset(circle=list(longitude=-76.87, latitude=27.10, radius=10)) %>%
    getProfiles() %>%
    readProfiles()
d[['ID']]
```
```
[1] "4900437" "4901274" "4901274" "4902066" "4902066"
```
```r
d[['id']]
```
```
[[1]]
[1] "4900437"

[[2]]
[1] "4901274"

[[3]]
[1] "4901274"

[[4]]
[1] "4902066"

[[5]]
[1] "4902066"
```

**Comment by dankelley** [comment]
I recall having a plan, once, to either change the case or to make both return the same.  Let me take a look (tomorrow ... I am still setting up this computer)

**Comment by dankelley** [comment]
The relevant code is given below.  As you can see, we are doing special interpretation of some things (like `"ID"`), in which we return a **vector**, not a **list**.  But the question is whether we ought to return *everything* as a vector or as a list.

I am not 100% sure whether I think it's best to give a vector as the result, or a list.

Maybe we, all three, ought to sleep on this and vote tomorrow by noon?  Then a final recoding can be done by 1300h tomorrow.

What do @j-harbin and @richardsc think?

```R
              if (type == "index") {
                  if (is.numeric(i)) {
                      return(x@data$index[i,])
                  } else if (length(i) == 1 && i == "index") {
                      return(x@data$index)
                  ##??} else if (length(i) == 1 && is.numeric(i)) {
                  ##??    return(x@data$index[i,])
                  } else if (length(i) == 1 && i %in% names(x@metadata)) {
                      return(x@metadata[[i]])
                  } else if (length(i) == 1 && i %in% names(x@data$index)) {
                      return(if (missing(j)) x@data$index[[i]] else x@data$index[[i]][j])
                  } else if (length(i) == 1 && i == "profile") {
                      warning("converted x[[\"profile\"]] to x[[\"cycle\"]] for backwards compatibility;\n  NOTE: this conversion will cease after 2020-Sep-01.")
                      cycle <- gsub("^[a-z]*/[0-9]*/profiles/[A-Z]*[0-9]*_([0-9]{3,4}[D]{0,1}).nc$", "\\1", x@data$index$file)
                      return(as.vector(if (missing(j)) cycle else cycle[j]))
                  } else if (length(i) == 1 && i == "cycle") {
                      cycle <- gsub("^[a-z]*/[0-9]*/profiles/[A-Z]*[0-9]*_([0-9]{3,4}[D]{0,1}).nc$", "\\1", x@data$index$file)
                      return(as.vector(if (missing(j)) cycle else cycle[j]))
                  } else if (length(i) == 1 && i == "ID") {
                      ID <- gsub("^[a-z]*/([0-9]*)/profiles/[A-Z]*[0-9]*_[0-9]{3}[A-Z]*.nc$", "\\1", x@data$index$file)
                      return(as.vector(if (missing(j)) ID else ID[j]))
                  } else if (length(i) == 1 && i == "length") {
                      return(length(x@data$index$file))
                  } else {
                      stop("cannot interpret i=", paste(i, collapse=","), " for an object of type=\"index\"")
                  }
```

**Comment by j-harbin** [comment]
As of now, for all object types, `index`, `profiles`, and `argos`, [['id']] returns a character vector of the id numbers. This has been completed in commit b292cce7b8816e1ae47dc9f4c7fa689a88208f9d of the develop branch. @richardsc , if you are pleased with this, feel free to close this issue.

**Comment by richardsc** [comment]
I'll rebuild and have a look! Thanks :)

**Comment by j-harbin** [comment]
Closing on the assumption that it works, @richardsc please reopen if you want to.
