### ISSUE TITLE
Should we refer to ID or id

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#194]
As discussed in a vftf with @dankelley, we should decide if we are going to refer to ID or id. I vote that we use id throughout all of the code and documentation, however, if the user uses ID we can prepare a warning that ID will be allowed until September 01, 2020 (much like we did for changing profile to cycle).

Let's all vote, and we will make a final decision at 1300h tomorrow. Thanks Team!

**Comment by dankelley** [comment]
I vote +1 on @j-harbin's suggestion: `"id"` is the official name, and that goes in all documentation; `"ID"` is accepted as a synonym, but that will give a warning until Sep 1, and after Sep 1 it will stop working.

**Comment by richardsc** [comment]
+1 from me.

**Comment by dankelley** [comment]
Closing, after discussion in vm.

**Comment by j-harbin** [comment]
Done in commit da5d31549c9878e86049deb6716e3f44caf2788c of the develop branch.
