### ISSUE TITLE
Update Youtube Video Documentation for ID to id

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#197]
In commit 5512737bd8db4f59bfa6a000ae40200f99c78be2 of the develop branch, `ID` has been changed to `id` throughout the package. The code for YouTube videos is also updated, however, I was wondering if @dankelley could update Video 06 at https://www.youtube.com/watch?v=7BB3UuwjUqo&feature=youtu.be and Video 07 at https://youtu.be/Lc32MTMCbbI documentation to state " argoFloats now refers to "id" rather than "ID", e.g. subset(a,ID='124') would become subset(a,id='124') and a[["ID"]] would become a[["id"]]."

**Comment by dankelley** [comment]
Thanks. Both video descriptions are now updated.
