### ISSUE TITLE
PROPOSAL: Change the description of ?showQCTests

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#201]
Right now the current help for `showQCTests` is as follows:

showQCTests print a summary of the quality-control (QC) tests (if any) that were performed on an argo profile. It uses hexToBits() to decode the hexadecimal values that may be stored in historyQCTest and historyAction within the metadata slot of an individual argo profile, as read directly with oce::read.argo() or indirectly with readProfiles(), the latter being illustrated in the “Examples” section below. The “Details” section provides an explanation of how showQCTests works at a low level, as an adjunct to the Argo documentation.

I propose changing it to:

showQCTests prints a summary of the QC tests (if any) that were performed on an Argo cycle. It uses hexToBits() to decode the hexadecimal values that may be stored in historyQCTest. From there it pairs the determined test values with the appropriate action, QC Tests performed or QC Tests failed, found in historyAction within the metadata slot of an individual Argo profile, as read directly with oce::read.argo() or
indirectly with readProfiles(), the latter being illustrated in the “Examples” section below. The “Details” section provides an explanation of how showQCTests works at a low level, as an adjunct to the Argo documentation.

**Comment by dankelley** [comment]
I suggest you go ahead and make the changes, as you see fit.  You're on top of this :-)

**Comment by j-harbin** [comment]
This has been completed in commit 0ee822f66e21667f32366256821d5288708794f2 of the develop branch.
