### ISSUE TITLE
[["id"]] should work for type='profiles'

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#203]
It would be helpful for `[["id"]]` to work for all 3 `type`s of argoFloats object.

Once we have that done, we can document all three in the overall-properties portion of in the docs for `[[,argoFloats-method`.  Trimming the specific-to-`type` portions will improve readabilty of the docs.

**Comment by j-harbin** [comment]
This has been completed in commit b292cce7b8816e1ae47dc9f4c7fa689a88208f9d of the develop branch. I am therefore closing this issue.
