### ISSUE TITLE
Decide on the word `cycle` and `profile`

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#208]
As discussed in a vftf with @dankelley, I will be looking into weather what is produced every ten days is referred to as a `cycle` or `profile`. In addition, when each (now referred to as) `cycle` has two columns, would that be 2 profiles within a cycle?

**Comment by j-harbin** [comment]
I encourage everyone to look at Section 1.6 Argo Float Cycles of the Argo User's Manual [1]. In brief, it states the following:

"A typical Argo float drifts for four years or more in the ocean. It continuously performs measurement cycles. A cycle is defined as a series of actions made by a float and includes either a descending profile or an ascending profile (or, rarely, both); it may also include immersion drift or surface drift."

This makes me think that @dankelley is correct when he said he believes that when a `cycle` has 2 columns, the columns are called `profiles`. In this case, it may be okay to keep `getProfiles`, and `readProfiles` instead of changing to `getCycles` and `readCycles` because if there is a `cycle` with 2 columns (ie. profiles) it will "get" and "read" both columns.

Thoughts?

[1] Carval, Thierry, Bob Keeley, Yasushi Takatsuki, Takashi Yoshida, Stephen Loch Loch, Claudia Schmid, and Roger Goldsmith. Argo User’s Manual V3.3. Ifremer, 2019. https://doi.org/10.13155/29825.

**Comment by richardsc** [comment]
I agree with the proposal to keep the `profile` terminology. In my mind, and based on the documentation, `cycle` refers to all the actions performed by a float over 10 days, not just the collection of data while the float is moving (profiling) vertically.

It's not usually contained in the final netCDF files, but the original raw data from many floats contains more data (both scientific AND engineering) that are collection during the various phases of a cycle, e.g. during the 9 day drift and while the float is descending.

**Comment by dankelley** [comment]
So, this gets us into the conversation that J and I had yesterday: `getProfiles()` and `readProfiles()` are therefore confusing names.

I could do a ms/teams meeting at 0900h if J and C want, but I have another meeting at 1000h.

**Comment by j-harbin** [comment]
I'm available!

**Comment by j-harbin** [comment]
Great meeting, Team!

For completeness, the final decision was to keep the function names `getProfiles` and `readProfiles`.
