### ISSUE TITLE
subset should have a column argument

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#209]
As discussed in the meeting with @dankelley and @richardsc , we will be incorporating a subset by column ability.

**Comment by j-harbin** [comment]
NOTE: This will be a subset for `argos` type only.

**Comment by j-harbin** [comment]
This has been completed in commit b341acda722100805bc1d437baf3ae3b52295652 of the develop branch with the help of Dan. I am therefore closing this issue.

**Comment by dankelley** [comment]
See e.g. https://github.com/dankelley/oce/blob/8071f2ba29d2cbac830dd807424460b07129b897/R/argo.R#L613 in the oce package for a way to sift through both `metadata` and `data`.

**Comment by dankelley** [comment]
Closing, according to consensus in vf2fm
