### ISSUE TITLE
Example 1 in ?`subset,argoFloats-method` does not work

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#213]
Hi Team,

As you can see from my issues, I am going down rabbit holes with our subset function. I did notice, however, when I do:

Example 1: subset to the first 3 profiles in the (built-in) index
```R
library(argoFloats)
data(index)
index1 <- subset(index, 1:3)
```
I receive:

```R
 Error in .local(x, ...) : 
  must specify the subset, with 'subset' argument,'circle','rectangle', 'parameter','polygon', 'time', 'institution', 'deep', 'id', 'ocean', 'mode', 'cycle', 'direction', or 'column' 
```

**Comment by dankelley** [comment]
We can do a ms/t if you'd find it helpful.

**Comment by j-harbin** [comment]
This now works, I am therefore closing this issue.
