### ISSUE TITLE
PROPOSAL: Video 10

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#220]
Hi Team,

I propose to make a 10th, and final (for now) video for `useAdjusted()` on Thursday. The video could be as follows:

1. Explanation about adjusted data and how that differs from qc flag data
2. Use the following code to demonstrate an example of `useAdjusted()`
```R
library(argoFloats)
index1 <- subset(getIndex(filename='synthetic'), id='5903586')
index2 <- subset(index1, cycle='001')
profiles <- getProfiles(index2)
raw <- readProfiles(profiles)
adjusted <- useAdjusted(raw)
rawOxygen <- unlist(raw[['oxygen']])
rawPressure <- unlist(raw[['pressure']])
adjustedOxygen <- unlist(adjusted[['oxygen']])
adjustedPressure <- unlist(adjusted[['pressure']])
xlim <- range(c(rawOxygen, adjustedOxygen), na.rm=TRUE)
plot(rawOxygen, rawPressure,
     pch=1, col=1,
     xlim=xlim, ylim=rev(range(rawPressure, na.rm=TRUE)),
     xlab=expression("Raw Oxygen ["*mu*mol/kg*"]"),
     ylab='Pressure (dbar)')
points(adjustedOxygen, adjustedPressure,
       pch=3, col=2)
legend("bottomright", pch=c(1,3), col=c(1,2), c("Raw", "Adjusted"))
```

![Screen Shot 2020-08-28 at 11 35 32 AM](https://user-images.githubusercontent.com/58750538/91579851-9b301180-e922-11ea-8c2e-57fe9c39a384.png)

**Comment by dankelley** [comment]
Good idea.  I added your name as an assignee ... hoping we can do a joint video, like the others :-)

**Comment by j-harbin** [comment]
This has been completed and can be found at https://youtu.be/AuauWeUnopc
