### ISSUE TITLE
checking for future file timestamps ... NOTE

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#223]
When "checking" the package, I receive the following:

![Screen Shot 2020-08-31 at 1 41 33 PM](https://user-images.githubusercontent.com/58750538/91744365-c703ff00-eb8f-11ea-802e-a1b571caa67e.png)

It should be noted that at https://stackoverflow.com/questions/63613301/r-cmd-check-note-unable-to-verify-current-time it seems that people are having this problem the last few days. I will be looking into this, but just wanted record of it.

**Comment by dankelley** [comment]
All packages have been getting that for several days.  I think the machine that provides time-stamps is down.  We are in the same boat as all other packages, so this issue ought to be closed.
