### ISSUE TITLE
VOTE: add app to this repo

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#226]
@j-harbin and @richardsc are asked to vote below...

In a separate (teaching) project, I've been working on an app that shows a map of argo float positions.  I propose to port that into this package, because I think it would be of benefit to quite a few people.  Let's have a vote, with -1 meaning do not include that app in this package, +1 meaning to include it, and numbers in between meaning as usual for this kind of voting.  I will decide based on the sum of votes provided by noon tomorrow.

* **DK vote: +1**
* **JH vote: +1**

**Comment by dankelley** [comment]
PS this is a snapshot of the app, focussing on a single float.  Is the path funky and aphysical? Sure.  But it's got my initials in it, so it's all good 🥰 

<img width="1022" alt="Screen Shot 2020-09-02 at 1 58 13 PM" src="https://user-images.githubusercontent.com/99469/92013626-6e199f80-ed24-11ea-90e9-8cd4f4120d8a.png">

**Comment by j-harbin** [comment]
+1 for adding this app. We have been working with the app for only a few days and have already had a few "break throughs" and learned a lot. I definitely don't see a downfall to adding it.

**Comment by dankelley** [comment]
Voting is now closed.  Thanks.  I will add it, and am closing the issue since it (as defined by the title) has been addressed.
