### ISSUE TITLE
Is this QC plot plotting correctly?

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#228]
Hi Team,
Looking for your thoughts/ feedback on what is happening in this QC plot?

The following code:
```R
library(argoFloats)
index1 <- subset(getIndex(), circle=list(longitude=-83, latitude=9, radius=150))
ppx <- c(-84.50618, -83.41864, -81.82846, -81.60913, -83.19931, -84.60671, -84.61585)
ppy <- c(9.643841, 8.939756, 7.919735, 7.621853, 7.630880, 7.657960, 9.445253)
index2 <- subset(index1, polygon=list(longitude=ppx, latitude=ppy))
index3 <- subset(index2, id='3900407')
profiles <- getProfiles(index3)
argos <- readProfiles(profiles)
plot(argos, which="QC", parameter='temperature')
```
![Screen Shot 2020-09-03 at 12 15 09 PM](https://user-images.githubusercontent.com/58750538/92134028-6c60e200-eddf-11ea-920a-e72072617ce3.png)

**Comment by dankelley** [comment]
The times are not in order.  We could just order them, but there might be other problems.  I can look tomorrow.

**Comment by dankelley** [comment]
If I add
```R
time <- oce::numberAsPOSIXct(unlist(argos[["time"]]))
o <- order(time)
data.frame(order=o, time=time, cycle=argos[["cycle"]], id=argos[["id"]])
```
at the end of your code, I get as follows.
```
   order                time cycle      id
1     11 2011-02-10 02:28:43   198 3900407
2     16 2011-01-30 08:50:28   197 3900407
3     17 2011-03-25 01:04:02   202 3900407
4     18 2011-01-08 20:14:08   195 3900407
5     15 2010-12-29 03:32:41   194 3900407
6      9 2011-04-04 19:51:39   203 3900407
7      8 2011-04-26 07:02:30   205 3900407
8      5 2010-12-18 08:00:11   193 3900407
9      4 2010-12-07 11:53:44   192 3900407
10     2 2011-05-07 01:09:08   206 3900407
11     1 2010-10-14 20:48:57   187 3900407
12     3 2011-04-15 11:24:30   204 3900407
13     6 2011-05-17 17:40:07   207 3900407
14    12 2011-05-28 11:28:08   208 3900407
15     7 2010-11-26 20:33:25   191 3900407
16    10 2010-10-25 11:35:16   188 3900407
17    13 2010-11-05 08:35:03   189 3900407
18    14 2010-11-16 02:57:04   190 3900407 
```
so, indeed, the times (and cycles) are not in order.

I don't really think `readProfiles()` should put them in order -- I think it should obey the files as they are.  However, I think `plot(..., which="QC")` ought to put them in order, so I'll do that in a moment.

I will also need to attend to this in the shiny app.  Actually, this explains something that was confusing me in the app.

**Comment by dankelley** [comment]
This should work now in "develop" commit a50e9c88109317f138e2312bd89ba76a48303f32; to test, `git pull`, rebuild, and then do as follows
```
cd issues/2xx/228
make
```
and view the `.png` file.

---

Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done. *Thanks!*

PS.  This is a standardized reply.
