### ISSUE TITLE
another weird float to look at

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#229]
This little fella (pic from the app) jumped over Florida.  It might be worth checking on it.  Maybe it was in shallow water and didn't make profiles?  Maybe it was caught in a net?  Maybe it wanted some orange juice so it went on land for a while, decided it didn't like how they vote there, and headed back to sea?

Could you look into it, @j-harbin?

<img width="1022" alt="Screen Shot 2020-09-04 at 8 21 12 AM" src="https://user-images.githubusercontent.com/99469/92234155-ec428700-ee87-11ea-96b3-ee02843f663e.png">

**Comment by j-harbin** [comment]
So when I do the following code:
```R
library(argoFloats)
index1 <- subset(getIndex(), id='4901596')
# To focus on last point on the left of Florida, and then 4 points to the right of Florida
index2 <- subset(index1, 234:239)
profiles <- getProfiles(index2)
argos <- readProfiles(profiles)
for (i in 1:5) {
    print(range(argos[[i]][['latitude']]))
}
```
Produces:
```R
[1] 23.88047 23.88047
[1] NA NA
[1] NA NA
[1] 27.71069 27.71069
[1] 27.80043 27.80043
```
Which shows us that the first and second points to the right of Florida ( remembering that the first argos object is on the left of Florida) have no values for lat and lon.

Diving further into this:
```R
showQCTests(argos[[2]], style='full') # To look at first point to the right of Florida
```
We receive:
```R
Test |  Status  | Description
-----|----------|--------------------------------------------------------------
   1 |  Skipped | Platform Identification test
   2 |   Passed | Impossible Date test
   3 |   Passed | Impossible Location test
   4 |  Skipped | Position on Land test
   5 |  Skipped | Impossible Speed test
   6 |  Skipped | Global Range test
   7 |  Skipped | Regional Global Parameter test
   8 |  Skipped | Pressure Increasing test
   9 |  Skipped | Spike test
  10 |  Skipped | Top and Bottom Spike test (obsolete)
  11 |  Skipped | Gradient test
  12 |  Skipped | Digit Rollover test
  13 |   Passed | Stuck Value test
  14 |  Skipped | Density Inversion test
  15 |  Skipped | Grey List test
  16 |   Passed | Gross Salinity or Temperature Sensor Drift test
  17 |  Skipped | Visual QC test
  18 |  Skipped | Frozen profile test
  19 |  Skipped | Deepest pressure test
  20 |  Skipped | Questionable Argos position test
  21 |  Skipped | Near-surface unpumped CTD salinity test
  22 |  Skipped | Near-surface mixed air/water test
  23 |  Skipped | Interim rtqc flag scheme for data deeper than 2000 dbar
  24 |  Skipped | Interim rtqc flag scheme for data from experimental sensors
  25 |  Skipped | MEDD test
-----|----------|--------------------------------------------------------------
```
Which is interesting that Impossible Location Test was passed considering there are no lat and lon values.

**Comment by dankelley** [comment]
Maybe add the times to your printout?  That could help in this detective work.  Fun!

**Comment by j-harbin** [comment]
Good idea!
```R
time <- oce::numberAsPOSIXct(unlist(argos[["time"]]))
data.frame(Time=time, Cycle=argos[['cycle']])
```
```R
               Time Cycle
1 2020-06-30 23:20:38   233
2 2020-07-10 23:27:43   234
3 2020-07-21 00:22:35   235
4 2020-08-09 06:00:43   237
5 2020-08-18 20:21:53   238
6 2020-08-28 10:37:11   239
```
This shows that the cycles are in order in terms of time, and the "left" to "right" of Florida journey took 10 days.

**Comment by dankelley** [comment]
You might want to figure out the distance (the new text-output box in the app shows distances from a given float up to 100km, so you can get a scale that way, or from the y axis) and then figure the speed in m/s ... is it credible?

**Comment by j-harbin** [comment]
As discussed in a vftf with @dankelley, looking at cycle 333 and 337 (left and right of Florida). There is about a 40 day span in between the floats. As shown by the following calculation:

```R
700e3/40/86400
```
```R
0.2025463
```
The float would be moving at about .2 m/s. This is credible. Feel free to close this issue if you agree.

**Comment by dankelley** [comment]
Closing
