### ISSUE TITLE
start tweet thread

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#230]
This stems from #140, but the goal here is to start issuing those tweets.  (I am following our usual rule of closing issues when the subject defined in the title has been addressed, and the other title was "make R markdown for tweet thread")

**Comment by j-harbin** [comment]
@richardsc, I have updated the tweet thread to include `mapApp()` and remove any merged datasets. You can see the changes in commit f824ce193708704de74a63391d94d00788f1c13f of the develop branch. The tweets are now fully up to date.

**Comment by richardsc** [comment]
Great, thanks! I built the Rmd last week but will do it again now to check it out

**Comment by j-harbin** [comment]
@richardsc, please note that the tweet thread has been updated to account for the `id` to `ID` change. More specifically, the screen shots of the `useAdjusted()` and `showQCTests()` code were updated. The changes can be found in commit dd147a82d177a446ec6f5b0d6be17426db976085 of the develop branch.

**Comment by j-harbin** [comment]
@richardsc, please note that the Rmd has been updated again. I changed the order of the `applyQC` and `showQCTests`. I did this because that is the natural order we use when working with the data, and also the order we use in our paper. It now looks like the following:

![Screen Shot 2020-10-23 at 1 13 37 PM](https://user-images.githubusercontent.com/58750538/97027759-9908be80-1531-11eb-9594-c3120007d036.png)

**Comment by richardsc** [comment]
Thanks @j-harbin . I've been preparing for the release of this a bit by lining up some of my "big name" science Twitter friends to help promote and retweet. I think we're getting close to starting to promote this (I still need to get the DFO comms folks on board).

**Comment by j-harbin** [comment]
As per the conversation with @richardsc, I have updated the tweet thread to include the `dataStateIndicator` subset. This can be found in 
commit 67744474850455e961347695839741dfb0824f2d of the develop branch.
