### ISSUE TITLE
create mapApp()

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#234]
This is a followup to positive votes on #226.  The app will be called `mapApp()`.

**Comment by dankelley** [comment]
ACTION for @j-harbin stated below.

This is done in the "develop" branch, commit 2019cb4b12f1761a3b262701696c477f00492094

@j-harbin: perhaps you can read the docs for `?mapApp` and tell me if it's clear, or close the issue if it is clear.

Notes:

1.  It took me quite a while to convert the code to be part of the package (as opposed to self-contained) but it seems OK now.  Note that it creates a local file named `argo.rda`, which burns up space (a negative) but makes it load in tens of seconds, rather than several minutes. 

2. The cache time is set to 7 days.  That's different from the 1-day cutoff for `getIndex()`, simply because I find it really annoying for the app to sit there for a minute or two to download the files, create a local cache file, etc.  Somehow, time delays are more annoying with a GUI system.

3. I was going to make `mapApp()` take an argument for the age cutoff, but had problems with global variables, and decided I'd prefer to push what I have, for now, so I can focus on other things.

**Comment by j-harbin** [comment]
Great work on this! I know this was a lot of work, on top of very busy times. I've just read this all over and it looks great. The only comment I will make, in addition to some *minor* spell tweaks I did,  is that for the first time when the app is downloading the index, it takes about a minute. On the app, we don't have the blue loading button that pops up, instead in RStudio, we have the progression of the index that always prints out. I therefore added a line in the docs stating it may take a few seconds.

These change can be found in commit e43a0cf3518a99dde032f58155bf562d16a6a76c of the develop branch.

I think this is done and I believe this issue can be closed.

**Comment by dankelley** [comment]
@j-harbin why did you change a test?  With the new version, I get an error as below.  Do you get the same error?  We could do a 10-minute z if you like, but I can't take much more time than that, at this time on a teaching day.

```
x |  49 1     | subset [10.3 s]
──────────────────────────────────────────────────────────────
test_subset.R:111: failure: subset by column
`readProfiles(p)` produced warnings.
```

**Comment by j-harbin** [comment]
I did a change a test because when I "checked" the package, I received the error that `readProfiles(p)` didn't produce any warnings. I believe this is because last week I was playing with `warnings()` in my RStudio. I will find out the default and adjust it accordingly.

**Comment by dankelley** [comment]
Maybe restart RStudio and do the `readProfiles()` manually, to see if there's a problem?

**Comment by dankelley** [comment]
I'm going to close this, since the issue (as defined by the title) has been addressed.

If there are lingering problems with the 'check' operation, perhaps @j-harbin can submit a new issue.
