### ISSUE TITLE
missing filename in an index??

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#236]
@j-harbin can you look into this?  The screenshot explains, I think.  This is perhaps a new thing, since I am in the middle of altering some tests (because I changed `silent` to `quiet` and then added a progress-bar ... **not** pushed to GH yet!)

<img width="1192" alt="Screen Shot 2020-09-09 at 10 05 58 AM" src="https://user-images.githubusercontent.com/99469/92602245-49717a80-f284-11ea-8ccc-6fc9540221de.png">

**Comment by j-harbin** [comment]
Hi Dan,

I can confirm that this is not related to the work that you have done that is not pushed to GH, because I receive this error as well. I will look into this. It's interesting because doing:

```R
s[['file']]
```
returns
```R
[1] "aoml/4901536/profiles/R4901536_094.nc" "aoml/4901622/profiles/R4901622_167.nc"
[3] "aoml/4901628/profiles/R4901628_212.nc"
```
Therefore we know [2] is not NA.

**Comment by j-harbin** [comment]
Ah! But doing,
```R
p[['file']]
```
returns
```R
[1] "~/data/argo/R4901536_094.nc" NA                            "~/data/argo/R4901628_212.nc"
```

Ok, I'm excited! I love this detective work.

**Comment by dankelley** [comment]
NOTE: Q for @j-harbin below.

This is because of an arg to `getProfiles()`, the doc of which reads as below.

I am not sure I agree with the choice we made for the default.  I want to change it to `FALSE`, because I would rather an error message occur than that the user gets a funky result with something blanked out.  Do you agree, @j-harbin?

<img width="479" alt="Screen Shot 2020-09-10 at 2 54 58 PM" src="https://user-images.githubusercontent.com/99469/92776729-ea8c2e00-f375-11ea-8589-86ea876c61c7.png">

**Comment by dankelley** [comment]
Via separate email, @j-harbin has agreed with my suggestion to use `FALSE` as the default value for `skip`, so I will do that.

**Comment by dankelley** [comment]
Fixed (with clean build, test, and check) in "develop" branch, commit 7d0ef052a8a7d2d29250dff62a19afc5b7d6403e
