### ISSUE TITLE
Make video 11: mapApp()

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#250]
As discussed in a vftf with @dankelley, we will make a video 11 to show the `mapApp()` function.

The description for the video can be found at

https://github.com/ArgoCanada/argoFloats/blob/develop/videos/11/decription.Rmd

**Comment by dankelley** [comment]
Done, and uploaded to youtube at https://www.youtube.com/watch?v=PEkIBwXLLpE&feature=youtu.be
