### ISSUE TITLE
... arguments for plot(x, which='profile') not working

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#257]
When plotting
```R
library(argoFloats)
data(index)
argos <- readProfiles(getProfiles(subset(index,1:2)))
plot(argos, which='profile', parameter='temperature', col='blue')
```
The plot remains black. This is also the case for arguments like `type` and `pch`, etc.

**Comment by dankelley** [comment]
Should work now in a3e0bb114379b38c6260bbcfd7c2debfe4f3aeb7.  I did the bugfix during a meeting, so it was a quick one ... you might want to look at the diff, to see if I've missed anything.  The deal is that `col` is a named argument, so it does not go into `...`

**Comment by j-harbin** [comment]
This all works now, thanks Dan. I will close this issue.
