### ISSUE TITLE
discussion: I suggest switching axes to signed lons and lats

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#258]
As I suggested at

https://github.com/dankelley/oce/issues/1735

I think our default for `plot,argoFloats-method` axis labels is faulty.  Surely anyone looking at a map will be able to understand negative numbers, since this is on the grade 6 curriculum, i.e. for 11 year olds (https://curriculum.novascotia.ca/english-programs/course/mathematics-6).

Also, we burn up a lot of space with those letters, which can lead to near-overlapping of the lon and lat labels at the lower-left corner (see the link above for an image).

These are two reasons why I suggest we switch our axis notation to signed numbers, by default.

I wonder how @j-harbin and @richardsc think?  (We could discuss this in our vf2f meeting tomorrow, if folks don't want to weigh in here.)

**Comment by richardsc** [comment]
I prefer without the numbers, but it’s nice to have the option. Is it easy to keep the functionality, but with an arg?

**Comment by dankelley** [comment]
You mean without letters?

Yup, my proposal is that we have an arg to determine the format (the arg can be the same as in oce, which was updated 20 minutes ago for a new type, `geographical=4`)

**Comment by richardsc** [comment]
> You mean without letters?

> Yes. That is what I meant.

... time for some coffee

**Comment by j-harbin** [comment]
I agree with the fact that the takes up too much space, but of course, that is just our opinion and somebody else may want to use the current default format that we have. For this reason, I agree to changing it while also keeping it an option with an additional arg.

**Comment by dankelley** [comment]
It seems that we have agreement.

Therefore, I plan to add a new arg to `plot,argoFloats-method`, called `geographical`, with the same options as for `plot,coastline-method` in `oce`.

**Comment by dankelley** [comment]
This is done in "develop" commit 475a0caa9e70045396c00e1a78086189f9a95b96

Test code and results follow.
```R
library(argoFloats)
data(index)
png("0.png")
par(mar=c(2.5, 2.5, 2, 2))
par(mfrow=c(2,2))
plot(index, which="map")
mtext("geographical=0 (default)")
plot(index, which="map", geographical=1)
mtext("geographical=1")
plot(index, which="map", geographical=4)
mtext("geographical=4")
dev.off()
```
![0](https://user-images.githubusercontent.com/99469/95335086-54202f00-0885-11eb-8899-fd89af54251c.png)

**Comment by dankelley** [comment]
I'll close this, but of course @j-harbin and @richardsc should feel free to reopen it, e.g. if they don't like my explanation in the docs.  I did not emulate 2 of the styles that oce provides, because I don't think an argo plot is ever going to need minute-scale or second-scale plot axes.  (A minute is about 1.8km, and a float travelling at even 1cm/s will go 10km in the inter-cycle time, so we would never need to show minutes, let alone seconds.)

**Comment by j-harbin** [comment]
Dan, thanks for doing this so quickly. One thing I will note (which may not be a big deal) is that for `argoFloats` vs `oce` the axes differ in that tick marks extend on the top and on the right for the `oce` plots,  but not for `argoFloats` (shown below).

Once upon a time there was somebody who drilled the idea of **beautiful** diagrams in my head....

![10_ctd_argo](https://user-images.githubusercontent.com/58750538/95336182-c1808f80-0886-11eb-94c4-9985d17c1e3c.png)

**Comment by dankelley** [comment]
Ha!  But which style is more beautiful?  I can make the af one be like the oce one in about 2 minutes; just say the word.  (It will be this afternoon, since classes start in a moment.)

**Comment by dankelley** [comment]
Also, I notice that the argo one is not noticing that it is a full-world view, like the coastline one is.  I will fix that because, oh my, that's so ugly to me, actually!!

**Comment by j-harbin** [comment]
I agree! +1 for making the argoFloats be the same as coastline.

**Comment by dankelley** [comment]
The present argoFloats default would show e.g. lat from -90 to 90.
