### ISSUE TITLE
Update Youtube Documentation to use ID instead of id

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#265]
I am assigning this to Dan, however, I will provide exact videos/ updates that need to be done once I code `[['ID']]` to work instead of `[['id']]`

**Comment by j-harbin** [comment]
*Video 06*
Remove "(2) argoFloats now refers to "id" rather than "ID", e.g. subset(a,ID='124') would become subset(a,id='124') and a[["ID"]] would become a[["id"]]." from the description

*Video 07*
Remove "(2) argoFloats now refers to "id" rather than "ID", e.g. subset(a,ID='124') would become subset(a,id='124') and a[["ID"]] would become a[["id"]]. " from the video description

*Video 08*
In the description please add "argoFloats now refers to "ID" rather than "id", e.g. subset(a,id='124') would become subset(a,ID='124') and a[["id"]] would become a[["ID"]]."

*Video 09*
In the description please add "argoFloats now refers to "ID" rather than "id", e.g. subset(a,id='124') would become subset(a,ID='124') and a[["id"]] would become a[["ID"]]."

Please note that all sample code has been updated.

**Comment by dankelley** [comment]
I finally got around to this, and have made the changes.  Don't ask me why it took me 3 weeks to get around to a 3 minute task :-)
