### ISSUE TITLE
getIndex() should tell about unexpected first arg value

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#268]
See below
```R
> library(argoFloats)
> i<-getIndex("howdie")
Error in getIndex("howdie") : 
  cannot construct .rda filename (please report an issue)
```

**Comment by j-harbin** [comment]
done in commit 698dad768f54e388cf91a1fcbbe699eb0198ded3 of the develop branch

**Comment by j-harbin** [comment]
Thanks for your help on this Dan, the suggestions you made are done in commit ed9bf20f2fb2ff6fa71734e2b5aeb171257a118c of the develop branch. Please feel free to close this issue if you are satisfied with the changes.

**Comment by dankelley** [comment]
No time to check -- I'll trust you!  Closing.
