### ISSUE TITLE
QC plots should show cycle # on top axis of top panel

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#269]
@richardsc suggested this for the paper, and I agree, so I'll code it.

**Comment by dankelley** [comment]
This is done in "develop" branch.

I altered example 7 of `plot,argoFloats-method` because it was subsetting by rectangle, so the cycle numbers had gaps as the float sometimes entered and sometimes left the box.  Now the temperature QC plot looks as below.  

I am closing this issue, since I'm happy with the result, and I was the reporter.

![a](https://user-images.githubusercontent.com/99469/97046344-9f0c9880-154d-11eb-978b-d046fc30ead0.png)

**Comment by dankelley** [comment]
PS. the cycle axis has the leading zeros because cycles are stored as strinjgs.  Maybe @j-harbin can figure out if they are always just integers with leading zeros, in which case we can switch to use `as.integer()` on those strings.  But I think sometimes we see a "D" in a cycle indicator, which means we must stick with strings.  I am reopening this and assigning it to J, who can either change to an integer or put a comment here and close the issue.

**Comment by richardsc** [comment]
Nice!

**Comment by j-harbin** [comment]
Hi Dan,

Firstly, great job on this, and a great suggestion by Clark to include the cycle numbers. One thing I will say is you're right, the descending profiles have a `D` at the end of the cycle number, for example, `001D`, and therefore the as.integer wouldn't work.

One other thing I did want to note, is that explained on page 13 of the Argo User's Manual [1], although usually the cycle numbers for an Argo float start at 001, sometimes a cycle of 000 exists. Below the manual is quoted to explain cycle 0.

"Cycle 0 contains the first surface drift with technical data transmission or configuration information. This data is reported in the technical data files.
Cycle 0 may contain subsurface measurements if a descending/ascending profile is performed before any data transmission. The time length of this cycle is usually shorter than the next nominal cycles. The cycle time is therefore regular only for later profiles and may be variable if the float is reprogrammed after its deployment."

[1] Carval, Thierry, Bob Keeley, Yasushi Takatsuki, Takashi Yoshida, Stephen Loch Loch, Claudia Schmid, and Roger Goldsmith. Argo User’s Manual V3.3. Ifremer, 2019. https://doi.org/10.13155/29825.

**Comment by j-harbin** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done. Thanks!

PS. This is a standardized reply.

**Comment by dankelley** [comment]
Done :-)
