### ISSUE TITLE
type argument doesn't work for plot(x, which="profile")

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#272]
The following code produces no plot (note: `type="l"`)

```R
library(argoFloats) 
index <- subset(subset(getIndex("synthetic"), ID="5903586"), cycle="001")
adjusted <- useAdjusted(readProfiles(getProfiles(index)))
par(mar=c(1,3.5,3.5,1))
plot(adjusted, which="profile", profileControl=list(parameter="oxygen"), type="l")
```
However, if we change the plot argument to say `type="p"`, the plot works fine.

**Comment by dankelley** [comment]
**QUESTION FOR CR AND JH AT THE END**

This is an interesting one.  No plot is created because the non-`NA` values occur singly, with strings of `NA` values in between.  By default, R does not join up single points.  You can see that with
```R
x<-1:5
y<-c(1,NA,2,NA,3)
par(mfrow=c(2,1))
plot(x,y)
plot(x,y,type='l')
```
in which the first plot has points, but the second has no line.

The question is whether, for these profile plots, we ought to simply remove the `NA` values and join up what is left.  I am divided on that question.  I like to follow R conventions, and so when I coded this, I did not skip over the `NA` values.  But I could be reversed in this thinking...

What do @richardsc and @j-harbin think? 

PS. this is why the first draft of our paper shows points and not lines.

**Comment by j-harbin** [comment]
This is a good point. One thing I will note is that`plotProfile()` in `oce`,  defaults to `type="l"`, and the user has the option to use `type="p"`. For example:

```R
library(oce)
data(ctd)
par(mfrow=c(1,2))
plotProfile(ctd, xtype="temperature")
plotProfile(ctd, xtype="temperature", type="p")
```
![Screen Shot 2020-10-27 at 8 10 09 AM](https://user-images.githubusercontent.com/58750538/97293752-dae47e00-182b-11eb-808b-1def5c0aa99b.png)

Would this mean NA values would be skipped in `plotProfile()`? If yes, I would argue to make `argoFloats` consistent with `oce` and allow the user to have the option to do `plot(x, which="profile", profileControl=list(parameter="temperature", type="l"))`

**Comment by dankelley** [comment]
No, `oce::plotProfile` does not skip over the `NA` values.  It breaks the lines at such spots, in accordance with the usual R conventions.

**Comment by j-harbin** [comment]
As discussed in a vftf with @dankelley, we thought it may be a good idea to follow R conventions, and not skip over the NA values. Another option that Dan pointed out, if we saw a real advantage to connecting the points, we could have another arg such as, `connect=TRUE` or something like that.

**Comment by dankelley** [comment]
I was thinking that the arg could be called `na.rm`, but `connect` is maybe better because it has no wider meaning within R.

**Comment by dankelley** [comment]
@j-harbin I added a way to do this in "develop" commit bc922d791b525028231b95f81cc5a1fa25046e6e.  See the docs for the `profileControl` argument.  I find that the following work nicely for me
```R
library(argoFloats) 
index <- subset(subset(getIndex("synthetic"), ID="5903586"), cycle="001")
adjusted <- useAdjusted(readProfiles(getProfiles(index)))
plot(adjusted, which="profile", profileControl=list(parameter="oxygen"), type="l")
plot(adjusted, which="profile", profileControl=list(parameter="oxygen"), type="o")
plot(adjusted, which="profile", profileControl=list(parameter="oxygen"), type="b")
plot(adjusted, which="profile", profileControl=list(parameter="oxygen"), type="p")
```

**Comment by dankelley** [comment]
The paper should show `type="o"`, in my opinion, so please set that up.  You'll need to alter the part where we manually draw the second variety on top of the profile, of course.

**Comment by j-harbin** [comment]
This issue has been resolved.
