### ISSUE TITLE
Use tempfile  to test `getIndex` and `getProfiles`

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#274]

**Comment by j-harbin** [comment]
This is done in commit 07ace9002437300a9fd7e3e7c116d342b8335b68 of the develop branch. This was my first time doing this, so it may be a good idea to get somebody to look at this before I close this issue (no rush)

**Comment by j-harbin** [comment]
I should also note that this commit increased the codecov for the argoFloats package from 55.96% to 59.38% and increased the codecov for get.R from 53.33% to 78.97%

**Comment by dankelley** [comment]
Oh, that codecov increase is great!!  I will look at your stuff tomorrow morning, and then either suggest changes or suggest you close this.

**Comment by dankelley** [comment]
J, I suggest you change `tmp_file` to `tmpFile` or `temporaryFile`, because we use camelCase in this package.  Once that's done, you ought to go ahead and close it.  It looks ok, and if the test works, that means we're fine.

**Comment by j-harbin** [comment]
Done in commit 3b744996555127fdcd52d20eedaee394303450ad of develop.
