### ISSUE TITLE
what should getProfiles() do if the file is not on the server?

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#281]
**Preamble.** Earlier today I was having trouble with the usgodae server, which was not providing index files (or the netcdf files I wanted either ... maybe it was flat-out down, but that's not the point.  I added a think in `readProfiles()` to give an error message if *none* of the required files exist locally.  (It already gives a warning for those files.). But, if *none* are available, then `readProfiles()` was previously handing a missing filename to `oce::read.argo()`, which gave an obscure method.  Now, we get a message from within `argoFloats::readProfiles()`, so that part is ok now.

**Question.**. What should `getProfiles()` do if it cannot download a file?  Should it just report the problem and keep on trying for other files?  Or maybe it should just give an error and stop.  I'm not worried about the coding -- we can do anything -- but my question is what is easiest for the user.

**Comment by richardsc** [comment]
I feel like a warning is probably the best approach here. I can imagine a few scenarios:

a) Someone is downloading only a few relevant profiles for a specific purpose (e.g. regional), and would very likely notice a warning message saying that such-and-such a file was not found on the server (perhaps the message should warn that they should try again later ...).

b) Someone is going a large study that involves hundreds or thousands of profiles, and likely will not care if one or two didn't download for some reason, but certainly would be a lot more bothered if their entire download kept crashing in the middle until they could figure out which files were not found, and manually remove from the `getProfiles()` call.

**Comment by dankelley** [comment]
Thanks, @richardsc.  I've set it up to do that, in "develop" commit 79b81c4e42abc0b9aa2939522b8b3f25a876f465

And, as I guessed, the problem I had with usgodae has gone away; the following now works, because the files now exist (again).
```R
library(argoFloats)
index1 <- subset(getIndex(), ID="4902502")
index2 <- subset(index1, time=list(from="2020-10-11", to="2020-10-23"))
ascent <- subset(index2, direction="ascent")
descent <- subset(index2, direction="descent")
cycle002 <- subset(index1, cycle="002")
pA <- getProfiles(ascent)
cat(oce::vectorShow(pA[["file"]]))
pD <- getProfiles(descent)
cat(oce::vectorShow(pD[["file"]]))
p002 <- getProfiles(cycle002)
cat(oce::vectorShow(p002[["file"]]))

argosA <- readProfiles(getProfiles(ascent))
argosD <- readProfiles(getProfiles(descent))
argos002 <- readProfiles(getProfiles(cycle002))
```

**Comment by j-harbin** [comment]
I know this issue is closed, but I thought that I would mention that I agree with @richardsc. I think it would have been too restricting to simply add an error message. Great work, Team.
