### ISSUE TITLE
should the first server tried be ifremer instead of usgodae?

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#282]
I see problems with usgodae quite a lot, and I think we have some hints that ifremer is faster.  I know the "good citizen" thing to do might be to use the server on this continent, but I am feeling I would like to switch so that `getIndex()` tries ifremer first, and moves to usgodae only if ifremer fails.

The other thing is that ifremer seems more up-to-date than usgoadae (evidence of this being the fact that ifremer switched to 'synthetic' indices first).

What do you think, @j-harbin and @richardsc?

**Comment by dankelley** [comment]
Thanks, @richardsc.  I've set it up to do that, in "develop" commit 79b81c4e42abc0b9aa2939522b8b3f25a876f465

And, as I guessed, the problem I had with usgodae has gone away; the following now works, because the files now exist (again).
```R
library(argoFloats)
index1 <- subset(getIndex(), ID="4902502")
index2 <- subset(index1, time=list(from="2020-10-11", to="2020-10-23"))
ascent <- subset(index2, direction="ascent")
descent <- subset(index2, direction="descent")
cycle002 <- subset(index1, cycle="002")
pA <- getProfiles(ascent)
cat(oce::vectorShow(pA[["file"]]))
pD <- getProfiles(descent)
cat(oce::vectorShow(pD[["file"]]))
p002 <- getProfiles(cycle002)
cat(oce::vectorShow(p002[["file"]]))

argosA <- readProfiles(getProfiles(ascent))
argosD <- readProfiles(getProfiles(descent))
argos002 <- readProfiles(getProfiles(cycle002))
```

**Comment by j-harbin** [comment]
I agree with this, Dan. I think we should try to switch it to ifremer, and if we find we have the same problems as we did with usgodae we can always switch it back.

**Comment by dankelley** [comment]
Good.  Can you do the coding?  There is likely a sentence in the docs that needs changing also.

PS. usgodae is working again today.   But I also improved things in the code to handle failed downloads better (#281).

**Comment by j-harbin** [comment]
I'm working on this coding now! Thanks

**Comment by j-harbin** [comment]
Done in commit aa55b00dbf27afe3965a047f8d51428772ec5bc8 of the develop branch. I know you are busy with class work, so I will break the unwritten rule, and close this issue myself :)
