### ISSUE TITLE
mapApp() not displaying last cycle during path trajectory

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#283]
As discussed in the issue https://github.com/ArgoCanada/argoFloats/issues/279, the following screenshot shows that the most recent cycle (indicated by the black square) was cycle 454 on 2020-08-05. You'll notice, however, that my "End" date is 2020-08-07, which aligns with Dan's screenshot (screenshot number two) that cycle 455 was taken on 2020-08-07. This is telling me for some reason, my path or trajectory does not show the last cycle, but the "End" time shows up correctly with the most recent time.

![](https://user-images.githubusercontent.com/58750538/98036113-dbfb4980-1def-11eb-95b9-39b2712adae1.png)

![](https://user-images.githubusercontent.com/99469/97441255-48191180-1907-11eb-850d-58b8cfa83315.png)

I further investigated this by looking at the float we use in our trajectory example in the paper, ID 6900388. The following code shows that the date for this float ranges from  2005-10-29 13:57:42 UTC to  2011-11-27 05:11:40 UTC

```R
library(argoFloats)
index1 <- subset(getIndex(), ID="6900388")
range(index1[["date"]])
```
Furthermore,

```R
index1[['cycle']]
```
produces the following output indicating the last cycle number for this float was 223.

```R
 [1] "001" "002" "003" "004" "005" "006" "007" "008" "009" "010" "011" "012" "013" "014" "015" "016" "017" "018"
 [19] "019" "020" "021" "022" "023" "024" "025" "026" "027" "028" "029" "030" "031" "032" "033" "034" "035" "036"
 [37] "037" "038" "039" "040" "041" "042" "043" "044" "045" "046" "047" "048" "049" "050" "051" "052" "053" "054"
 [55] "055" "056" "057" "058" "059" "060" "061" "062" "063" "064" "065" "066" "067" "068" "069" "070" "071" "072"
 [73] "073" "074" "075" "076" "077" "078" "079" "080" "081" "082" "083" "084" "085" "086" "087" "088" "089" "090"
 [91] "091" "092" "093" "094" "095" "096" "097" "098" "099" "100" "101" "102" "103" "104" "105" "106" "107" "108"
[109] "109" "110" "111" "112" "113" "114" "115" "116" "117" "118" "119" "120" "121" "122" "123" "124" "125" "126"
[127] "127" "128" "129" "130" "131" "132" "133" "134" "135" "136" "137" "138" "139" "140" "141" "142" "143" "144"
[145] "145" "146" "147" "148" "149" "150" "151" "152" "153" "154" "155" "156" "157" "158" "159" "160" "161" "162"
[163] "163" "164" "165" "166" "167" "168" "169" "170" "171" "172" "173" "174" "175" "176" "177" "178" "179" "180"
[181] "181" "182" "183" "184" "185" "186" "187" "188" "189" "190" "191" "192" "193" "194" "195" "196" "197" "198"
[199] "199" "200" "201" "202" "203" "204" "205" "206" "207" "208" "209" "210" "211" "212" "213" "214" "215" "216"
[217] "217" "218" "219" "220" "221" "222" "223"
```

In the screenshot of the path (or trajectory) for this float ID, however, you'll see that the last point, highlighted with a black box, is dated 2011-11-17 (10 days before the last cycle was recorded), AND, the cycle number only goes up to 222 (not 223). Note that the trajectory is zoomed in to show the final point, and the full path is not shown.

![Screen Shot 2020-11-04 at 7 45 32 AM](https://user-images.githubusercontent.com/58750538/98108069-cdee0d00-1e71-11eb-90ff-dc938249a7cd.png)

**Comment by dankelley** [comment]
First, I wonder if part of this can be that maybe your index and mine were acquired at different times.  (I think they change past data, in addition to adding new data.)

Second, maybe the usgodae and ifremer servers are giving different indices.

Third, how about a quick Z meeting (just J and I) to try to get on the same page?  I'm a bit behind.

**Comment by dankelley** [comment]
Notes during  Z. meeting:
1. J and D now agree on most-recent points, so #279 is definitely addressed.
2. We ought to use `mapApp(age=0)` in future, to ensure we are getting the same index files. (Some of this was likely that one of us had a not-yet-too-old usgodae file, and the other had a ifremer file.)


Next steps:

1. document new 'server' arg for mapApp
2. test with one of the IDs, using 'a' server and 'f' server. Check the time shown in mapApp and also the time reported by R.  (This may help us to see if perhaps the index file is in UTC, but the data themselves are shifted.)
3. if the above fails, change mapapp.R:278 and 279 to shift by 24h, as a crazy test of times.

**Comment by j-harbin** [comment]
1. Done
2. The following code tells us that both the `usgodae` and `ifremer` servers give us the same index. Both with an end date of 2011-11-27 05:11:40 UTC and max cycle of 223.  When looking the path for this ID, however, on the app, it only goes at high as a date of 2011-11-17 and cycle 222. It should be noted that the "End" time in the top left of the app does provide the correct date (ie. 2011-11-27).
```R
library(argoFloats)
indexf <- subset(getIndex(server="ifremer"), ID="6900388")
indexu <- subset(getIndex(server="usgodae"), ID="6900388")
range(indexf[["date"]])
range(indexf[['cycle']])
range(indexu[["date"]])
range(indexu[['cycle']])
```
Note: I think some changes we made in the vftf when adding the server in `mapApp.R` broke the code because `mapApp()` no longer works. 

```R
Warning: Error in [: object of type 'environment' is not subsettable
  52: argoFloats::getIndex [/Users/jaimiekeeping/Documents/GitHub/argoFloats/R/get.R#234]
  51: server [/Users/jaimiekeeping/Documents/GitHub/argoFloats/R/mapApp.R#97]
Error in server[iserver] : 
  object of type 'environment' is not subsettable
```
Leave this with me!

**Comment by dankelley** [comment]
I think the start and end times may be just simple dates, e.g. 2011-11-27T11:12:13 becomes 2011-11-27T00:00:00 for the comparison.  So maybe try changing that "<=" test where we put in an extra 1 hour to put in 24 hours...

Offline for 2 hours now.

**Comment by j-harbin** [comment]
Conclusion:

The `mapApp()` was not working, because when getting the index for core and BGC, we had `server=server` instead of `server="auto"`. This now works. Additionally, by adding the 24 hours to the end time the last cycles are now displayed (YAHOO!). These changes can all be found in commit 1dc15f522bb658c61e1e9a97f5234b9f8d62a829 of develop.

I am therefore closing this issue.

**Comment by dankelley** [comment]
Fast work!  Note that I improved the comment on those time shifts in "develop" commit c1250369006480740861aeda7db695f4ec0e10bc
