### ISSUE TITLE
DESCRIPTION's 'Description' field should be more informative

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#288]
@j-harbin, I wonder if you and I can talk over Z next week (which is 'study break' week, so I have more time!), to do a joint edit of the 'Description' field that's in the DESCRIPTION file. I'm showing a screenshot of it and the oce one.  The latter is about the length that I think makes sense.  A few points we might want to get in there are as follows.  I propose we both think about this a bit, and finalize something early next week.

1. they are *ocean* floats
2. they *profile*
3. data come in constantly so we need a good caching mechanism
4. users can rely on the oce package to do lots of things (e.g. QC handling, seawater computations, graphics)

<img width="1090" alt="Screen Shot 2020-11-07 at 12 35 15 PM" src="https://user-images.githubusercontent.com/99469/98446719-cb034e80-20f5-11eb-9761-f03c9a62973a.png">

**Comment by j-harbin** [comment]
Dan, I know we didn't get to discuss this on our Zoom today, but here is a draft for the DESCRIPTION:

Supports the analysis of Argo, autonomous drifting profiling float, data by identifying data sources, downloading, and caching the constant flow of data. Provides tools to sift through data based on float ID, time, geography, variable, profile, etc, and is closely tied to oce to allow for QC handling, seawater computations (such as "UNESCO" or "TOES-10" equation of state), and graphics that conform to conventions of Oceanographic literature.

**Comment by dankelley** [comment]
Thanks. I updated the DESCRIPTION file.  Maybe you could have a look and if it seems ok, close this.  (Otherwise, make edits as you see fit.)
