### ISSUE TITLE
suggested mapApp() change: show 10 days at launch screen

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#294]
I think we should make it so the launch screen shows 10 days of data, so that the number of dots will roughly represent the number of floats in the "fleet".  (At the moment, it shows 30 days, which gives the impression that the fleet is 3X larger than it actually is.)

@j-harbin, if you agree, please make the change and close this. If you disagree, please give a reason.

**Comment by j-harbin** [comment]
Agreed. Done in commit 9cda08e1cdc553a061eaa02878e1759fe6065187 of the develop branch.
