### ISSUE TITLE
subset() by cycle should permit numeric criteria

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#303]
The recent change to require character arguments, e.g.
```R
subset(i, cycle="020")
```
is fine for a single cycle, but I think user would love to be able to do e.g.
```R
subset(i, cycle<=100)
```
to get a set of cycles.

I think what we should do is to check whether the criterion contains a character string, and in that case, use the existing code, *but* if it does not contain such a string, we should use `as.integer()` on the cycles within `i`, and then apply the criterion.

Do you agree, @j-harbin?

**Comment by richardsc** [comment]
You didn't ask me, but I agree and was thinking exactly this after seeing the character issue.

**Comment by j-harbin** [comment]
This is done for both `"index"` and `"argos"` types in commit e4f259b010a8ce0f66ef61a9ef168b52ceb70699 of the develop branch. Documentation and tests have also been updated. 
To test `index` cycle subset by character:

```R
library(argoFloats)
data(index)
index2 <- subset(index, cycle="1")
index2[["cycle"]]
```
```R
[1] "001" "001" "001" "001" "001" "001"
```
To test `index` cycle subset by integer:
```R
index3 <- subset(index, cycle=1:5)
index3[["cycle"]]
```
```R
 [1] "003" "004" "005" "001" "002" "003" "001" "002" "001" "002" "001"
[12] "002" "002" "003" "004" "005" "001" "002" "004" "005" "001" "002"
[23] "004" "005" "002" "003" "004" "005"
```
To test `argos` cycle subset by character:
```R
library(argoFloats)
data(index)
subset <- subset(index, 1:10)
argos <- readProfiles(getProfiles(subset))
argos2 <- subset(argos, cycle="124")
argos2[["cycle"]]
```
```R
[1] "124"
```
and, to test `argos` cycle by integer:
```R
argos3 <- subset(argos, cycle=124:126)
argos3[["cycle"]]
```
```R
[1] "124" "125" "126"
```

**Comment by dankelley** [comment]
I'm a bit mixed up, wrt `vim +93 tests/testthat/test_subset.R`

Maybe a Z?

**Comment by j-harbin** [comment]
This was tweaked in a Z with @dankelley, I therefore know he agrees this is complete and I will close the issue.
