### ISSUE TITLE
index[["time"]] should give the time

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#305]
Right now, `index[["date"]]` works, which is fine because that is what the servers call the time, but I do not think users will guess that.  The entries are times, after all, not dates.

I thought we had this already, but I just noticed that we do not, and I just don't like the line from our paper, reproduced below, which suggests to users that `"date"` is a sensible name for a date-time object.  (Of course, they can still get it from `[["date"]]` if they want to.)

Since this will not break existing code, and since I want it for edits of our in-prep paper, I will go ahead and add this without waiting for a vote.

<img width="614" alt="Screen Shot 2020-11-15 at 1 45 51 PM" src="https://user-images.githubusercontent.com/99469/99192381-e949f980-2748-11eb-8c4b-f884009efcfc.png">

**Comment by dankelley** [comment]
Closing, since this is done in "develop" commit 0297196e855c0419aa7ade6b5d9ba52c6c65450c

**Comment by richardsc** [comment]
I thought this when I was reading the paper too, but must have forgot to comment on it ...
