### ISSUE TITLE
Change subset by column to subset by profile

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#310]
As discussed in https://github.com/ArgoCanada/argoFloats/issues/208, we now know that what we have been referring to as `column` for subset, is actually a `profile`. I will be making this change when things settle down with the paper, but I wanted to make an issue of it now so I didn't forget.

**Comment by j-harbin** [comment]
Done in commit 909d6c90204e09e4e45d176a0f4ef2780773ef92 of the develop branch.

**Comment by dankelley** [comment]
Did you push the commit?  (Or did you maybe mean in the paper repo?)

The most recent commit I see is ebaf835876b42a7418f2834eecd28f04c90c8906

**Comment by j-harbin** [comment]
Whoops! I'm bad for "committing" and not "pushing". You should see commit 909d6c90204e09e4e45d176a0f4ef2780773ef92 now :)

**Comment by dankelley** [comment]
I get a check failure locally, although the action says that 'R CMD CHECK' worked.
```R
E  Running ‘testthat.R’ [63s/156s] (2m 35.7s)
   Running the tests in ‘tests/testthat.R’ failed.
   Last 13 lines of output:
     ── Skip (test_plot.R:9:1): plot map ────────────────────────────────────────────
     Reason: empty test
     
     ── Failure (test_subset.R:119:19): subset by profile ───────────────────────────
     `getIndex()` produced messages.
     
     ── Skipped tests  ──────────────────────────────────────────────────────────────
     ● empty test (1)
     
     ══ testthat results  ═══════════════════════════════════════════════════════════
     Failure (test_subset.R:119:19): subset by profile
     
     [ FAIL 1 | WARN 0 | SKIP 1 | PASS 221 ]
     Error: Test failures
     Execution halted
```

**Comment by dankelley** [comment]
That error is because we are demanding silence from the `getIndex()` call. It will not be silent if a new download takes place.

We should only demand success.  Can you change that, @j-harbin?

PS. I'll be offline for 2 hours.

**Comment by j-harbin** [comment]
the `expect_silence()` is removed in commit 767cf623527eaa2541230aba0f1ac98f71276758 of develop branch
