### ISSUE TITLE
Subset by multiple IDs

### ISSUE THREAD

**Issue by anna-schrecengost** [ArgoCanada/argoFloats#321]
Hi again, I'm just wondering if there is a way to `subset()` by multiple IDs at once, so that they are all contained in the same index. Thank you!

**Comment by j-harbin** [comment]
Hi @anna-schrecengost,

As of right now, there is no option to subset by multiple IDs (however, I can code that in). In the meantime, what you can do is use the `merge` function to combine indices.

For example,

```
library(argoFloats)
ai <- getIndex()
index1 <- subset(ai, ID="13857")
index2 <- subset(ai, ID="15854")
index3 <- merge(index1, index2)
plot(index3)
```

I hope this helps!

**Comment by j-harbin** [comment]
Hi @anna-schrecengost ,

Just a FYI, in commit abbf10d72921255cb64cc822b56930081089bfb8 of the develop branch, I've added the option to subset by multiple IDs. You can now do, for example,

```R
library(argoFloats)
ai <- getIndex()
index1 <- subset(ai, ID=c("13857", "15854"))
plot(index1)
```

Hope this helped!
