### ISSUE TITLE
Update vignette to include details of Argo and section data

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#322]
I will be updating the vignette to include details of Argo and section data. This was based off of discussions in https://github.com/ArgoCanada/argoFloats/issues/313.

**Comment by j-harbin** [comment]
Hi Team,

This has been completed in commit efe241bc1e391222470c10ceab90dea5f9a56eca of the develop branch. I am going to keep it open and go over it tomorrow when my brain isn't so foggy.

Alongside this change I also updated the vignette with the following as it was a little bit outdated:

1. Stating we use the Ifremer server first, then the USGODAE
2.  Changing "Argos" to "Argo profiling floats" throughout the vignette to avoid confusion with communication system
3. Fixed typos
4. Changed code for readProfiles.R plot. It was not using the "new" plot profile function, and was instead extracting `pressure` and `temperature` and plotting it that way.
5. Updated exercises

I'd like to mention that there is lots that can be said about section data and the comparison of CTD ship based section data vs. Argo sampling. I think it may be worth having a discussion if we'd like to have a vignette specific to section data.

**Comment by dankelley** [comment]
I think small vignettes are great, and so there ought to be a new one specifically for pseudo-section data, and later maybe one for pseudo-station data.  Other things could come to mind, too.  J has seen the pseudo-section dataset I used in a class assignment, for example.

**Comment by j-harbin** [comment]
As per the title, this issue has been complete. Perhaps I will create another issue about creating a section vignette.
