### ISSUE TITLE
switch mapApp date field to use dateInput()

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#340]
@j-harbin, I think the dates in `mapApp()` ought to be done with `dateInput()`.  This will avoid errors made by users who don't know that the proper way to specify dates is yyyy-mm-dd (not the crazy US style).  Also, it's pretty convenient, and does not require knowing the number of days in each month.

You might want to try it.  Only a few lines will need to be changed.  I vote +1 on the suggestion to switch to `dateInput()`, where -1 means "as is".

**Comment by j-harbin** [comment]
This is completed in commit fe3a60144a4d30380ebe1f4125601f124de665c0 of the develop branch. I'm not sure why it took me almost a month to do ~ 15 seconds of work! If you're happy with these changes please feel free to close this issue

**Comment by dankelley** [comment]
@j-harbin can you move the time and arrows blocks to the top line, please?  As you know, I am always in favour of views that do not require scrolling, and the loss of this line means I have to scroll to see the plot.  As the screen shot illustrates, we have a lot of space in the GUI (blue) area to spare, so it should be possible to reduce the height used by that box.

<img width="1264" alt="Screen Shot 2021-01-13 at 2 31 05 PM" src="https://user-images.githubusercontent.com/99469/104494035-4a0c7b80-55ac-11eb-8028-6c2087ac08ba.png">

**Comment by j-harbin** [comment]
I tried this earlier. It's interesting, on my laptop I have a lot less "blue" space. If you look in issue340, commit 44f7a0f9f888294eab056c4d75489ec82e915bcf, you'll notice that I can't fit both "End" and "Start" on the same line.

![Screen Shot 2021-01-14 at 8 08 23 AM](https://user-images.githubusercontent.com/58750538/104589099-c3a17980-563f-11eb-8f98-0424083be710.png)

**Comment by j-harbin** [comment]
Closed per Zoom meeting with D.

**Comment by dankelley** [comment]
@j-harbin this is **such** a great addition!  It only takes using it for a few moments to realize how helpful it is.  Thanks!!
