### ISSUE TITLE
Update mapApp()

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#348]
* [x] Put "path" option on Main Tab
* [x] When mouse is held over "Start" or "End" time have a YYYY-MM-DD popup to indicate format (I added dateInput() instead)
* [x] Reword "Select the action..." in the path tab
* [x] Fit float ID on one line
* [x] Make core dots smaller (ie. ~ 2/3 the size)
* [x] Potentially remove "View" word on Main tab
* [x] Float info only showing up on Trajectory Tab (put on Main)
* [x] Change size of Deep/ BCG Argo to be the same as Core
* [x] Add bg option in Settings (conditional if pch=21)
* [x] Make row for symbol and row for path settings
* [x] Document "p" keystroke
* [x] Add contour tick mark (remove keystroke) + document
* [x] get "info" to be on two lines (not necessary anymore with change of formatting)

**Comment by dankelley** [comment]
Another thing to check: make sure that the float-info box (which appears only when the mouse is sufficiently near a float position) is on the same line as the other things, the way it used to be.  At the moment (on some branch) this is not the case, and so when the user moves the mouse around, so it is sometimes near a float and sometimes not, the plot jumps up and down on the page.  I think this will be fixed in the updates to sizes, but please check on it.  Ta.

**Comment by j-harbin** [comment]
Reopening this issue with a new checklist:
* [ ] Float info only showing up on Trajectory Tab (put on Main)
* [ ] Change size of Deep/ BCG Argo to be the same as Core
* [ ] Add bg option in Settings (conditional if pch=21)
* [ ] Make row for symbol and row for path settings

**Comment by dankelley** [comment]
Suggestion: edit this checklist into the first comment, because then when you get an overview of issues, you'll see that this is 6/10-th done.  This helps, in case you would like to use that top-level listing of issues as to-do list.

**Comment by dankelley** [comment]
@j-harbin I fixed up 'Float info only showing up on Trajectory Tab (put on Main)' because I needed that in my work and didn't want to wait until the next working day.  I ticked the item in the top comment, to indicate this, but I'm making this comment so you'll know that this has been done.

**Comment by j-harbin** [comment]
Closing this issue until further updates are needed.
