### ISSUE TITLE
default colours

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#349]
@j-harbin I think the green in `mapApp()` is too "bright".  It is from the old palette.  R has changed the palette, so now `col=3` gives as in the first block below.  The second block contrasts this colour with the green we have now.

Do you agree that this default green is too "bright"?  If so, perhaps change it from `"green"` to `"#61D04F"`.  (You could also change it to `palette()[3]` but then if R changes the palette, this will change also.  I really don't think they will change the palette much in the next decade though...)

Possibly the purple should be replaced also.  I suppose `palette()[6]` might be a good one.

Anyway, up to you, of course!  I've assigned it to you, to do, or reject.

``` r
palette()[3]
#> [1] "#61D04F"
```

<sup>Created on 2021-01-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

``` r
x<-1:10
y<-rnorm(x)
plot(x,y,col="green",type="o",pch=20)
lines(x+0.5,y+0.1,col=palette()[3],type="o",pch=20)
```

![](https://i.imgur.com/QSaUQEf.png)

<sup>Created on 2021-01-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

``` r
plot(0:8,col=palette()[1:9],pch=20,cex=2)
```

![](https://i.imgur.com/1jnJpGE.png)

<sup>Created on 2021-01-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dankelley** [comment]
Hm, looking at that last plot, I wonder if we should have
* core col=7 (that beautiful amber)
* bgc col=3 (green -- makes sense for biology)
* deep col=6 ("deep purple" is well-known to those of a certain age ... see e.g. https://www.youtube.com/watch?v=eu5lv2Umn3M)

**Comment by j-harbin** [comment]
This is completed in commit 8c2a22a7e5edb099ae99034be57adf99526f30cc of the develop branch. Feel free to take a look and close this issue is you are satisfied :)

**Comment by dankelley** [comment]
Thanks
