### ISSUE TITLE
Error in -min(bathy) : invalid argument to unary operator

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#351]
``` r
library(argoFloats)
data("index")
plot(index)
#> Error in -min(bathy): invalid argument to unary operator
```

<sup>Created on 2021-01-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dankelley** [comment]
Thanks.  I'll fix this something this afternoon. It's a remnant from the switch to `oce::download.topo()`.  See also to #350.

**Comment by dankelley** [comment]
I think this works now in "develop" commit 490a2ffb0ccf65e8813adedd3abad165b8bb79a0, as illustrated below.  @j-harbin can you check this?  (**Note:** please also update your local `oce`, before updating `argoFloats`. I want to be sure we're using similar machines.  If you get an error about `rgdal` not being available, please install that package first.)

``` r
library(argoFloats)
debug <- 0 # set to e.g. 3 to debug
data("index")
par(mar=c(3,3,1,2))
plot(index, debug=debug)
```

![](https://i.imgur.com/HFInDAM.png)

<sup>Created on 2021-01-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by j-harbin** [comment]
I can confirm this works, thanks! I'll close this issue.
