### ISSUE TITLE
mapApp() request: a way to log float ID/cycle data

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#359]
In my work with `mapApp()`, I often want take note of a particular float ID and cycle, for the purpose of later investigation.  It is tiresome to write things down or to copy-paste from the GUI into a separate file, and so I just added a way to log ID/cycle info.

The way it works is that the user puts the mouse near a float location (close enough that the float ID and cycle appear in the info box above the plot) and then strikes the '0' key.  Then, `mapApp()` appends the ID/cycle into a local file called `"log.dat"`.

Obviously, this is no good for a server application, in which writing local files is unadvised and likely not permitted by the webserver.  That's why this is a hidden feature that is not documented by `mapApp()`.

I intend to use this for a while to see if it's useful enough to get a better interface.  It is helpful to me, so far.

The purpose of this issue is to let other developers know that I "claim" the "0" key ... please do not assign that for any purpose of your own, without some discussion.  (I thought of making this action respond to the "l" key, but decided it was too provisional to use up a letter, and I like the idea that the numeric keys can be sandboxes, e.g. @j-harbin could "own" key "1".)

I'll leave this issue open for a while.

**Comment by j-harbin** [comment]
I like the idea of this a lot. I also find myself continuously writing float numbers on scrap paper. My question is, when I am developing argoFloats I work in the top directory of argoFloats (ie. in my case Github/argoFloats). If I type "0" in `mapApp()` and it saves the log.dat to my local file, will I be required to delete the log.dat each time before I commit or push anything to the argoFloats repo?

**Comment by dankelley** [comment]
There's no need to delete, since it's named in the git-ignore file:
```
➜  argoFloats git:(develop) grep  log.dat .gitignore
log.dat
```
I don't quite like this way of working in the long term, because it won't work well on a server. The better way is to create the data within the app, and then to display the results in the GUI, with e.g. `shiny::textOutput()`.  I think it's smartest to put those results after the plot, because otherwise every line that gets added might make the plot scroll down the page.

We could maybe have a zoom call to figure out details of other things.  In my work, I'm also finding it would be great for `mapApp()` to have a way to select by polygon ... the 'show code' would then be very useful as a first step in some pretty sophisticated work.

**Comment by j-harbin** [comment]
This has been completed in commit 0e4ef17467fcf3fe53b196fa77fc9356341f6808 of the develop branch. As discussed in a Z with DK, I will close this issue.
