### ISSUE TITLE
mapApp(): GUI elements should be revealed only when data have been read

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#360]
It's confusing, to see those GUI elements whilst the data are being loaded.  It's easy to hide them using `uiOutput`, so I'll do that.

**Comment by dankelley** [comment]
I've done this in "develop" commit f686117daa7be4dc7ed95a6fb004e4ece75b59ca.  My main reason for making this issue is so that @j-harbin will get an email about it, with this link that will provide a lesson on how to convert from the `conditionalPanel` method to the `uiOutput` method.  I prefer the `uiOutput` method anyway, because it seems clearer (e.g. you can write `input$something` instead of `input.something` in a test) and I think it's much more flexible, because your condition can be *anything* that you can calculate in R based on your data, etc., as opposed to javascript expressions that use those limited things (like `input`) that are shared from R to javascript.

I propose that @j-harbin have a go, next week, with hiding the other elements of the GUI until data become available.  I think it would be nice to just show the app name and version number until the data have been read in.

**Comment by j-harbin** [comment]
+1 to this. I'll have a look at this code. Thanks

**Comment by dankelley** [comment]
This has been partially working for a while.  Some elements still show up before the data have been read in.  I've removed my name from the assignee list, since I've coded in a start to this, and I'm happy to have @j-harbin continue with it, if desired.

**Comment by j-harbin** [comment]
I've completed this in commit 29da759761983946eee233a11817564f45cb87cd and commit 06a80bbe907037d9d0f806845b0006d319fb05d0 of the develop branch. Dan, since you are the creator of this issue, feel free to have a look and close the issue if you see fit!

**Comment by dankelley** [comment]
I see the menus before any data are available.  It would be nice not to. 😺 


<img width="302" alt="Screen Shot 2021-02-01 at 10 07 57 AM" src="https://user-images.githubusercontent.com/99469/106469231-6c8c0900-6475-11eb-8763-f9774847de2e.png">

**Comment by j-harbin** [comment]
I thought this too, however, the problem is that **alot** of code (widgets, plots, etc.) depend on which tab is selected. When we remove the tabs until after getIndex, we receive a continuous error "missing value where TRUE/FALSE needed" in multiple spots. For that reason, for me the work wasn't worth the gain.

Also, you'll notice that in Settings, if you click on "Core", "BGC", or "Deep", the user still has options for symbol type. This is because when we are actually getting the index and plotting it, the plot depends on the input from the "Settings" tab. That means, if we remove the Settings tab until after we get index, we receive an error.

Thoughts?

**Comment by dankelley** [comment]
Can you quote a file/line where something depends on the tab?  Possibly I can see a fix.

This is not a huge problem, but if I can see an easy fix, it might help.  I certainly would not want to keep this issue open if the final steps turn out to be hard.

As dogfooding is a "thing", so two is "cost:benefit analysis".  Not to put things in quotes, of "course". 😜

**Comment by j-harbin** [comment]
Line 45-66, for example, where the "core" widgets for settings are conditional on tab 3 and 4 being selected. Without having the core widgets, however, the plot is not possible as the colour points, symbol types, etc. depend on those widgets.

![Screen Shot 2021-02-01 at 10 56 32 AM](https://user-images.githubusercontent.com/58750538/106475465-55044e80-647c-11eb-852b-d8e6bdca78e6.png)


I think the bigger problem here is some of the code uses the `conditionalPanel()` approach, and some uses the `renderUI` approach.

**Comment by dankelley** [comment]
Right.  There are tricks with `conditionalPanel()`, which I could probably find in some old code, but I gave up on that a long time ago, in favour of `renderUI`.  I'll take a look this aft, but likely I'll just close the issue -- not a big deal for now.

**Comment by dankelley** [comment]
I'll close this, on the basis that it's not of high enough priority to complete the final step at this time, given the nature of the code and other priorities.  Thanks!
