### ISSUE TITLE
length(index1[["file"]] and length(index1[["index"]]) not equal?

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#361]
In the following code:

```R
library(argoFloats)
data("index")
index1 <- subset(index, 1:10)
length(index1[["file"]])
length(index1[["index"]])
```

I would expect `length(index1[["index"]])` to be equal to 10 since I subset for the first 10 cycles, but instead it is 8. Interestingly, `length(index1[["file"]])` is equal to 10. Any thoughts on this?

**Comment by dankelley** [comment]
That's because `[["index"]]` returns a data frame, not a vector, e.g.
```R
> class(index1[['index']])
[1] "data.frame"
> dim(index1[['index']])
[1] 10  8
> nrow(index1[['index']])
[1] 10
> ncol(index1[['index']])
[1] 8
```

Notice that `length()` is equal to the number of columns in the data frame.

**Comment by j-harbin** [comment]
Ah yes! Thanks, Dan.
