### ISSUE TITLE
topography downloads are failing

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#368]
I get errors with `oce::download.topo()` calls this morning, with the key report as follows. 

Whether this is a problem with argoFloats, oce, or the server, I don't know yet.  I kind of think it's the server, because we've had troubles before. Sometimes the problems are technical, other times they are governmental (e.g., amazingly, lots of US sites freeze during a government lockdown).  Maybe one of Biden's executive orders was to rename NOAA ... joke.

```
    download.topo(west=-65.3, east=-64.1, south=31.6, north=33, resolution=1, destdir='., server='https://gis.ngdc.noaa.gov')
      destination='./topo_65.3W_64.1W_31.6N_33.01N_1min.nc'
      querying "https://gis.ngdc.noaa.gov/arcgis/rest/services/DEM_mosaics/ETOPO1_bedrock/ImageServer/exportImage?bbox=-65.3,31.6,-64.1,33.01&bboxSR=4326&size=72,84&imageSR=4326&format=tiff&pixelType=S16&interpolation=+RSP_NearestNeighbor&compression=LZW&f=image"
Error in .local(.Object, ...) : 
  An error occurred while creating a virtual connection to the DAP server:Error while reading the URL: https://gis.ngdc.noaa.gov/arcgis/rest/services/DEM_mosaics/ETOPO1_bedrock/ImageServer/exportImage.ver.
The OPeNDAP server returned the following message:
Not Found: The data source or server could not be found.
        Often this means that the OPeNDAP server is missing or needs attention.
        Please contact the server administrator.

Error in .rasterObjectFromFile(x, band = band, objecttype = "RasterLayer",  : 
  Cannot create a RasterLayer object from this file. (file does not exist)
Error in topo[["z"]] : subscript out of bounds
```

**Comment by dankelley** [comment]
I'll make `plot,argoFloats-method(..., which="map")` immune to server failures.  We should get a map without topography, instead of an error message.

**Comment by j-harbin** [comment]
@dankelley is this solved now?

**Comment by dankelley** [comment]
I'm good at making issue and ok at addressing them, but pretty bad at closing them!

Yup.

Done.

Closing.
