### ISSUE TITLE
mapApp() bgc should be a brighter green

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#370]
As you can see in the snapshot, the bgc dots are a bit hard to see against the topography.  I'll try brightening them a bit.  (I know, I know, I'm the one who asked that they be darkened, recently ... so I'll just brighten them a little.)

<img width="649" alt="Screen Shot 2021-01-21 at 10 57 27 AM" src="https://user-images.githubusercontent.com/99469/105368037-7ab96a00-5bd7-11eb-9ddc-d256a331989a.png">

**Comment by dankelley** [comment]
Here's a variant, with bgc changed from `4` to `"#05f076"`.  I'm uploading it to see if I can tell the difference in this small size (which mimics the size of a figure in a paper, I think)

<img width="1022" alt="Screen Shot 2021-01-21 at 11 14 24 AM" src="https://user-images.githubusercontent.com/99469/105370468-ff0cec80-5bd9-11eb-977f-f5d5549f6173.png">

**Comment by dankelley** [comment]
I think this new one is better.  Looking at this issue on the website (to get an update to the second snapshot), I think the bgc dots seem more visible.

Note that line 6 of `R/mapApp.R` sets the default colours.  (You can access these as the 'default' value for the pulldown menus in the 'settings' tab.)

I'm going to leave this open until 1000h tomorrow (Jan 22) in case @j-harbin wants to weigh in on the colours.

**Comment by j-harbin** [comment]
+1 for the new green, it has an extra "pop".

**Comment by dankelley** [comment]
Thanks!
