### ISSUE TITLE
Make border selectInput be on same line as other symbol settings

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#377]
Hi @paleolimbot,

I have a similar request as https://github.com/ArgoCanada/argoFloats/issues/375. I currently added a conditional `selectInput` to specify the border colour if pch=21 in the Settings tab for Core, BGC, and Deep. When pch=21 is not selected the tab looks as follows:

![Screen Shot 2021-01-27 at 2 02 02 PM](https://user-images.githubusercontent.com/58750538/106033842-8bbb1d00-60a8-11eb-8208-807db9abf817.png)

However, when pch=21 and the conditional border `selectInput` appears, it goes to a new line as follows:

![Screen Shot 2021-01-27 at 2 02 16 PM](https://user-images.githubusercontent.com/58750538/106033920-a5f4fb00-60a8-11eb-816c-0e979437042f.png)

Do you know of a way to get the Border `selectInput` to show up on the same line as the other symbol settings? Please feel free to make any changes you see fit!

Thanks!

**Comment by j-harbin** [comment]
Hey Dewey!

I used the skills you taught me in #375 and Dan directed me to the column argument, so I figured I would tackle this. It is done in commit 27cc8423e7a7a369c3cec6dad31472932c6b912b of the develop branch and it looks like the following:

![Screen Shot 2021-02-01 at 2 26 26 PM](https://user-images.githubusercontent.com/58750538/106501689-d1f1f100-6499-11eb-993f-3aa5fb8ad150.png)

Thanks for the help everyone :)

**Comment by dankelley** [comment]
Not that I'm a picky, but does anyone else find it bothersome that the "default" word has a triangle on top?  Oh, those pesky triangles, always climbing on top, trying to be the king/queen of the castle.
