### ISSUE TITLE
Name for new QC app?

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#381]
Creating this issue as a place for us to discuss a name for the new QC app.

My suggestion is `QCApp()`. It'm simple and is similar to `mapApp()`.

**Comment by dankelley** [comment]
I agree. That's an ideal name.  Let's use the -1 to +1 voting convention, where +1 means "I agree" and -1 means "I do not agree", 0 means "let others decide" and numbers can be non-integral.  This way, the decision is made by the sign of the sum.

**DEK VOTE:** +1

**Comment by cgrdn** [comment]
+1 `QCApp()` is perfect. Style wise I kind of like the look of `qcApp()` but I understand the caps given its an acronym.

**Comment by richardsc** [comment]
+1 for the characters, but I think I agree with @cgrdn that `qcApp()` seems more consistent.

Sorry I missed the meeting today ... based on the new repo it sounds like it might be a good idea to have another meeting *just* for me to get me caught up (probably not until next week though ...) 😄

**Comment by j-harbin** [comment]
Good point. I also give +1! `qcApp()` it is. I'll close this issue and get to work on this now!
