### ISSUE TITLE
Create qcApp()

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#382]
Creating this as a place to keep track of my progress.

**Comment by j-harbin** [comment]
Note: This is being working on in branch issue382

**Comment by dankelley** [comment]
I'm happy to Z sometime, to "story-board" the interface or talk about things a person might want to do.  I walked down similar roads for the glider-QC app (and along some roads that got nowhere).

**Comment by j-harbin** [comment]
I think that would be quite useful, Dan. Maybe we'll plan for Monday? In branch issue382 commit a6ae66569b96ada89167f7a3d75d01d203c22b3d you'll see I added `qcApp()`, but am currently just focusing on adding widgets (this is based off of the photo I presented in the meeting yesterday, which was inspired from your `oceanglider` QC app).

**Comment by dankelley** [comment]
Sounds good.  Maybe you can get in touch on Monday. Thanks!

**Comment by j-harbin** [comment]
To do:

* [ ] Add "Load" button that reads profiles from the index rda (relevant code = `load("mapApp_20210208T1302.rda")`)
* [ ] Make widgets work
* [ ] Make only one tab with conditional widgets (showQCTests, Diagnostics) if "single float" is selected
* [ ] Make "Undo" button
* [ ] Make plot par depend on # of plots selected (look at `whalestrike` package)
