### ISSUE TITLE
Add "Save" button to mapApp()

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#383]
As discussed in a vftf, the "Save" button will save an subset of index into an rda.

The relevant code for this is as follows:

```R
rda <- paste0("mapApp_", format(Sys.time(), format="%Y%m%dT%H%m", tz="UTC"), ".rda")
save(A, file=rda)
```

This will allow me to add a "Load" button to `qcApp()` to look at a subset of profiles.

**Comment by j-harbin** [comment]
Done in commit 081814cc2c78439f45a4e55626180370cb9d6738 of the develop branch. Currently the "save" button only subsets by `time` and `rectangle`. Should it take into consideration if the user only selects `core`, `BGC`, or `deep`, or weather they select `path`, `contour` etc?

If so, I argue "code" should do the same thing. Currently the "Code" button only takes into consideration `time` and `rectangle` subset.

**Comment by dankelley** [comment]
1. I think "save" should record the index being displayed (core or bgc ... there is no separate index for deep).

2. Similarly, I think "code" should do the same.  (I guess this ought to be its own issue, if you don't mind making one ... issue drift is confusing to observers.)
