### ISSUE TITLE
should we remove the grand-fathering of subset(..., id=...)?

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#385]
As shown below, (a) we said we would remove the `id=` syntax in Dec 2020, but it seems we still permit it, and (b) I cannot remember the convention, despite coding and discussing.

What do you think, @j-harbin?  Should we report an error now?  I think so, actually, because otherwise I don't think I'll get the `ID` syntax into my puny brain unless forced to 😃 

<img width="1074" alt="Screen Shot 2021-02-08 at 12 47 10 PM" src="https://user-images.githubusercontent.com/99469/107252569-dc693900-6a0b-11eb-907e-8923b1460cca.png">

**Comment by j-harbin** [comment]
Yes, I'll make this change.

Do you also recommend changing the "backwards compatibility" of `filename="argo"`?

For example,

```R
library(argoFloats)
ai <- getIndex(filename="argo")
```
produces

```R
Warning in getIndex(filename = "argo") :
  converted filename="argo" to filename="core" for backwards compatibility.
 NOTE: this conversion will cease after 2020-Dec-01.
```

**Comment by dankelley** [comment]
Yes, I recommend that, also.  Basically, if we state an end date, we ought to stick to it, perhaps with a bit of grace period.  In this case, we've given a bit over 2 extra months, and that seems like plenty.

I prefer software that enforces its rules, because I'm bad, and really only pay attention to errors, not warnings.

**Comment by j-harbin** [comment]
Done in commit 72874e83c041f63931e02808d7027fae9bd3cc0a. Feel free to close if you see fit, or offer any further suggestions!

**Comment by dankelley** [comment]
Looks great, thanks!
