### ISSUE TITLE
Start and End time does not match "Code" tab

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#389]
As you see the "Start" and "End" time are 2021-02-07 and 2021-02-09 respectively,

![Screen Shot 2021-02-09 at 9 05 36 AM](https://user-images.githubusercontent.com/58750538/107367945-4ccc9480-6ab6-11eb-9e7e-1c769032ff2e.png)

But the code is showing 

from <- as.POSIXct("2021-02-06", tz="UTC")
to <- as.POSIXct("2021-02-08", tz="UTC")

![Screen Shot 2021-02-09 at 9 08 41 AM](https://user-images.githubusercontent.com/58750538/107368038-6ec61700-6ab6-11eb-8363-7402959f4b65.png)

**Comment by dankelley** [comment]
Who is assigned this issue?  (I propose @j-harbin but I could help since I wrote the original code, and have tweaked it for a similar problem fairly recently.)

**Comment by j-harbin** [comment]
Ah yes, the good ol "format needs a `tz` argument" trick. This is fixed in commit 9b7610bfd177915881908d48cbdb7276d38d6402 of the develop branch.
