### ISSUE TITLE
Code and Save button should incorporate argo type

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#390]
Re Dan's comment in https://github.com/ArgoCanada/argoFloats/issues/383:

"I think "save" should record the index being displayed (core or bgc ... there is no separate index for deep).

Similarly, I think "code" should do the same. (I guess this ought to be its own issue, if you don't mind making one ... issue drift is confusing to observers.)"

I agree. What I was thinking in terms of "deep" was that if the user clicks **only** deep profiles to be shown, then we would subset by `subset(getIndex(filename="synthetic", deep=TRUE)`.

Thoughts?

**Comment by dankelley** [comment]
Oh, I see.  Yes, that makes sense.

**Comment by j-harbin** [comment]
This is solved in commit 09d6d9faea81bf1508a304f048bff50bdbd2a6ed of the develop branch.

**Comment by j-harbin** [comment]
Note: changes were made in commit 47776a08e6a064e5ca835e6d0576a0d83789ddee  of the develop branch, based on CG comments in https://github.com/ArgoCanada/argoFloats/issues regarding synthetic data.
