### ISSUE TITLE
is there something in an Argo netcdf file that makes it distinct?

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#391]
This comes up from the discussion of `qcApp()` but I think it's also more general.  I would like to know if there's something in Argo netCDF files that changes, each time the file is updated.  If so, then we coiuld uniquely identify a cycle by a triplet:
* float ID
* cycle
* this 'thing'

I am thinking it might be `DATE_UPDATE`.  I wonder (and this is to @cgrdn and @j-harbin), is that distinct, in the sense that **any** update to the data on the server **always** causes a modification in this value?

By the way, the following is how this can be determined at the unix commandline.  It could also be determined by using some of the `nc` commandline tools, but I'm working in R, so this is the natural way to figure this out.
```R
➜  argo Rscript -e "ncdf4::ncvar_get(ncdf4::nc_open('SD6901654_417.nc'),'DATE_UPDATE')"
[1] "20201120145322"
```

**Comment by cgrdn** [comment]
I have a feeling `DATE_UPDATE` gets updated upon pushing the file to the DAC, which means the answer would be yes any update would cause it to be modified. Anh would know for sure, I'll send her a message to confirm.

**Comment by dankelley** [comment]
Thanks, Chris.  Also, I hope you don't mind, but I altered the bold-face markup in the issue template for the new QC repo.  (It previously had spaces inside the two-asterisk delimiters.)

**Comment by cgrdn** [comment]
Pasted out teams conversation here, sounds like it is automatic and so would be reliable to identify Argo nc file versions. 

CG: 
> Hi Anh, do you know the answer to Dan's question here?https://github.com/ArgoCanada/argoFloats/issues/391
>
> Basically - does the variable DATE_UPDATE in an Argo file get updated automatically upon pushing the DAC/GDAC or is it the responsibility of the person performing the update to modify that field? Thanks!!

AT:
> Hi Chris.  Technically, if there's any change to the original file, the date update will change.  So for example, if the data file was DMQC, the date update will change.  For DMQC case, there will be another entry for history date.  If the DAC regenerate the file from scratch, or database, the date_update and date_creation will almost the same.  This is our case.

**Comment by j-harbin** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done. Thanks!

PS. This is a standardized reply.

**Comment by j-harbin** [comment]
The answer is at https://github.com/ArgoCanada/argoFloats/issues/391#issuecomment-776133262 so I'll close this.  Sorry for the passing of ages.
