### ISSUE TITLE
Should we have a time-series plot?

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#392]
This question is stemming from the development of `qcApp()`. Currently, we have a `plot(argos, which="profile")`, but we don't actually have anything that is a time series. 

Does `oce` have anything like this?

**Comment by dankelley** [comment]
The question is what ought to go on which axis.  We can z if you like.

**Comment by j-harbin** [comment]
This belongs in user space, until a user requests a feature with detail and an argument vis-a-vis general utility. Sic transit gloria Mundi. -- DEK
