### ISSUE TITLE
mapApp() code chunk should have `TSControl=` NOT `TScontrol=`

### ISSUE THREAD

**Issue by richardsc** [ArgoCanada/argoFloats#398]
A simple typo, found when I uncommented the `if (FALSE)` block from the code copied out of `mapApp()`:
```r
plot(applyQC(argos), which="TS", TScontrol=list(colByCycle=1:8))
Warning messages:
1: In plot.window(...) : "TScontrol" is not a graphical parameter
2: In plot.xy(xy, type, ...) : "TScontrol" is not a graphical parameter
3: In axis(side = side, at = at, labels = labels, ...) :
  "TScontrol" is not a graphical parameter
4: In axis(side = side, at = at, labels = labels, ...) :
  "TScontrol" is not a graphical parameter
5: In box(...) : "TScontrol" is not a graphical parameter
6: In title(...) : "TScontrol" is not a graphical parameter
7: In plot.xy(xy.coords(x, y), type = type, ...) :
  "TScontrol" is not a graphical parameter
```

which can be fixed by capitalizing the "C" in "TSControl". 😄

**Comment by dankelley** [comment]
Happy Valentine's Day 💋

**Comment by richardsc** [comment]
Fixed in b867ed3948

**Comment by richardsc** [comment]
I know it took me longer to type the issue than to go and fix it, but I was in the middle of something else at the time, and was expecting a 2.5 year old to wake up from a nap any minute, and knew that if I started fixing it then I'd get distracted and would then forget about it .... so I opened the issue just to be safe 😄 

And happy Valentine's Day to you @dankelley (it's a heart, see?)
![image](https://user-images.githubusercontent.com/233584/107887445-95cc8080-6edc-11eb-8cdd-e6336c8cea58.png)

**Comment by dankelley** [comment]
``` r
library(argoFloats)
library(oce)
#> Loading required package: gsw
#> Loading required package: testthat
#> Loading required package: sf
#> Linking to GEOS 3.8.1, GDAL 3.1.4, PROJ 6.3.1
data(coastlineWorld, package="oce")
mapPlot(coastlineWorld, projection="+proj=bonne +lat_1=90", col="red", drawBox=FALSE)
s <- subset(getIndex(), time=list(from=Sys.Date()-10, to=Sys.Date()))
#> Kept 4277 profiles (0.177%)
mapPoints(s[["longitude"]], s[["latitude"]], col="red", pch=20, cex=2/3)
```

![](https://i.imgur.com/MDK1TPJ.png)

<sup>Created on 2021-02-14 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
