### ISSUE TITLE
"deep" profiles not capturing "bgc" deep profiles in mapApp()

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#405]
When working on https://github.com/ArgoCanada/argoFloats/issues/390 I noticed that when "deep" is chosen, we look in the `profiler_type` in `I<-getIndex()` (See lines 134-156 in `R/mapApp.R`). This is problematic, because `deep` profiles exist within `bgc` Argo as well. See the `reprex` below:

``` r
library(argoFloats)
bai <- getIndex(filename="bgc")
subset1 <- subset(bai, deep=TRUE)
#> Kept 730 profiles (0.317%)
```

<sup>Created on 2021-02-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I propose we make "deep" profiles look in `sai <- getIndex(filename="synthetic")` to capture both core and bgc, deep profiles.

Dan, do you agree with this? If so, I'll make the change.

**Comment by dankelley** [comment]
I'll defer to you to make the decision.  I'm not actually very clear about the distinction between `bgc` and `synthetic` (e.g. does the `synthetic` dataset contain every single `bgc` profile, and no non-`bgc` profiles?)

I feel that you'll make a good decision on this, so I say "go for it" and if problems develop, then they can be dealt with.

<details><summary>More information</summary>

``` r
cat("Nice reprex")
#> Nice reprex
```

<sup>Created on 2021-02-19 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by j-harbin** [comment]
Hm, I am going to read into this. I was under the impression that `synthetic` was a combination of `core` and `bgc`.

However (see reprex below)
``` r
library(argoFloats)
ai <- getIndex() #Core
bai <- getIndex(filename="bgc") # BGC
sai <- getIndex(filename="synthetic") #synthetic
ai
#> argoFloats object of type "index" with 2413580 items
bai
#> argoFloats object of type "index" with 230234 items
sai
#> argoFloats object of type "index" with 215309 items
```

<sup>Created on 2021-02-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Where there are much more "core" than "synthetic". I'll look into this..

**Comment by dankelley** [comment]
Do you mean
> more "bgc" than "synthetic"

?

**Comment by richardsc** [comment]
@cgrdn knows lots about the details of synthetic profiles ....

**Comment by cgrdn** [comment]
Only BGC floats get synthetic profiles, and the BGC data in the S (synthetic) files should be exactly the same as the BGC data in the B files. The synthetic files also contain T and S data, but potentially a subset (or in rare cases, extension I suppose? If N_LEVEL of the B files is greater than N_LEVEL of the core file) of the T and S data found in the core files, as the nearest measurement is taken to match the resolution of the BGC variables. 

Re: deep Argo, because it doesn't have its own standalone index yet, I think you'll have to use a combination of the core and bgc index files to properly find them all.

**Comment by cgrdn** [comment]
Re: there being more bgc than synthetic files, I imagine that is a product of some additional processing having to go into making synthetic files, so the most recent BR files may not have corresponding SR's yet.

**Comment by j-harbin** [comment]
Thanks for this, Chris. That makes a lot more sense.

I'll take the approach of combining both "core" and "bgc". The below `reprex` shows the significance of not only using `core` data:

``` r
 library(argoFloats)
    ai <- getIndex()
    bai <- getIndex("bgc")
    merge <- merge(ai, bai)
    d <- subset(ai, deep=TRUE)
#> Kept 11330 profiles (0.469%)
    deep <- subset(merge, deep=TRUE)
#> Kept 12061 profiles (0.456%)
```

<sup>Created on 2021-02-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dankelley** [comment]
@j-harbin I wonder where we are on this issue?  I see that I'm assigned, but that you volunteered to do this, in your initial comment.

I don't mind doing it, but if you're spun-up on this, maybe you can do it?

It's nice to tie up loose threads.

**Comment by j-harbin** [comment]
Hi Dan,

I don't mind doing this issue, however, the reason it hasn't been completed yet, was because if you remember we discovered on one of our many zooms that there was some confusion with the message (which is currently commented out) at line 141 saying "combining "core" and "bgc" data". We discovered this isn't actually what we're doing, and it impacts how we move forward with getting deep data. I wasn't able to quite figure out what was going on, but it may be worth a Z.

**Comment by dankelley** [comment]
I'm not sure where we stand on this.  Want to z on it, @j-harbin?

**Comment by dankelley** [comment]
J and I agree that this is okay.  The key thing is that the "ID" of every member of the BGC set is a member of the "ID" for the core data.  Below is a reprex showing this. (This reprex will become a comment in the code later today.)

``` r
library(argoFloats)
i <- getIndex()
b <- getIndex("bgc")
iid <- i[["ID"]]
bid <- b[["ID"]]
stopifnot(sum(bid %in% iid) == length(bid))
```

<sup>Created on 2021-03-16 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
