### ISSUE TITLE
Create "section" vignette

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#424]
As discussed in a vftf with Dan and Clark, I will be creating a section vignette to highlight the use of the newly developed subset by section (https://github.com/ArgoCanada/argoFloats/issues/397)

**Comment by j-harbin** [comment]
Hi Team,

I'm going to argue against making a special vignette for section data. The reasons are as follows:

1.  In our current vignette we explain and show examples of different subset types. I don't see how this is any different
2. In our current vignette we actually already discuss advantages of Argo section data. This was written a few months ago, so it uses subset by `rectangle` to compare sampling efforts of Argo data vs CTD
3. An example of subset by `rectangle` is already done in the current vignette, and I think it is redundant to have it shown twice, and this is therefore a perfect place to add subset by section

In commit 10e7c6aa4fd4f75f8a8e6159bd07732dc1deabc8 of the develop branch, I therefore tweaked the vignette (some things were out of date) and updated the section where we discuss sampling efforts of Argo vs CTD data to show our new section subset. Of course, if we want further detail on section data (such as changes in temperature over pressure/ latitude etc) I can add those in.

**Comment by dankelley** [comment]
I agree with this.  The only problem is that you've not instituted a vote!

**Proposal:** discuss subset-by-section within existing vignette.
**Voting scheme:** real number between -1 and +1, with -1 meaning to create a new vignette for the topic and +1 meaning to discuss it in the existing vignette.

DK vote: +1.

**Comment by j-harbin** [comment]
Hehehe I really took control there didn't I :)

+1 from JH as well

**Comment by dankelley** [comment]
@j-harbin you ought to add a line to the NEWS.md file to mention that we can now subset by section. Please follow the format of that file, and the terse writing style (we want all items to be just one line long, if possible).
