### ISSUE TITLE
index[["processingLog"]] doesn't work

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#425]
`index[["processingLog"]]` doesn't work, but `index@processingLog` does. I know why this is happening, but will likely get to it tomorrow.

**Comment by dankelley** [comment]
FYI the normal thing to do is to type
```R
summary(i)
```
rather than
```R
i[["processingLog"]]
```
because the first scheme formats the time and comments nicely.  But, as you say, it makes sense for the latter to also give output.

**Comment by j-harbin** [comment]
Done in commit 6a6b6135e39e40efc186a2c4dc43c55cde1410ba of the develop branch.
