### ISSUE TITLE
bump version number?

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#432]
@j-harbin, I think that we ought to bump the version to 0.2.0, the first entry of which will be the subset-by-section that I suggested in another issue.

My goal is that the version active upon the publication of the FMS paper be a "minor" release, not a "subminor" one.  (First digit is "major", second is "minor" and third is "subminor".)

If you agree, @j-harbin, please take care of this.  It's simple: just change `DESCRIPTION` and `NEWS.md` ... I think no other files will need to be changed.

**Comment by j-harbin** [comment]
Done like dinner! ( commit d2010d0abb50055f03776481ab69a3ade65693c3 of develop branch).
