### ISSUE TITLE
Need to create subtype for "argos" type

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#435]
Dan, this is what I was trying to demonstrate on our Zoom call yesterday. You can see the problem in the reprex below, where the subtype should be "trajectories". 

``` r
library(argoFloats)
ai <- getIndex("traj")
argos <- readProfiles(getProfiles(subset(ai,1)))
#> Kept 1 cycles (0.0057%)
#> Warning in FUN(X[[i]], ...): This file has no STATION_PARAMETERS item, so an
#> attempt is made to discover some important fields for inclusion in the data slot
#> of the return value. However, other variabiles will go in the metadata slot, so
#> be aware of this problem during further processing.
argos[['subtype']]
#> [1] "cycles"
```

<sup>Created on 2021-04-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

In read.R line 91 we say ` res <- new("argoFloats", type="argos")`. I was thinking the solution to this was to do:

```R
istraj <- grepl("traj", profiles[["file"]])
res <- new("argoFloats", type="index", subtype=if (istraj) "trajectories" else "cycles").
```

This works great for our typical workflow (ie. getIndex(), subset(), getProfiles(), then readProfiles()). But for the built in data-set when we do the following code it won't work.

```R
library(argoFloats)
raw <- readProfiles(system.file("extdata", "SD5903586_001.nc", package="argoFloats"))
```

**Comment by dankelley** [comment]
Can you state the branch name?  I could download and we could Z, which might make sense.

**Comment by j-harbin** [comment]
Whoops! The branch is issue421. Ready for a Z when you are.

**Comment by dankelley** [comment]
I'll start a zoom at 0840.

**Comment by j-harbin** [comment]
Done in commit 0990827a7f56c71f8909c796851ca83bc32e3473 of the develop branch.
