### ISSUE TITLE
Should we remove summary plot?

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#437]
I'm curious what @dankelley and @richardsc think about this. My reasoning is as follows:

1. We have never used it
2. Dan and I both forgot it existed
3. We never mention it in a paper
4. We never mention it in a vignette
5. We never demonstrate it in any Youtube videos
6. I don't know a practical use for it

**Comment by dankelley** [comment]
I propose deleting it.  Let's vote, with -1 means keep it, +1 means delete it, etc.  If the sum of all our numbers exceeds 0, we keep it.

DK vote: -0.7

**Comment by richardsc** [comment]
I'm further from this that you too, but can I see an example of what you're referring to? It's not just the default `plot()` method I assume.

**Comment by j-harbin** [comment]
An example is as follows:

``` r
library(argoFloats)
data("index")
index1 <- subset(index, ID="1901584")
#> Kept 10 cycles (0.992%)
argos <- readProfiles(getProfiles(index1))
#> Warning in readProfiles(getProfiles(index1)): Of 10 profiles read, 9 have >10% of salinity values with QC flag of 4, signalling bad data.
#>     The indices of the bad profiles are as follows.
#>     1 2 3 4 5 6 7 8 10
#> Warning in readProfiles(getProfiles(index1)): Of 10 profiles read, 9 have >10% of temperature values with QC flag of 4, signalling bad data.
#>     The indices of the bad profiles are as follows.
#>     1 2 3 4 5 6 7 8 10
plot(argos, which="summary")
```

![](https://i.imgur.com/OpEq59e.png)

<sup>Created on 2021-04-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dankelley** [comment]
I hate to say it (and I know I'm contradicting my vote from before) but now I think that plot looks pretty useful.  I'd use it in my own work, to get an idea of the space-time coverage in a region of interest.

New DK vote: +0.3

**Comment by j-harbin** [comment]
Hm, I'm conflicted. I suppose at one point we felt this was necessary, which tells me we should keep it.

JH vote: +0.2

**Comment by j-harbin** [comment]
I'm going to close this issue. We can always revisit it if we feel it's a priority to delete this plot type.
