### ISSUE TITLE
User does not have the option to select nothing for bgc, core, or deep

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#467]
Likely the user would never want to not have either core, bgc, or deep selected. However, this is a bug because if I click off deep, and core, for example, they disappear. If I then click off deep, they won't disappear. The solution to this bug is also the solution for https://github.com/ArgoCanada/argoFloats/issues/463

**Comment by dankelley** [comment]
Um, they might want to have nothing selected.  That could be a way to get a bathy map.  You never know just what cool things users might try :-)

**Comment by j-harbin** [comment]
Fixed in commit 3138fa5c8bf3302af81455bf348d3327289ce9f0 of develop.
