### ISSUE TITLE
mapApp: add pch images

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#480]
I can do this, but want to wait until @j-harbin finalizes the other open `mapApp()` issues, because adding the image will require me to move source around, etc. and that will cause git problems if J is editing `R/mapApp.R`.  Also, once I do that, the `source("R/mapApp.R");mapApp()` procedure will fail; it will be become necessary to do a build/install for each test.

It will only take me 10 minutes to do the change, but I don't want to blindside J with git conflicts.

**Comment by dankelley** [comment]
I thought I took detailed notes when I did this last time but ... if I did, I can't find them :-)

So I'll take some notes here.  First, I had to create `inst/shiny/mapApp` and move the most of `R/mapApp.R` there.  Then I had to remove that stuff from `R/mapApp.R` and add some more things so it finds this `inst` directory and does `runApp()` pointed at it.  I won't bother showing all the steps, because that's what git is for, i.e. those steps will be recorded by git.  However, one thing that really makes me feel a bit silly is that I didn't save the code that created the pch gallery. So, for the record, I'm putting that in `sandbox/dek/15_pch_gallery`.

Nothing I say above relates to the repo *at this moment* because I want to get this all working before I commit.  I figure I'll be done in half an hour, with a **very** provisional version.  The button to show the pch gallery will be in a bad place, and I'm going to ask @j-harbin (who understands the conditional/tab code) to figure out where to put it.

So, more sometime this aft.

**Comment by dankelley** [comment]
I have done this in commit 3abf8d3476a55f10caac4b851006ed64dd279105 of the "develop" branch.  The placement of the button is **very** ugly, and I am going to rely on @j-harbin to find a better position.  I'm including snapshots of that bad position, and of the window that comes up when you click on it.

**(ugly) button position**

<img width="671" alt="Screen Shot 2021-08-13 at 3 01 59 PM" src="https://user-images.githubusercontent.com/99469/129403522-01caee45-afaf-48fe-b25e-325b9d6b19a4.png">

**The popup window**

<img width="449" alt="Screen Shot 2021-08-13 at 3 26 08 PM" src="https://user-images.githubusercontent.com/99469/129403649-66fd4b33-1542-4da5-a524-b715ba531d3d.png">

**Comment by dankelley** [comment]
NOTE to @j-harbin now, `R/mapApp.R` just calls code in `inst/shiny/mapApp/app.R` and so it is **crucial** that further edits to the interface be done in this second location.

Also, note that using `source(R/mapApp.R)` will no longer help.  You must **rebuild** the whole package to test new code.

PS. this note has bold-face because I'm worried about getting into git tangles. Indeed, when I went to push, it freaked out and made me handle a merge conflict, do a "restore" operation, etc.  So, again, please note the first paragraph of this comment.

**Comment by dankelley** [comment]
@j-harbin -- I propose that you alter the location of this new button to your liking, and then close this issue.  Next week is fine for that, of course.

**Comment by dankelley** [comment]
I think we need to keep it there, so R will find it.  If you look at it, you can see that it finds the other directory and tells shiny about it.

The file should now be quite short -- just docs and maybe 10 lines of code.

I could Z if this is not clear.

**Comment by j-harbin** [comment]
Ah, yes! I remember you explaining this on a Z before. I didn't realize that it had already been updated. I consider this issue done. Feel free to close if you agree.

**Comment by dankelley** [comment]
Looks great.  Thanks, Jaimie!
