### ISSUE TITLE
mapApp: should the symbol selector be a slider or a popup menu?

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#484]
I think a popup menu makes sense, because it's an integer quantity.  @j-harbin if you agree, perhaps you could do that change, since you understand the UI code better than I.

**Comment by j-harbin** [comment]
Hi @dankelley,
What is meant by a popup menu? Do you mean like a selectInput (similar to the focus button that I've screen shot?)

![Screen Shot 2021-08-16 at 1 39 15 PM](https://user-images.githubusercontent.com/58750538/129598775-4e3e71f9-7cd2-4364-81ad-db41828d8bd2.png)

**Comment by dankelley** [comment]
Yup.  I call it "popup" because it pops up.  I'm not sure of the right name though.  Possibly, with 25 items, it won't work well ... but it's worth a try, if you think you might like the look of it.  At one point I had figured out how to get the icons to appear by the numbers, but the code for that is a bit fiddly and therefore I don't recommend it.

**Comment by j-harbin** [comment]
To avoid the issue of scrolling for numbers 1:25 for `selectInput`, I instead used `numericInput`, ( see commit commit bf4427967a312d7677cc4e73a4583384fc2b25d9 of develop) which allows the users to either use the arrows to increase or decrease the desired number (with a min of 0, max of 25 - same as before), OR type in the number themselves. I quite like this and didn't know it existed. See screen shot below. If you're happy with this @dankelley, feel free to close this issue :)

![Screen Shot 2021-08-16 at 2 24 42 PM](https://user-images.githubusercontent.com/58750538/129604355-31cc3f70-cb02-44a7-8ba5-732d6df97a12.png)
