### ISSUE TITLE
Reformat "Settings" tab

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#485]
I will be reformatting the Settings tab to have symbol widgets together, and path widgets together.

**Comment by j-harbin** [comment]
Aligning things still kind of confuses me. In commit 69c3aef02af3d994972468c6569b181bb68bf25e of develop, I did the best I could. I wouldn't say it's perfect by any means, but it's better. It's worth nothing that I initially tried making "Symbol Gallery" be on the same line as the other symbol commands, but it looked to crammed.

![Screen Shot 2021-08-17 at 11 54 50 AM](https://user-images.githubusercontent.com/58750538/129749475-017068ec-9a1f-4623-beb6-23b514d935b4.png)

I'll close this issue for now, but of course, anyone can add comments if they see fit.

**Comment by dankelley** [comment]
I think this looks *great!*
