### ISSUE TITLE
Update help docs in mapApp() to better display key strokes

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#489]

**Comment by j-harbin** [comment]
Done in commit ad3cc9009d102cdfac77154ac0b6449f623a597e of develop.

**Comment by dankelley** [comment]
I wonder whether you can make this doc string a bit more self-consistent?  I sometimes see `'(thing)'` and sometimes see `"(thing)"` and I'm not too sure what the difference is. 

Possibly we should use bold-face for keystrokes, like `<b>?</b>` and quotes like `"Single"` for menu items and button names.  If you agree, perhaps do the change and add a comment so I can check.  If you disagree, just reclose this, of course.

**Comment by dankelley** [comment]
Or possibly `*"Single"*` for single items -- that way they see the double quote and they also see italic.

**Comment by dankelley** [comment]
Sorry, I've edited the last two comment in-place.

**Comment by j-harbin** [comment]
Good point on this. I made it such that any tab names and ? for keystroke are bolded and any menu items or button names are in double quotes. (commit 74f53ba06dc5b4f5b688e09fb838dc8d46beae0f of develop). See below. If you're happy with this feel free to close the issue.

![Screen Shot 2021-08-31 at 12 25 43 PM](https://user-images.githubusercontent.com/58750538/131530956-ab679dd4-0b62-4b02-93fd-8f275e365639.png)

**Comment by dankelley** [comment]
Can "holding a message" say a bit more?  Perhaps "holding the contents of the information window steady, retaining the information about the float nearest the mouse".  Actually, I can't figure out how to phrase that clearly.  Maybe you can see a way to make it a bit clearer than "a message"?

**Comment by j-harbin** [comment]
I fixed this up in commit 4ca6b92478d129eacd993829cd183bad87e26e47 of develop. We actually already had a paragraph explaining the hover message, so I just did some rearranging (shown below). Based on the name of this title, this issue is fixed, so I will close it. Please feel free to add any other comments about the help page, though.

![Screen Shot 2021-09-01 at 10 07 26 AM](https://user-images.githubusercontent.com/58750538/131676640-7cc2904c-e26f-4d3c-b734-e79da9a8bba0.png)

**Comment by dankelley** [comment]
Thanks.  I'll have a look to see if any edits come to mind.  I'll be done in 15 minutes.
