### ISSUE TITLE
A list of things to mention for CRAN release meeting with DK

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#495]
* [x] #496
* [x] Vignette (and therefore user website) have Core, Deep, and Biogeochemical capitalized, but `?argoFloats-package` does not
* [x] Vignette (and therefore user website) "Preliminary Setup" not consistent with developer website
* [x] Vignette (and therefore user website) figure name for work flow should be more descriptive (eg. Work flow of the argoFloats package with descriptions on the left and relevant functions on the right)
* [x] Description of built in Argo files not consistent (see below)

![Screen Shot 2021-09-02 at 8 41 44 AM](https://user-images.githubusercontent.com/58750538/131837662-c31dd41c-57f2-4e2d-9be3-9493a266fd13.png)

* [x] Sometimes description of functions are like a title (ie. first letter capitalized) and sometimes it's not (see below)

![Screen Shot 2021-09-02 at 8 45 10 AM](https://user-images.githubusercontent.com/58750538/131837950-904e6e5b-1c2f-4cbd-9377-e4639be11390.png)

* [x] Description of built in Argo files not 100% consistent. For example for D4900785_048.nc it says "This is NetCDF file for delayed-mode data for cycle 48 of Argo float 4900785", but for SD5903586 it says "This is the NetCDF file for cycle 1 of Argo float SD5903586"

**Comment by dankelley** [comment]
Hi J.  I see you assigned both of us, but we don't want git conflicts.  Do you have time to look at these before the meeting at 1PM today, or shall I?

**Comment by j-harbin** [comment]
Hi Dan. I will leave the image problem to you and I will look at the rest.
