### ISSUE TITLE
mapApp() not obeying path-line width setting

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#505]
To reproduce, double-click a float and select "path". Then, if you change the line colour, that works.  But if you change the line width, it stays the same.  (It helps to turn contouring on, because then it's obvious that the linewidth is not changing.)

Any chance you could fix this in "develop", @j-harbin?  That way, I can merge into "developdevelop", where I am fiddling around with things so that my default view lets me see controls plus map.  I think quite a few people might be on small laptops like this, and when I demo the app in class, it's embarrassing to have to scroll up and down when I talk.

**Comment by j-harbin** [comment]
Fixed in commit 7a3fd620856e891175ca7ea97e3b9f39bd389896 of develop. Good catch on this.

**Comment by dankelley** [comment]
Thanks. Closing now.
