### ISSUE TITLE
mapApp() control region too large

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#506]
The default `mapApp()` view is too large for my screen, in the sense that I have to scroll in one direction to use the controls (e.g. to set the time range) and then the other way to see the plot.  I am on a small laptop and I think my default font might be larger than average, but this is a pain.  I can reduce the font a bit and still see it, but if I show this in class and have to say "we have to scroll" or "let me reduce the font first" then `mapApp()` doesn't really advertise itself.

In the "developdevelop" branch I have been fiddling with
1. CSS modifications
2. The plot margins and
3. the plot width
 
to tighten the GUI space at the top.  My feeling is that it is better than the "develop" branch, but I don't want to merge it in until @j-harbin has a look.  So, @j-harbin, can you try "developdevelop" and write below whether you think it's OK for me to merge it in?  (I am asking this because I don't want to merge it in, given that we might both be editing the same line of code and get a git conflict.)

**The develop view (observe the map cutoff)**

<img width="1022" alt="mapapp-develop" src="https://user-images.githubusercontent.com/99469/134669171-599e06b7-d3aa-4c81-9dea-925b9447d2fa.png">

**The developdevelop view (we see the controls plus the whole map)**

<img width="1022" alt="mapapp-developdevelop" src="https://user-images.githubusercontent.com/99469/134669190-864c74eb-ee60-4b64-8169-1af205f1a81b.png">

**Comment by dankelley** [comment]
PS. I may also trim the bottom and left margins another half-font-height.  That won't make a big difference but you know me -- I prefer tight margins, so we get more space for the data.

**Comment by dankelley** [comment]
I've tightened the margins a bit more in "developdevelop" commit e36126f462bf5d60a05b00a17b95b2052500b601; below is the result (to be compared with the second plot, 2 comments above).

<img width="1022" alt="mapapp-developdevelop2" src="https://user-images.githubusercontent.com/99469/134670397-926812ce-32f0-4be1-a5e0-7166069f826c.png">

**Comment by j-harbin** [comment]
I agree that the new `developdevelop` looks better. Correct me if I'm wrong, however, didn't we initially set the margins for mapApp, then set it back to the original (as suggested when we were submitting to CRAN). This caused us to run into the problems with brushing to zoom in, etc (https://github.com/ArgoCanada/argoFloats/issues/500), which is why we removed it. Will this cause the same problem or is this different?

**Comment by dankelley** [comment]
You're not wrong.  But there are 3 places I can think of to set it.  One has no effect. Another breaks zooming.  And the third -- the one we have in developdevelop -- seems to work.  But I'd really appreciate it if you could try zooming and some other things for 15 minutes.

**Comment by j-harbin** [comment]
All works on my end. I did notice another error (unrelated to this) so I will make a separate issue.

**Comment by dankelley** [comment]
Done.
