### ISSUE TITLE
Fixing 3 mapApp() issues

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#509]
In testing mapApp(), I discovered 3 issues worth addressing:

* [x] We cannot turn off all the argo types (a known issue).
* [x] "Contour" only works if one of the argo types is displayed (a new issue).
* [x] The scalebar does not white-out contours (a new issue).

I see how to fix these things, and I'll do so in the "developdevelop" branch.

My plan is to leave this issue open until at least the afternoon of Monday, Sep
28, in hopes that @j-harbin will check "developdevelop" to see if it seems OK.
If I get the thumbs-up, I will merge "developdevelop" into "develop" before the
end of Monday.

A note to @j-harbin: I have made a new global variable named "viewDefaults" (in
inst/shiny/mapApp.map.R:6) that holds the initial state of input$view.
I mention this because this line is just above the one setting colDefaults, so
we might get a merge conflict if @j-harbin edits nearby. I actually think we
ought to have a variable called "defaults", like
```R
defaults <- list(view=..., col=...)
```
and then change `colDefaults` to `defaults$col` and so forth.

I think that would make the code easier to understand.  And, who knows, we might get other things for which we want to save defaults.  What do you think of this, @j-harbin? 

PS. our planned release date is next Friday, so we have lots of time for small
changes and testing.

**Comment by dankelley** [comment]
I've made the fix in "developdevelop" commit ec1578d85a6f2cb2eef577971d4c7ab1beeae0d9 and am attaching a video (not sure if this works -- will we get sound, for example??) to demonstrate.

https://user-images.githubusercontent.com/99469/134772330-cfcd217b-1728-4f54-bce8-ee47659775d4.mp4

**Comment by j-harbin** [comment]
I didn't know we could add videos to issues! This is helpful when trying to explain how to recreate a bug in `mapApp()`. This all looks good to me.

**Comment by dankelley** [comment]
Thanks.  I merged "developdevelop" into "develop" and am closing this issue now.
