### ISSUE TITLE
"r" doesn't refresh check marks

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#512]
When the user clicks "r", it resets the "view" to only have bgc, deep, and core selected (ie. not topo, hires, path, and contour). If a user does the following:

1. open `mapApp()`
2. click topo
3. click "r" keystroke

You'll notice that topo disappears as expected, but it remains checked in the view (see below). This is not specific to topo, but instead occurs for all of the "view" widgets. 

![Screen Shot 2021-09-28 at 2 59 43 PM](https://user-images.githubusercontent.com/58750538/135140734-c1fb798c-db1a-4622-946c-b0ad23c29743.png)

On the other hand, if a user does the following:

1. open `mapApp()`
2. UNCLICK bgc
3. click "r" keystroke

BGC floats get displayed again as expected by the default, but it remains unchecked in the widget.
![Screen Shot 2021-09-28 at 3 01 05 PM](https://user-images.githubusercontent.com/58750538/135140900-6622d338-9c25-4971-8b6a-c868365c248a.png)

There is technically no bug here, however, it could be a little confusing to users. I'm not sure how to fix this. Thoughts on this Dan?

**Comment by dankelley** [comment]
See snapshot.  I think maybe near line 695 (bottom panel) we need to update the `checkboxGroupInput` named "view" (see top panel)

<img width="1138" alt="Screen Shot 2021-09-28 at 3 05 54 PM" src="https://user-images.githubusercontent.com/99469/135141574-4039dc9b-e6e9-47e2-96ed-54711238e3b3.png">

**Comment by j-harbin** [comment]
Ah! You're right. This is now fixed in commit 38b59b503734410420d5856812572bd4bf33e632 of develop.

**Comment by dankelley** [comment]
Um, did you push that commit?  I'm not seeing it.

**Comment by j-harbin** [comment]
Hehe! Nope, I forgot. It's pushed up now.

**Comment by dankelley** [comment]
Cool. reclosing now
