### ISSUE TITLE
Float ID gets erased when switching from focus "single" --> "all" --> "single"

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#514]
When a user does the following:

1. Double click a float, which autofills in the Float ID widget
2. Changes focus to "all"
3. Tries to go back to "single"

The float ID disappears. See video below

https://user-images.githubusercontent.com/58750538/135261019-0859e571-4cdd-47e9-a5ff-511e8826558a.mp4

.

**Comment by dankelley** [comment]
Actually, I think what it does is correct.  If you want we could do a quick Z to discuss.

**Comment by j-harbin** [comment]
I agree with you. If the user wanted to remember which float they were looking at, they could use the "h" key stroke. I'm going to close this issue.
