### ISSUE TITLE
Remove "Focus" widget from mapApp()

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#516]
Discussions of this issue started in https://github.com/ArgoCanada/argoFloats/issues/513. In conclusion, I will be removing the "Focus" widget. The user will still have the option to type in their Float ID, which will look at (what is now called) the single view. If they remove the float ID, the geographical range will stay the same, but the time will not update from the time set by the single float.

**Comment by j-harbin** [comment]
This is done in commit 30c6fbf310256c365be90c85d03a6b513faf201f of develop. Dan, if you're satisfied with the changes, feel free to close this issue.

**Comment by dankelley** [comment]
This looks great.  I am going to change the message
```
Hover mouse in plot to see locations; click-slide to select regions; double click point to focus.
```
to
```
Hover to see location/cycle; brush to select region; double-click  to restrict ID.
```
so that it's a bit shorter (and so the double-click action is clearer).

**Comment by dankelley** [comment]
I've changed the hover msg in commit 7d4fb1f319fd1e2c2255df28868066f92a32c130  of develop, and I agree that this issue has been addressed, so I'm closing it.  Thanks!
