### ISSUE TITLE
colourpicker default colour not updating when "u" or undo is used in mapApp()

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#522]
The below video explains this issue.

https://user-images.githubusercontent.com/58750538/137132752-6f063d73-1ed0-4583-8e58-b8d369efa9e6.mp4

**Comment by dankelley** [comment]
I agree: the colourpickers should update.

**Comment by j-harbin** [comment]
This has been fixed in commit 4117ddd5f7fff771d9b809cde349ab16201fbc01 of develop. Not only did I change the colour pickers to update, I also made it such that the other setting widgets (ie. symbol type, size size, path width, etc.) also update after clicking the "Undo" button and "u". I'll now close this issue.
