### ISSUE TITLE
should we supply a topo file with argoFloats?

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#523]
In many circumstances, I want to make maps of local regions (e.g. a region of interest, or the region traced out by a single ID) and these often have scales like in the panels below.  The top panel is with the topo we have now (from `oce::topoWorld`, at 30-minute resolution) and the bottom one is with a new file I downloaded, which is at 15-minute resolution.  The first looks pretty "blocky" at this scale but the second looks quite good.

This new data file is 1.3M in size, so it would get a NOTE in a CRAN submission, I think.  But my impression is that the rule for human inspection of a package is 5M for the whole package, so we would be under that.

I wonder.  Should we include this with argoFloats?  My vote would be perhaps -0.2 on the -1 to 1 scale, meaning I don't favour it, but I don't hate it.  I am slightly negative because I think it's best to lean on existing packages.  (Maybe `ocedata` needs a higher-resolution topography file. After all, it gets updated only rarely and so maybe it's OK to put in a bigger file.)

Even though I am not really in favour of adding this, I wanted to bring it up.
Your thoughts, @j-harbin?

![create_topoWorld](https://user-images.githubusercontent.com/99469/137316144-5a6ae487-ed66-4a39-af7e-c820886ec67d.png)

**Comment by j-harbin** [comment]
There is no doubt the second photo is more appealing. That being said, the idea of size scares me. We mention to the user how you can get the hi-res topo in the `mapApp()` help docs (see below). My thought is if a user is that interested in topography, they will take the 2 minutes to do the outlined steps. I therefore vote -0.4 (ie. not in favour) for adding this.
![Screen Shot 2021-10-14 at 10 55 27 AM](https://user-images.githubusercontent.com/58750538/137332266-15d30b3c-8a3b-44a4-87a5-c9e03b764600.png)

**Comment by dankelley** [comment]
Good, two votes on the same size of zero, so this is rejected.  I'll close it.
