### ISSUE TITLE
argos[["ID"]] doesn't perform as expected

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#530]
I noticed when dealing with type `index`, in order to look at the first ID or cycle we must FIRST do `[["ID"]]` THEN `[[1]]`. See below:

``` r
library(argoFloats)
ai <- getIndex()
index1 <- subset(ai, ID="6900388")
index1[["ID"]][[1]] # This works
#> [1] "6900388"
index1[[1]][["ID"]] # This does not work
#> NULL
index1[["cycle"]][[1]] # This works
#> [1] "001"
index1[[1]][["cycle"]] # This does not work
#> NULL
```

<sup>Created on 2021-11-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

The same can be said for type `argos`, but only when extracting `cycle`, not `ID`. Notice below that the user has the option to give`argos[[1]][["ID"]]` to get the ID, but not `argos[[1]][["cycle"]]` to get the cycle. 

``` r
library(argoFloats)
ai <- getIndex()
index1 <- subset(ai, ID="6900388")
#> Kept 223 cycles (0.00879%)
profiles <- getProfiles(index1)
argos <- readProfiles(profiles)
#> Warning in readProfiles(profiles): Of 223 profiles read, 1 has >10% of pressure values with QC flag of 4, signalling bad data.
#>     The indices of the bad profiles are as follows.
#>     14
argos[["ID"]][[1]]
#> [1] "6900388"
argos[[1]][["ID"]] # This works
#> [1] "6900388"
argos[["cycle"]][[1]]
#> [1] "001"
argos[[1]][["cycle"]] # This does not work
#> NULL
```

<sup>Created on 2021-11-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

My question is A) should these be consistent for type `argos` and B) which way do we prefer? @dankelley , what are your thoughts on this?

**Comment by dankelley** [comment]
Want to Z on this?  It would be easier than sorting it through by typing.

**Comment by j-harbin** [comment]
It was agreed that for `index` type, the proper action is occurring. For `argos` type, to get the expected behaviour, the user must to `argos[[1]][["cycleNumber"]]`. To be able to do `argos[[1]][["cycle"]]`, the user must use the GitHub version of `oce` once issue 1881 is fixed.

**Comment by dankelley** [comment]
Note that, with oce as on github (develop branch), `argos[[1]][["cycle"]]` should now work.
