### ISSUE TITLE
PROPOSAL: Add ID and cycle to the index

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#532]
Currently the names of an index include: file , date, latitude, longitude,  ocean, profiler_type, institution, and date_update. @dankelley and I were discussing that I should add ID and cycle to this data frame so it will speed up the process of extracting ID and cycle. See below the time difference if ID and cycle were included in the index.

``` r
library(argoFloats)
ai <- getIndex()
A <- system.time(ai[["ID"]],1)
A
#>    user  system elapsed 
#>   2.303   0.013   2.324
B <- system.time(ai[["file"]],1)
B
#>    user  system elapsed 
#>       0       0       0
```

<sup>Created on 2021-11-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by dankelley** [comment]
But here's the good thing...
```
> round(log(10),3)
[1] 2.303
```

🐵

**Comment by dankelley** [comment]
@j-harbin where do we sand on this?  I sort of think it was done 28 days ago but, if not, perhaps you can find time to do it, so the issue can be closed.

**Comment by j-harbin** [comment]
Thanks for commenting to avoid the stale bot message. This has not been done yet, but again is on my radar of list of things to do.
