### ISSUE TITLE
"Suggests" vs "Depends"

### ISSUE THREAD

**Issue by richardsc** [ArgoCanada/argoFloats#536]
This was probably talked about before, and I forgot about it (or missed it), but the current state of having the package depend *only* on R version (though `oce` is in "Imports") means that a new user actually has to do quite a bit of package installation work to be able to run even the example given in the package README (e.g. without `curl` you can't even download the index). 

If there is a good reason for keeping the dependencies light (and relying on errors to get everything installed as required), we should at least update the README to reflect that -- either it should give the instructions for installing the required dependencies to run the example (`dependencies=TRUE` I think?) and/or there should be a paragraph about it that a user will see.

**Comment by dankelley** [comment]
Good idea, thanks.  I added more (as you can see in the snapshot below).

<img width="656" alt="Screen Shot 2021-11-17 at 1 16 49 PM" src="https://user-images.githubusercontent.com/99469/142249463-bea33260-8dd0-4e8f-8338-3ce44248eadf.png">

**Comment by dankelley** [comment]
I am closing this issue now, because (a) I think it has been handled, and (b) the reporter is a co-developer, who can be relied upon to reopen the issue if desired.
