### ISSUE TITLE
make plot(..., bathymetry=TRUE) for index/argos something that can be set with an option

### ISSUE THREAD

**Issue by richardsc** [ArgoCanada/argoFloats#537]
I like that the index plots can have bathymetry, but I feel like the slowness (and the issue of the creeping palette margins) makes it's less useful for quick plots of index subsets.

So, for discussion, I wanted to propose either:

1. We change `bathymetry` to be default FALSE, or 
2. We make it an option that can be set (like `argoDefaultDestdir()` etc)

**Comment by dankelley** [comment]
I agree with this.  @j-harbin and I have gone back and forth on it.  THB, I thought we were defaulting to FALSE.

I think we ought to do just like for `destdir`.

J can do this, I'm pretty sure.  I'll be swamped with teaching for a while.

**Comment by dankelley** [comment]
I have some time this morning so I'm going to do this one.

**Comment by dankelley** [comment]
commit 383e1dbdeac5dd840abc904f5515a77e02e4fda9
Author: dankelley <kelley.dan@gmail.com>
Date:   Thu Dec 2 11:15:39 2021 -0400

    plot() has bathymetry=FALSE by default

**Comment by dankelley** [comment]
This is done now, so I'll close this, on the assumption that the reporter (a co-developer) will feel free to reopen it if desired.
