### ISSUE TITLE
need to update on CRAN

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#543]
Please see https://github.com/dankelley/oce/issues/1918 for details.  CRAN is telling us to update argoFloats.  I will do this before the end of the week.  Once I've done what I need to do, I'll ask @j-harbin to do a test build.  (I will do oce first, and that will involve running both local and nonlocal tests.  That process will take a few hours.)

**Comment by dankelley** [comment]
@j-harbin I have done local tests, and have submitted a remote test on windows.  This is for "develop" commit 7669b9eb0261f8c58df3330839635f57fe646357.

Can you do a quick test build/check on your machine?  (Also, please "follow" this comment thread so you can keep up with my other tests.). I may need to ask you to test several times.  I'd love to clear this up today so I can submit to CRAN before noon tomorrow.  (I like to try to submit to CRAN during the week, in case one of the CRAN volunteers has to look at test results.)

**Comment by j-harbin** [comment]
![Screen Shot 2022-02-17 at 8 18 46 AM](https://user-images.githubusercontent.com/58750538/154480474-f31dfa4b-c54c-46f3-9e29-5fb42fda217d.png)

All good so far!

**Comment by j-harbin** [comment]
JH Checklist:
* [ ] local check
* [ ]  devtools::check_win_devel()
* [ ] devtools::check_win_release()
* [ ]  devtools::check_win_oldrelease()
 * [ ] rhub::check_for_cran()

**Comment by dankelley** [comment]
Submitted.  Details of the email, below.  I will leave this issue open until I see it appearing on CRAN for some systems.  (I won't wait for all systems because sometimes that takes a week or two.)

>Dear maintainer,
>
>thanks, package argoFloats_1.0.4.tar.gz is on its way to CRAN.
>
>Best regards,
>CRAN teams' auto-check service
>Flavor: r-devel-linux-x86_64-debian-gcc, r-devel-windows-x86_64
>Check: CRAN incoming feasibility, Result: Note_to_CRAN_maintainers
>Maintainer: 'Dan Kelley <[dan.kelley@dal.ca](mailto:dan.kelley@dal.ca)>'

**Comment by dankelley** [comment]
I'm closing this now, since the following two links show that CRAN Downloads and Checks are all now updated to this version.

* https://cran.r-project.org/web/packages/argoFloats/index.html
* https://cran.r-project.org/web/checks/check_results_argoFloats.html
