### ISSUE TITLE
In mapApp() hover message should give position of the float, not the position the user clicked

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#551]
See example below

![Screen Shot 2022-04-04 at 1 51 45 PM](https://user-images.githubusercontent.com/58750538/161593315-f4a955f6-4e9e-49b3-9582-bc50b13fb525.png)

**Comment by j-harbin** [comment]
Fixed in commit 200270888ae88ec04269046263bfc73d8b13eb12

![Screen Shot 2022-04-20 at 4 22 40 PM](https://user-images.githubusercontent.com/58750538/164307244-18044ba2-0597-4369-89b1-178ad826c20f.png)

**Comment by j-harbin** [comment]
Whoops! I just realized I was accidentally working in the "main" branch for this commit, and not the "develop".

**Comment by dankelley** [comment]
https://youtu.be/VC3thojIrFc
