### ISSUE TITLE
When a hover message is displayed in mapApp(), the float of interest should be highlighted on map

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#552]

**Comment by j-harbin** [comment]
The problem of the map plotting more than once is evident here. The idea is that when we are hovering a message from a float, we wanted to highlight what float it is. The video below shows that the map loop makes this not work. I've left the code for this in, but commented it out until I figure out this loop problem.

https://user-images.githubusercontent.com/58750538/164300512-3b509df3-5c58-4a9c-acff-958492747d09.mp4

**Comment by dankelley** [comment]
If it would help, we could Z tomorrow (say 0900, to be concrete) to get more eyes on the problem.

**Comment by j-harbin** [comment]
Agreed. I'm available at 0900 tomorrow.

**Comment by dankelley** [comment]
I don't like to put links here, but I'll email a link tomorrow at 0900 to anybody on the devel team who expresses an interest before that time.

**Comment by richardsc** [comment]
Go ahead and email me the link. I'll join if I can!

**Comment by j-harbin** [comment]
Done in commit 5e0d8412a1df25f33e60725f1237487ac05b39e7 of develop.
