### ISSUE TITLE
how to cursor from arrow to circle?

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#553]
@j-harbin do you know how to do that?  It would be quite nice, for QC things where a person wants to indicate a point. Somehow, my brain finds it easier to encircle a data point with a cursor, as opposed to putting the thin end of an arrow icon at the point.

Feel free to close this, if you don't know and don't want to find out.  (Or if the solution involves some fancy storage of icon image files somewhere in a css directory or whatever.)

**Comment by dankelley** [comment]
I think this might be quite hard.  @j-harbin feel free to close this issue, if you've looked into it and don't see a solution.  I suppose it doesn't hurt to have it open, but we both likely have it in our heads to do this in some of our shiny apps, if we ever happen to see the method.

**Comment by j-harbin** [comment]
Dan, the following code changes the cursor  to a "crosshair" when hovering over a widget. This code was inspired from https://stackoverflow.com/questions/53506514/set-image-as-cursor-in-r-shiny. I know you wanted a circle and not a crosshair, but this tells me that it would be quite easy.


```R
library(shiny)

csscode <- HTML("
#messagebutton {  
  cursor: crosshair;
}
")

ui  <- fluidPage(    
    tags$head(tags$style(csscode)),
    actionButton(inputId = 'messagebutton', label = 'click me')
)

server <- function(input, output, session) {}

shinyApp(ui = ui, server = server)
```

**Comment by dankelley** [comment]
omygod that is **COOL**

**Comment by j-harbin** [comment]
Based on the video @dankelley sent via email, I know he had incorporated this into his tagging app. I will close this issue (breaking argoFloats rules :) )
