### ISSUE TITLE
mapApp() scalebar can read 0km

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#554]
I noticed this during a workshop.  I cannot reproduce it on my machine, though, either with the CRAN version of argoFloats or with the github version.  It might be worth looking into by @j-harbin.

**Comment by j-harbin** [comment]
I remember seeing this in the workshop as well. I tried several different things to reproduce this, but was unsuccessful. I suggest closing this issue until it pops up again.
