### ISSUE TITLE
plot(..., bathymetry=TRUE) hangs?

### ISSUE THREAD

**Issue by richardsc** [ArgoCanada/argoFloats#556]
Not sure if this is my machine, or if something about the NOAA bathymetry download changed, but if I do e.g.

```r
library(argoFloats)
i <- getIndex()
si <- subset(i, circle=list(longitude=-60, latitude=40, radius=100))
plot(si, bathymetry=TRUE)
```

it just hangs (for longer than I'm willing to wait) at the plotting line.

I just realized that this is using `oce::download.topo()`, so next I'll see if that is the problem, but wanted to document the issue here first.

```
R version 4.1.2 (2021-11-01)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.3.1

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] argoFloats_1.0.4

loaded via a namespace (and not attached):
 [1] compiler_4.1.2 magrittr_2.0.2 R6_2.5.1       cli_3.1.0      tools_4.1.2
 [6] ocedata_0.1.8  curl_4.3.2     Rcpp_1.0.8     testthat_3.1.1 gsw_1.0-7
[11] rlang_1.0.1    oce_1.7-3
```

**Comment by j-harbin** [comment]
I did the following. There was a slight lag, but nothing major on my end. An unrelated issue, though, is wow those margins are ugly.

system.time(plot(si, bathymetry=TRUE))
   user  system elapsed 
  1.198   0.039   1.268

![Screen Shot 2022-04-21 at 8 14 20 AM](https://user-images.githubusercontent.com/58750538/164446445-80c7d10b-f3c2-43df-bac4-fb4efb1cd045.png)

**Comment by j-harbin** [comment]
I'm closing this issue as there didn't seem to be an issue on my end and the "ugly" margins were explained to me in a Zoom. Clark, feel free to reopen if you feel it is still a problem.
