### ISSUE TITLE
Subset by polygon should have an error message when only 2 lat/lon points are provided

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#566]
As shown below, if the user does the following, we get an error:

``` r
library(argoFloats)
data(index)
lonp <- c(-77.492, -78.219)
latp <- c( 26.244,  25.247)
indexPolygon <- subset(index, polygon=list(longitude=lonp, latitude=latp))
#> Error: Error in subset,argoFloats-method():
#>   polygon is invalid, because of NA
```

<sup>Created on 2022-04-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

This is really because if a user only gives two points for a polygon, it's just a line and not possible for the polygon method to work as nothing is "inside" of the polygon.

**Comment by dankelley** [comment]
You might want to see why it says NA for the reason.  It ought to be displaying a more useful message.  If I recall correctly, we were using a function to look up the error but maybe that's being done incorrectly.

**Comment by j-harbin** [comment]
Done in commit 44a5e8d5aa6d7bd626c48f4e336582d7b8ee75fc of develop.
