### ISSUE TITLE
Proposal: Remove some keystrokes in shiny

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#569]
Dan and I chatted about this and thought it may be beneficial to remove some keystroke in shiny as the widgets have the same functionality. The existing keystrokes are below:

![Screen Shot 2022-05-05 at 1 56 22 PM](https://user-images.githubusercontent.com/58750538/166974423-a5738e86-1c3d-4c21-b7c5-2b52f3635ac8.png)

I propose removing i, o, n,e,s,w,f, and b. This is because all of these keystrokes can be taken care of with the existing widgets.

PS- any removal will be taking place after the polygon branch is merged into the develop branch.

**Comment by dankelley** [comment]
A good approach to this might be to define a state variable

```R
state$useKeystrokes <- FALSE
```
up near the start and then in the code, have e.g. change
```R
            } else if (key == "n") { # go north
                dy <- diff(state$ylim)
                state$ylim <<- pinlat(state$ylim + dy / 4)
```
to
```R
            } else if (useKeystrokes && key == "n") { # go north
                dy <- diff(state$ylim)
                state$ylim <<- pinlat(state$ylim + dy / 4)
```

The advantage of this is that we could easily add it back in.  And if we put `useKeystrokes` into `state`, then we could have a "settings" thing to turn them back on.

Up to you.  If you remove them, please use a clear commit note that we can find later if we want.  Personally, I'd just comment-out the code.  (I know, that's not the "right thing" in git, but I often comment things out for a few months and only actually remove them after I am really, really sure.)

**Comment by j-harbin** [comment]
Done in commit bd586c2e5dfbc6968d1c53a9f7ca6eb88685ce40 of develop.
