### ISSUE TITLE
mapApp is not adaptive to larger screens

### ISSUE THREAD

**Issue by richardsc** [ArgoCanada/argoFloats#574]
I suspect that there is a hard-coded figure/column width somewhere in the app, and probably because all the the development was done on Macbooks this wouldn't have been flagged as an issue, but I noticed today on my nice 24" monitor that the size of the map figure is laughably tiny:

![image](https://user-images.githubusercontent.com/233584/171227326-198143e7-0287-46de-b47c-b44a1b242916.png)

**Comment by dankelley** [comment]
Hm, I don't think the map is given a particular size (see below for a link to what I think is the relevant part of the code).  Perhaps @j-harbin could set the width to 100% as a test?

https://github.com/ArgoCanada/argoFloats/blob/ad24fd27d6d6d4cf30958c4ea26ad667caa0ef18/inst/shiny/mapApp/app.R#L1346
