### ISSUE TITLE
getProfileFromUrl() doc error

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#575]
It says that for a missing file, `NULL` is returned.  However, `NA` is returned.  I propose changing the docs, not the code, because somebody might have written code that is based on the *actual* behaviour, not the *documented* behaviour.

Do you agree with my decision, @j-harbin?  If so, I'll make the change.  (The change is quicker than typing this issue, by orders of magnitude!)

<img width="1074" alt="Screen Shot 2022-05-31 at 3 15 39 PM" src="https://user-images.githubusercontent.com/99469/171256676-b113c35b-6708-4bdb-8847-19cbd22a2292.png">

**Comment by j-harbin** [comment]
Done in commit ad24fd27d6d6d4cf30958c4ea26ad667caa0ef18 of develop. @dankelley if you are satisfied with the changes feel free to close the issue.

**Comment by dankelley** [comment]
Looks great, thanks!
