### ISSUE TITLE
problem accessing remote index

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#579]
@j-harbin do you know what's going on here?  First, the .fr server isn't working.  I guess that just happens, sometimes.  But, second, it seems like it only tried a single server, even though (a) I thought we had it set up to try two servers and (b) the error message says "Could not download ... from any of these servers".

```R
> library(argoFloats)
> indexAll <- getIndex(age=0)
Downloading 'https://data-argo.ifremer.fr/ar_index_global_prof.txt.gz'
Error in curl::curl_download(url = url[iurl], destfile = destfileTemp,  :
  Timeout was reached: [] Connection timeout after 10000 ms
Can't download index from https://data-argo.ifremer.fr
Error in getIndex(age = 0) :
  Could not download index from any of these servers:
'https://data-argo.ifremer.fr/ar_index_global_prof.txt.gz'
```

**Comment by dankelley** [comment]
I'll be looking into this before noon.

**Comment by j-harbin** [comment]
@dankelley, I don't receive this error (see reprex below). Additionally, I can't quite remember if `getIndex` automatically tries both servers. I believe by default it tries USGODAE and then if specified by `server="infremer"` it will try the French server.

``` r
library(argoFloats)
indexAll <- getIndex(age=0)
#> Downloading 'https://data-argo.ifremer.fr/ar_index_global_prof.txt.gz'
indexAll
#> argoFloats object of type "index" with 2668361 items
```

<sup>Created on 2022-08-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by dankelley** [comment]
Hm.  Well, I changed "develop" to try two servers.  (It used to do that but we got a new behaviour via a function that sets up defaults.). Anyway, the .fr one works for me now.  Maybe it was eating brunch.

commit c3bafe9df0c197b495ed068545fde37603678974
Author: dankelley <kelley.dan@gmail.com>
Date:   Thu Aug 4 08:10:12 2022 -0300

    make default server have 2 entries; fix two URLs
    
    See
    https://github.com/ArgoCanada/argoFloats/issues/579
    for the server problem, and
    https://github.com/ArgoCanada/argoFloats/issues/580
    for the URL problem.

**Comment by dankelley** [comment]
Weirdly, it now fails for me (again).  Maybe it's because I am running R through vim here ... maybe RStudio has some special hand-shaking.  Anyway, I guess I don't care too much because the newly-updated `argoFloats` goes to the second server, and that works.

<img width="960" alt="Screenshot 2022-08-04 at 9 21 12 AM" src="https://user-images.githubusercontent.com/99469/182845589-4d8d6506-989e-4de2-a643-2d44ecf5c6af.png">
