### ISSUE TITLE
Should we interpret the `MTIME` field?

### ISSUE THREAD

**Issue by richardsc** [ArgoCanada/argoFloats#590]
I noticed when looking at a recently deployed float (ID=6990512) that it contains a field called `MTIME`, which based on the nc file corresponds to:
```
        double MTIME[N_LEVELS,N_PROF]
            long_name: Fractional day of the individual measurement relative to JULD of the station
            _FillValue: 999999
            units: days
            valid_min: -3
            valid_max: 3
            C_format: %.6f
            FORTRAN_format: F.6
            resolution: 9.99999997475243e-07
```
I presume that this field is also described in the relevant Argo manual (but I haven't looked). It certainly could be converted to a POSIX time (using the "JULD" of the station).

A reprex to get data from this float to examine is:
```r
library(argoFloats)
i <- getIndex()
si <- subset(i, ID='6990512')
p <- getProfiles(si)
d <- readProfiles(p)
```
Note that because the float starts at the bottom the profile of MTIME goes negative:
<img width="680" alt="image" src="https://user-images.githubusercontent.com/233584/226438173-5d5b62d2-1eba-4afe-95c5-c070047d8de8.png">

**Comment by richardsc** [comment]
I think that the following should be all that is required to convert MTIME to POSIX, providing that `startTime` in the object corresponds to the "JULD" field mentioned in the attributes:
```r
time <- ctd[['startTime']] + 86400 * ctd[['MTIME']]
```

**Comment by richardsc** [comment]
The nc attributes say the Argo reference for JULD is 1950-01-01 00:00:00. 

But I guess the question is how do we determine the `startTime` field from the nc file? (I could look at the code but am on the bus right now)

**Comment by dankelley** [comment]
Our comments are interlaced.  In the comment just before yours, I showed how we compute the start time.  (It is called `data$time` though, not `metadata$startTime`.)

**Comment by richardsc** [comment]
```r
    res@data$time <- t0 + res@metadata$juld * 86400
```

Oh, I see that `time` *is* constructed from JULD. So I'm confused as to why they would be different …

**Comment by dankelley** [comment]
I'm planning to fiddle with this tomorrow.  If you're at Dal on Wednesday we could talk about it.

**Comment by dankelley** [comment]
Mystery solved:
```R
> options(digits=15)
> a@metadata$juld
[1] 26730.9497685185
> a@metadata$juld - 26730
[1] 0.949768518519704
> (a@metadata$juld - 26730) * 24
[1] 22.7944444444729
> ((a@metadata$juld - 26730) * 24 - 22)*60
[1] 47.6666666683741
> (((a@metadata$juld - 26730) * 24 - 22)*60 - 47)*60
[1] 40.0000001024455
```

Those steps say that the time of day is 22:47:40 which is what we got.  So, no contradiction.  I was just being stupid, forgetting I have R set up only to have a certain number of digits.

@richardsc if you're going to be at Dal Wed or Fri (CDOGS day) we could chat more about whether to make oce

1. return `[["startTime"]]` as the start time
2. return `[["time"]]` as a vector of times

or perhaps just store `time` as a column.  We would want to be consistent with CTD handling, I think.  It's easier to hash such things out in person, as compared to comments on GH, I think/find.

**Comment by dankelley** [comment]
One thing to keep in mind -- there may be user code (possible quite a lot of user code since argo has been in oce for a long time) that assumes that `[["time"]]` will produce just one value.

I am going to write some code to see how many of the .nc files on my compute has MTIME defined. That would be useful.

I am leaning towards just storing `@data$mtime` as it is (fractional days), if the file contains `MTIME`.   The conversion to get time-of-each-datum is easy and could be documented.  That way, any existing code that assumes time is a single value will still work, but users who want more can get it (if it's in the file).

**Comment by richardsc** [comment]
I think I agree with you re: "time" vs "mtime". For the Argo folks "mtime" will be a known thing, which as you say is easy to handle.

One thought though, as an issue for `oce`, is that perhaps `as.ctd()` on an argo object should know how to interpret `time` (metadata) and `mtime` to be converted to the standard fields (for a `ctd` object) of `startTime` (metadata) and `time` (data).

**Comment by dankelley** [comment]
Oh, hang on.  We *already* read MTIME, so the user can do as below.  I don't think `oce` needs changing.

PS to @richardsc do you know why there are **so many** NA values?  They outnumber true values 10:1 for this file.

```R
library(oce)
f <- "R6990512_001.nc"
a <- read.argo(f)
sort(names(a@data))
time <- a[["time"]] + a[["MTIME"]]*86400
# NA values outnumber finite values 10:1 ... WHY?
ok <- is.finite(time)
print(table(ok))
png("01.png")
oce.plot.ts(time[ok], a[["pressure"]][ok], type="o", pch=20, cex=0.7)
```

![01](https://user-images.githubusercontent.com/99469/226570585-243380c3-7ff1-4444-b2d0-206a33691acc.png)

**Comment by dankelley** [comment]
I like your idea.  (As often seems to be the case, our comments are interlacing.)

**Comment by richardsc** [comment]
Yes, do do read it -- that's the issue title was "Should we _interpret_ it"? 😄 

I think the reason there are NAs is because it doesn't necessarily store the time corresponding to every sample (maybe to save space?). It's actually something I plan to look into (this is quite new firmware on a float type that DFO uses).

**Comment by richardsc** [comment]
On the interpretation note -- should it be at least lowercased? Or just left alone?

**Comment by dankelley** [comment]
I also thought about whether to lower-case it.  We do that for "standard" things that are known in other objects (e.g. DOXY and similar things all get named oxygen).  I want to look in the SBE docs to see if they talk about MTIME there.  It rings a bell, but, for the life of me, I am drawing a blank on what the M might stand for.

**Comment by dankelley** [comment]
I guess we could call it "mtime".  Frankly, I'm divided on this. If the original name is retained (which it ought to be) then the user could do either of
```R
a[["MTIME"]]
a[["mtime"]]
```
and get the same result.

I am still blanking on what to call that thing.  Maybe I need to look in argo docs now.  I imagine "M" means *something*.

**Comment by richardsc** [comment]
I think the "M" is for "measurement".

See this from the Argo QC manual, that explains the sporadic time returns:

![image](https://user-images.githubusercontent.com/233584/226582434-63b2ed21-ae68-4b05-b8c7-d8d335fd0e55.png)

**Comment by dankelley** [comment]
I have found something in section 2.6.4 of Ref 1:

<img width="903" alt="Screenshot 2023-03-21 at 8 02 37 AM" src="https://user-images.githubusercontent.com/99469/226587636-fa9cd0be-ff3e-4b0a-ad4e-07d3e2bdb719.png">


# References

1. Argo Data Management Team. “Argo User’s Manual V3.4,” January 20, 2021. https://archimer.ifremer.fr/doc/00187/29825/86414.pdf.

**Comment by dankelley** [comment]
I'm closing this because it relates to oce, not directly to argoFloats.  See https://github.com/dankelley/oce/issues/2122 for a discussion of another matter relating to MTIME. 

 I prefer discussing on oce when it's an oce issue, because I get auto-notified about all new oce issues.  Plus, I check oce quite a lot, and don't have a habit of looking for issues here on argoFloats.
