### ISSUE TITLE
Creation of Video 2

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#69]
As discussed in the ftf with @dankelley , we will create the next video this Friday.

The following content will be included:
- JH instructing DK
- Get circle subset near Bermuda
- Take this data and show a TS diagram

**Comment by dankelley** [comment]
The video has been created, and is in the editing phase.

**Comment by dankelley** [comment]
The video has been approved by both speakers, and put online at https://youtu.be/ZoTrVEMG5Qo
 so I am closing the issue.  Good work, team!
