### ISSUE TITLE
pkgDown footer should name coauthors

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#74]
At the bottom of the page we see as below. @richardsc, could you try to figure out how to make it list coauthors?

<img width="219" alt="Screen Shot 2020-04-25 at 7 16 02 AM" src="https://user-images.githubusercontent.com/99469/80277356-c4b30500-86c4-11ea-9afb-178817ea52da.png">

**Comment by richardsc** [comment]
I forgot about this, but I think the reason is because only "authors" (as named in the `DESCRIPTION`) get to be listed on the bottom of the page. 

At the very least I think that @j-harbin should be listed as author.

**Comment by dankelley** [comment]
Thanks.  I added @j-harbin as an author, and so now we get two names in the sidebar of the webpage.  Closing now.
