### ISSUE TITLE
subset(..., polygon) unclosed polygons; new plot colours

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#75]
@j-harbin and @richardsc : I wonder if we can get votes on two topics. 

**Topic 1.**

At the moment, `subset` issues a warning for an unclosed polygon.  The reason for that is that weird results can occur by the joining of first and last points (e.g. that can make a polygon that has crossing line segments, which we don't want).  My question is: do you think a warning should be issued?

I vote +1 for keeping the warning. 

**Topic 2.**

See the snapshot from 
https://argocanada.github.io/argoFloats/reference/subset-argoFloats-method.html and notice that 
I changed the colour of the float-location dots from blue to gray.  That's because I think it will be a common case that users want to use a colour to designate something, and I don't want to "waste" a bright colour by plotting those dots in blue, which is what we had before.

I vote +1 on this switch to gray.

PS. in the snapshot, you'll also see that the colours are less saturated and, I presume, better suited for people with vision limitations.  (These colours come with R 4.x, released the other day.)
I'm very happy that R has changed the colours ... the yellow is now visible!

<img width="704" alt="Screen Shot 2020-04-26 at 10 28 07 AM" src="https://user-images.githubusercontent.com/99469/80309250-3fa21b80-87aa-11ea-8ceb-2800feca8a94.png">

**Comment by j-harbin** [comment]
I like the idea of having the warning, but I'm wondering if we could word it in a way that may tell the user why it's closing it? Ie:  In subset,argoFloats-method(): First and last points did not match. Closing the polygon to avoid crossing line segments.

Or do we think that warning is too long?

Also, definitely +1 for changing the color to gray. It looks great.

**Comment by dankelley** [comment]
Yes, I like the wording you're suggesting for the warning. Could you fix that up, please?

**Comment by j-harbin** [comment]
As discussed in our ftf today, I changed the polygon warning back to what it was.

**Comment by j-harbin** [comment]
Dear reporter,
Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done. Thanks!
PS. This is a standardized reply.

**Comment by dankelley** [comment]
Yes, with https://github.com/ArgoCanada/argoFloats/blob/d2f2a76a0f4760a9f6d6a9246373dabdb5461352/R/subset.R#L222 I think this can be closed, because now we'll get indications of more problems than just self-intersection.
