### ISSUE TITLE
vignette should list videos

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#76]
Pretty soon, there will be half a dozen of them, and so an itemized list will be getting close to a full screenful, which makes me think this should be a subsection.

PS. `sandbox/videos/README.md` is basically all we need.

**Comment by j-harbin** [comment]
Dan, I was *just* thinking about this. I was thinking either a list within the vignette, or on our user website.

**Comment by dankelley** [comment]
Could be both, I guess.  The website is tricky, because it would require learning how to add specialized content there ... bear in mind that the whole website is created automatically, through analysis of the package, so adding specialized content would require learning something about the `pkgdown` package (not a bad use of some time, though).

**Comment by j-harbin** [comment]
Hi Team,

You'll see at  https://github.com/ArgoCanada/argoFloats/blob/develop/vignettes/argoFloats.Rmd that there is a Youtube Video section added to the vignette. @dankelley , if you are okay with how the table looks feel free to close this issue.

**Comment by dankelley** [comment]
Looks good, so closing now.  At 1400h today, I plan to merge 'develop' into 'master' and then rebuild the website.
