### ISSUE TITLE
create video 4

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#83]
@j-harbin and I plan a video about using `subset(i, polygon)`, perhaps
* on the Atl and Pac sids of the isthmus of Panama, where e.g. a circle might include water from two oceans
* along the eastern or western sides of Greenland, isolated from waters further offshore

NB. other ideas have been tossed around and will likely be decided in a vf2f prior to the vf2f during which the video would be made.

**Comment by j-harbin** [comment]
As an update mentioned by @dankelley , a good idea for a video could be:

Try to get the oceans on the other side of the isthmus of Panama by 

```R
library(oce)
library(ocedata)
library(argoFloats)
if (FALSE) { # finding good center
    data(coastlineWorldFine, package="ocedata")
    plot(coastlineWorldFine, clongitude=-80, clatitude=8, span=4000)
    ## centre <- locator(1)
    centre <- list(longitude=-83, latitude=9)
    points(centre$longitude, centre$latitude, col=2, pch=20)
    lines(rep(centre$longitude,2), c(-5,5)+centre$latitude, col=2) # show diameter
}

i <- getIndex()
s <- subset(i, circle=list(longitude=-83, latitude=9, radius=500))
if (!interactive()) png("by_ocean.png")
plot(s, which="map")
atlantic <- subset(s, ocean="A")
pacific <- subset(s, ocean="P")
points(atlantic[["longitude"]], atlantic[["latitude"]], pch=20, col=2, cex=0.7*par("cex"))
points(pacific[["longitude"]], pacific[["latitude"]], pch=20, col=3, cex=0.7*par("cex"))
if (!interactive()) dev.off()
```
We will then see that this fails due to Atlantic and Pacific Ocean AREA, shown below. 

![Screen Shot 2020-05-04 at 10 41 04 AM](https://user-images.githubusercontent.com/58750538/80971907-cf237c00-8df3-11ea-9c08-eb6c88437233.png)

To solve this issue, we would then show how to do a polygon method.

**Comment by j-harbin** [comment]
The sound on the video sounds great. For the description of the video:

This video demonstrates how to use both the subset by ocean and subset by polygon function around the Isthmus of Panama. The manual referenced in this video can be found at:

Carval, Thierry, Bob Keeley, Yasushi Takatsuki, Takashi Yoshida, Stephen Loch, Claudia Schmid, Roger Goldsmith et al. "Argo User's Manual, Version 3.2. December 29th 2015.[SUPERSEDED]." (2015).

**Comment by dankelley** [comment]
The video has been uploaded to https://youtu.be/tcGRB479Udk so I'm closing this now.  Good work, team!
