### ISSUE TITLE
stray erroneous points with subset(s, polygon=) method

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#86]
I noticed this when trying something out for the upcoming video.  Notice the red dots in the Atlantic. I won't bother explaining things further, since @j-harbin and I went over this in a f2f meeting.

I suspect that the problem is in the `sf` scheme for finding points in a polygon.  To test that, I plan to switch (back) to `sp`.

This may take a few days.

```R
library(oce)
library(ocedata)
library(argoFloats)
setup <- FALSE

i <- getIndex()
s <- subset(i, circle=list(longitude=-83, latitude=9, radius=500))
if (!interactive()) png("03_by_ocean_1.png")
plot(s, which="map")
atlantic <- subset(s, ocean="A")
pacific <- subset(s, ocean="P")
points(atlantic[["longitude"]], atlantic[["latitude"]], pch=20, col=2, cex=0.7*par("cex"))
points(pacific[["longitude"]], pacific[["latitude"]], pch=20, col=3, cex=0.7*par("cex"))
if (!interactive()) dev.off()

if (!interactive()) png("03_by_ocean_2.png")


if (setup) {
    axy <- locator(20, type="o")
    sink('a');dput(axy);sink()
} else {
    axy <- list(x = c(-83.58, -83.83, -83.3, -82.51, -81.65, -80.40, -79.35,
                      -78.42, -78.51),
                y = c(13.639, 11.97, 10.19, 9.44, 8.84, 9.01, 9.38, 9.405, 13.53))
}

if (setup) {
    bxy <- locator(20, type="o")
    sink('b');dput(bxy);sink()
} else {
    bxy <- list(x = c(-86.70, -85.87, -84.52, -83.26, -81.73, -80.21, -78.49,
                      -78.53, -87.62, -87.65),
                y = c(11.62, 10.50, 9.72, 8.73, 8.24, 8.42, 8.66, 4.38, 4.39,
                      11.64))
}

plot(s, which="map")
polygon(axy, border="blue", lwd=3)
A <- subset(s, polygon=list(longitude=axy$x, latitude=axy$y))
points(A[["longitude"]], A[["latitude"]], col="blue", pch=20)

polygon(bxy, border="red", lwd=3)
P <- subset(s, polygon=list(longitude=bxy$x, latitude=bxy$y))
points(P[["longitude"]], P[["latitude"]], col="red", pch=20)

if (!interactive()) dev.off()
```
![03_by_ocean_2](https://user-images.githubusercontent.com/99469/80980456-08151e00-8dff-11ea-8137-831ec18e89f8.png)

**Comment by dankelley** [comment]
I switched from `sf` to `sp` and it works now.  I am not totally surprised, since `sf` is a newer package, and is still in development.

I'll leave this open until the test suite and automated builds say that things are okay.

![03_by_ocean_2](https://user-images.githubusercontent.com/99469/80995801-39004d80-8e15-11ea-8812-ea6e59332876.png)

**Comment by richardsc** [comment]
I know you've closed the issue, but does this seem like something that should be reported as an `sf` issue?

**Comment by dankelley** [comment]
Yes, I thought the same, and plan to see if I an make a reproducible (but pared-down) example.

**Comment by dankelley** [comment]
Hm.  I made a simplified example, and it works as expected.  (These are the two points that were coming out red in the first image above.) 

I'll look at this again tomorrow to see if I made an error in my cut/paste work, but it seems like this error may be something subtle, possibly demanding the whole dataset ... stuff like that can happen, especially if the problem is happening down at the C level.  

NB. the `sf` package uses code that exists *outside* the package, so sometimes what seems like an `sf` error is really an error in that outside code.
```R
x <- c(-80.867, -80.190)
y <- c(9.176, 10.405)
polx <- c(-86.70, -85.87, -84.52, -83.26, -81.73, -80.21, -78.49, -78.53, -87.62, -87.65, -86.70)
poly <- c(11.62, 10.50, 9.72, 8.73, 8.24, 8.42, 8.66, 4.38, 4.39, 11.64, 11.62)
polygon <- sf::st_polygon(list(outer=cbind(polx, poly)))
stopifnot(sf::st_is_valid(polygon))
points <- sf::st_multipoint(cbind(x, y))
stopifnot(sf::st_is_valid(points))
sf::st_intersection(points, polygon)
```

**Comment by richardsc** [comment]
I will try this on my windows and Linux systems, to see the results. 

Not sure what you mean by “code outside the package” since if it comes from CRAN shouldn’t it have all libraries included in the binary package?

**Comment by dankelley** [comment]
Yes, but I think the `sf` authors take their responsibility to end with the code that they provide.  But I may be thinking of `rgdal`, though, in terms of `gdal`, which is separately installed (and used by different packages, I think).

Probably tomorrow morning I'll make a test with the whole dataset (but not hooked at all to our package.  If that fails, I'll try paring down, to see if I can make the dataset smaller but still able to show an error.

Most likely, though, I was just doing something wrong in argoFloats.  Frankly, though, if `sp` works and `sf` doesn't, I'm happy to just use `sp` for this, at least for now.  (We plan a video on Thursday, and we cannot do that with the code using `sf`.) 

PS. There are other packages that can handle point-in-polygon calculations, too.

**Comment by richardsc** [comment]
I can confirm I get the same thing with the `sf` dependency in linux:
![image](https://user-images.githubusercontent.com/233584/81134014-bc12c800-8f29-11ea-9d70-261874b99ad9.png)

And on WIndoze:
![image](https://user-images.githubusercontent.com/233584/81135090-2a0cbe80-8f2d-11ea-884d-74426e423274.png)

**Comment by dankelley** [comment]
I know how to solve this now in `sf` and will do that on Saturday.  A higher priority now is #82, which I won't go in to in much details since it was discussed at length in a vf2f earlier today.

**Comment by dankelley** [comment]
Fixed in "develop" and "master" branches.
