### ISSUE TITLE
Tweak to youtube video names

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#87]
Youtube videos one and two are named argofloats R 01: Introduction and argofloats R 02: TS plot near Bermuda respectively, where the 'F' in argoFloats should be capitalized in each if that is possible. Video three is ok!

**Comment by dankelley** [comment]
Good catch!!

I think I've fixed this.  Maybe you can check, and close the issue if so, or tell me of remaining problems if not.
