### ISSUE TITLE
update sandbox for renaming of 'file' getIndex() arg

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#88]
Jaimie, I have altered `getIndex()` (in both the "develop" and "master" branches) so the `file` argument is now `filename`.  The reason for this has to do with the simplifications in the "[[" operator (it avoids a conflict with the names of netcdf files).

When I run Show Diagnostics, it tells me that some of your sandbox files are using `getIndex(file=` instances, which ought to be `getIndx(filename=` now.

I know it's just sandbox code, but since it is in the repo, a user might copy it, and therefore it ought to state the first argument in the new way.

Can you go through your sandbox code and update it, please?  This Show Diagnostics action is very quick, so I'd suggest doing them a file at a time, to get the hang of it.

I think I've caught all the examples in the documentation pages and the vignette, but if you ever run across such, please let me know (but don't change the Roxygen, because I'm altering quite a lot of that in my code reframing, so we'll get git-merge conflicts if two of us are altering a given line).

Thanks, and have a great weekend!

D.

<img width="764" alt="Screen Shot 2020-05-08 at 1 23 51 PM" src="https://user-images.githubusercontent.com/99469/81427465-3a8d8680-9131-11ea-88c3-16578356ab58.png">

**Comment by j-harbin** [comment]
Commit # 2195e0d of the develop branch solves this issue. Please have a look and if you feel it addresses this issue, feel free to close this issue.

**Comment by dankelley** [comment]
Excellent, thanks!  Closing now.
