### ISSUE TITLE
Creating Video 5

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#89]
As discussed in the vftf with @dankelley , a good idea for the fifth video would be creating a TS diagram that is colour coded for oxygen near Bahamas.

This would show
- subset by circle
-subset by parameter ("DOXY")
- link to the oce package
-Paper by Thyng et al. (referenced below)

Thyng, Kristen M., Chad A. Greene, Robert D. Hetland, Heather M. Zimmerle, and Steven F. DiMarco. "True colors of oceanography: Guidelines for effective and accurate colormap selection." Oceanography 29, no. 3 (2016): 9-13.

**Comment by dankelley** [comment]
This is done and uploaded to https://www.youtube.com/watch?v=Y_SxjcOnW04&feature=youtu.be

Good work, team!

**Comment by richardsc** [comment]
Hahaha ... I only got as far as the "I'm not Jaimie, but I *am* Dan Kelley!". Nice one 😄
