### ISSUE TITLE
[[ should handle "ID"

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#90]
This item is not stored in the `@data` slot, and I am not proposing that it be stored there, because there is a real benefit in storing exactly what is in the source data file.

However, it would be very handy to be able to do
```R
index[["id"]]
```
which would, internally, look at
```R
index[["file"]]
```
and do a `gsub()` operation to extract the ID of the float.

I can do this pretty easily, but it would be better for the project for @j-harbin to do it; I can guide the work in a vf2f paired programming session.

**Comment by richardsc** [comment]
Vote of +1 for this!

**Comment by dankelley** [comment]
FYI, during a vf2f today, @j-harbin and I realized that the name should be `ID`, not `id`, and so I've edited the issue subject line.

**Comment by j-harbin** [comment]
I've created a branch and pushed what I have so far at commit #a2c1759 of branch issue90. When I do
```R
library(argoFloats)
data('index')
index[['ID']]
```
however, I receive the error:

```R
Error in index[["ID"]] : 
  the object type must be "index", "profiles", or "argos", but it is "index" 
```
Which tells me I'm not quite there.

**Comment by dankelley** [comment]
Done in "develop" and "master" branches, in a vf2f coding session (D and J).
