### ISSUE TITLE
Consider adding topography to map type

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#97]
As discussed in the vftf with @dankelley , it could be a good idea to add topography to map type.

**Comment by j-harbin** [comment]
When doing the following code:
```R
library(argoFloats)
data("index")
plot(index, bathymetry=TRUE)
```

I receive the following error:

```R
Error in if (ncol(x) == 3 & !exists("bathy", inherits = FALSE)) { : 
  argument is of length zero 
```

We can chat about this in our vftf today @dankelley, I just wanted to write it down so I didn't forget!

**Comment by dankelley** [comment]
I was getting the same yesterday.  Before our vf2f today, could you pull and rebuild "develop", and retest?

**Comment by j-harbin** [comment]
I just pulled, clean and rebuilt, and restarted R and received the same error.

**Comment by dankelley** [comment]
A. Can you pull, clean, and rebuild, and then test?

B. If that fails, can you add
```R
library(marmap)
```
to your code before you plot?  (The problem is inside marmap, somewhere).

**Comment by j-harbin** [comment]
This is now added, and the error no longer exists since installing the packages `rgdal` and `raster`. I am therefore closing this issue.
