### ISSUE TITLE
plot(..., which="map"): alter point type?

### ISSUE THREAD

**Issue by dankelley** [ArgoCanada/argoFloats#98]
In working on #97 I made the graph shown below.  I find that it's a bit hard to see the float locations.   I chose grey because it was not too glaring, but now I find that the points are a bit hard to see, if we use a topographic underlay with the pretty-much-standard GEBCO colour scheme (as shown).

Of course, the user can set any colour they want for the points, but I want the default to be clearer.  Therefore I'm thinking of changing it to red (a colour that is not commonly used in showing topography).

@j-harbin -- can you think about this, and add a comment with your opinion.

PS. the code to make this graph is not yet pushed to github, since I've not run checks, or reread the docs that I've just written.

![A](https://user-images.githubusercontent.com/99469/82371994-870a7900-99f1-11ea-8729-3b3233248f04.png)

**Comment by j-harbin** [comment]
I agree that the points are hard to see. Changing them to red would definitely help this issue. +1 from me.

**Comment by j-harbin** [comment]
Also, beautiful plot :)

**Comment by dankelley** [comment]
I think I'll make them a darker gray, because I want users to be able to show things easily with numbered colours, like
```R
points(lonSelected, latSelected, pch=20, col=2) # red
```

I am making it so you can do
```R
plot(index, which="map", bathymetry=TRUE)
```
and it downloads the bathy data for you.

PS. I am renaming the argument as `bathymetry` because we only show the water colours -- the land comes out as a bland monotone ... because argo floats never go on land :-)

**Comment by dankelley** [comment]
@j-harbin: I'm playing with different plot choices.  Can you comment on whether your preference from the trials shown below, and give any other suggestions that come to mind?  (We could do a 1000h or 1030h vf2f if that's easier.)

I think I lean towards version 7.

Of course, the user can set anything they want, but it's the default that will be seen in videos and in most work, so I want to get four eyes looking at this, in hopes of making a reasonable default choice.

## 1 pch=20, cex=1, col=1

![Rplot01](https://user-images.githubusercontent.com/99469/82446555-3a6c7f80-9a7d-11ea-9e13-72734b607b44.png)

## 2 pch=1, cex=1, col=1

![Rplot02](https://user-images.githubusercontent.com/99469/82446576-43f5e780-9a7d-11ea-9dd8-5a89402a1387.png)

## 3 pch=1, cex=1, col=2

![Rplot03](https://user-images.githubusercontent.com/99469/82446804-b5359a80-9a7d-11ea-922a-8f9f64eefe72.png)

## 4 pch=20, cex=0.8, col=2

![Rplot04](https://user-images.githubusercontent.com/99469/82446959-f2019180-9a7d-11ea-9ef0-0bfab44dcde4.png)

## 5 pch=20, cex=0.8, col="red"

![Rplot05](https://user-images.githubusercontent.com/99469/82447300-7b18c880-9a7e-11ea-933b-84c00a231837.png)

## 6 pch=21, cex=1, col="black", bg="red"

![Rplot06](https://user-images.githubusercontent.com/99469/82447950-5f61f200-9a7f-11ea-8167-021cd81c54bf.png)

## 7 pch=21, cex=1, col="black", bg="pink"

![Rplot07](https://user-images.githubusercontent.com/99469/82448087-a3ed8d80-9a7f-11ea-8c33-caa977e9d025.png)

**Comment by j-harbin** [comment]
I like the look of 7, but 9 makes the Argos stand out more. What this tells me is I am indecisive, but for practicality purposes I agree that 9 is a great choice.

**Comment by j-harbin** [comment]
Dear reporter,

Do you think this issue (as defined by its title) has been addressed? If so, please close it. If not, please add a comment explaining what remains to be done. Thanks!

PS. This is a standardized reply.

**Comment by dankelley** [comment]
Yes, closing now
