### ISSUE TITLE
Addition to description of video 2 on youtube

### ISSUE THREAD

**Issue by j-harbin** [ArgoCanada/argoFloats#99]
In our second YouTube video at 5 minutes we are talking about `getIndex()`. At this point the argument within `getIndex()` was `file` instead of `filename`. It may be a good idea to mention within the description of the video that the argument is now changed.

**Comment by dankelley** [comment]
I've updated it, at https://youtu.be/ZoTrVEMG5Qo ... maybe you can check the wording, and close this if it's okay?

PS. I did not see how to use a "code" font for code, so I just used quote marks.

**Comment by j-harbin** [comment]
Wording is great except where it says "Note that the video refers to the 'file' argument of the 'index()' function", it should be "getIndex()" function :-)

**Comment by dankelley** [comment]
Thanks. I fixed that error, so I'm closing this now.
